// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: storage/v1/storage.proto

package storagev1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteBackupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Fence               *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	PolicyId            string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	BackupId            string                 `protobuf:"bytes,3,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	SourceTargetId      string                 `protobuf:"bytes,4,opt,name=source_target_id,json=sourceTargetId,proto3" json:"source_target_id,omitempty"`
	DestinationTargetId string                 `protobuf:"bytes,5,opt,name=destination_target_id,json=destinationTargetId,proto3" json:"destination_target_id,omitempty"`
	ObjectSetDigest     string                 `protobuf:"bytes,6,opt,name=object_set_digest,json=objectSetDigest,proto3" json:"object_set_digest,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteBackupRequest) Reset() {
	*x = ExecuteBackupRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBackupRequest) ProtoMessage() {}

func (x *ExecuteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBackupRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBackupRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteBackupRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ExecuteBackupRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ExecuteBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *ExecuteBackupRequest) GetSourceTargetId() string {
	if x != nil {
		return x.SourceTargetId
	}
	return ""
}

func (x *ExecuteBackupRequest) GetDestinationTargetId() string {
	if x != nil {
		return x.DestinationTargetId
	}
	return ""
}

func (x *ExecuteBackupRequest) GetObjectSetDigest() string {
	if x != nil {
		return x.ObjectSetDigest
	}
	return ""
}

type ExecuteRestoreRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Fence               *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	PolicyId            string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	BackupId            string                 `protobuf:"bytes,3,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	SourceTargetId      string                 `protobuf:"bytes,4,opt,name=source_target_id,json=sourceTargetId,proto3" json:"source_target_id,omitempty"`
	DestinationTargetId string                 `protobuf:"bytes,5,opt,name=destination_target_id,json=destinationTargetId,proto3" json:"destination_target_id,omitempty"`
	ObjectSetDigest     string                 `protobuf:"bytes,6,opt,name=object_set_digest,json=objectSetDigest,proto3" json:"object_set_digest,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteRestoreRequest) Reset() {
	*x = ExecuteRestoreRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRestoreRequest) ProtoMessage() {}

func (x *ExecuteRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRestoreRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRestoreRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteRestoreRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ExecuteRestoreRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ExecuteRestoreRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *ExecuteRestoreRequest) GetSourceTargetId() string {
	if x != nil {
		return x.SourceTargetId
	}
	return ""
}

func (x *ExecuteRestoreRequest) GetDestinationTargetId() string {
	if x != nil {
		return x.DestinationTargetId
	}
	return ""
}

func (x *ExecuteRestoreRequest) GetObjectSetDigest() string {
	if x != nil {
		return x.ObjectSetDigest
	}
	return ""
}

type ExecuteRepairRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Fence               *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	PolicyId            string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	BackupId            string                 `protobuf:"bytes,3,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	SourceTargetId      string                 `protobuf:"bytes,4,opt,name=source_target_id,json=sourceTargetId,proto3" json:"source_target_id,omitempty"`
	DestinationTargetId string                 `protobuf:"bytes,5,opt,name=destination_target_id,json=destinationTargetId,proto3" json:"destination_target_id,omitempty"`
	ObjectSetDigest     string                 `protobuf:"bytes,6,opt,name=object_set_digest,json=objectSetDigest,proto3" json:"object_set_digest,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteRepairRequest) Reset() {
	*x = ExecuteRepairRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRepairRequest) ProtoMessage() {}

func (x *ExecuteRepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRepairRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRepairRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRepairRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ExecuteRepairRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ExecuteRepairRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *ExecuteRepairRequest) GetSourceTargetId() string {
	if x != nil {
		return x.SourceTargetId
	}
	return ""
}

func (x *ExecuteRepairRequest) GetDestinationTargetId() string {
	if x != nil {
		return x.DestinationTargetId
	}
	return ""
}

func (x *ExecuteRepairRequest) GetObjectSetDigest() string {
	if x != nil {
		return x.ObjectSetDigest
	}
	return ""
}

type ExecuteRebalanceRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Fence               *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	PolicyId            string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	BackupId            string                 `protobuf:"bytes,3,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	SourceTargetId      string                 `protobuf:"bytes,4,opt,name=source_target_id,json=sourceTargetId,proto3" json:"source_target_id,omitempty"`
	DestinationTargetId string                 `protobuf:"bytes,5,opt,name=destination_target_id,json=destinationTargetId,proto3" json:"destination_target_id,omitempty"`
	ObjectSetDigest     string                 `protobuf:"bytes,6,opt,name=object_set_digest,json=objectSetDigest,proto3" json:"object_set_digest,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteRebalanceRequest) Reset() {
	*x = ExecuteRebalanceRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRebalanceRequest) ProtoMessage() {}

func (x *ExecuteRebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRebalanceRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRebalanceRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRebalanceRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ExecuteRebalanceRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ExecuteRebalanceRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *ExecuteRebalanceRequest) GetSourceTargetId() string {
	if x != nil {
		return x.SourceTargetId
	}
	return ""
}

func (x *ExecuteRebalanceRequest) GetDestinationTargetId() string {
	if x != nil {
		return x.DestinationTargetId
	}
	return ""
}

func (x *ExecuteRebalanceRequest) GetObjectSetDigest() string {
	if x != nil {
		return x.ObjectSetDigest
	}
	return ""
}

type StorageEffectResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Fence           *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	State           commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	EffectId        string                 `protobuf:"bytes,3,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	ReceiptDigest   string                 `protobuf:"bytes,4,opt,name=receipt_digest,json=receiptDigest,proto3" json:"receipt_digest,omitempty"`
	CommitDigest    string                 `protobuf:"bytes,5,opt,name=commit_digest,json=commitDigest,proto3" json:"commit_digest,omitempty"`
	ProofDigest     string                 `protobuf:"bytes,6,opt,name=proof_digest,json=proofDigest,proto3" json:"proof_digest,omitempty"`
	ObjectSetDigest string                 `protobuf:"bytes,7,opt,name=object_set_digest,json=objectSetDigest,proto3" json:"object_set_digest,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StorageEffectResult) Reset() {
	*x = StorageEffectResult{}
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageEffectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageEffectResult) ProtoMessage() {}

func (x *StorageEffectResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageEffectResult.ProtoReflect.Descriptor instead.
func (*StorageEffectResult) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *StorageEffectResult) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *StorageEffectResult) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *StorageEffectResult) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *StorageEffectResult) GetReceiptDigest() string {
	if x != nil {
		return x.ReceiptDigest
	}
	return ""
}

func (x *StorageEffectResult) GetCommitDigest() string {
	if x != nil {
		return x.CommitDigest
	}
	return ""
}

func (x *StorageEffectResult) GetProofDigest() string {
	if x != nil {
		return x.ProofDigest
	}
	return ""
}

func (x *StorageEffectResult) GetObjectSetDigest() string {
	if x != nil {
		return x.ObjectSetDigest
	}
	return ""
}

var File_storage_v1_storage_proto protoreflect.FileDescriptor

const file_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/storage.proto\x12\x13deepseek.storage.v1\x1a\x16common/v1/common.proto\"\x91\x02\n" +
	"\x14ExecuteBackupRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\x1b\n" +
	"\tbackup_id\x18\x03 \x01(\tR\bbackupId\x12(\n" +
	"\x10source_target_id\x18\x04 \x01(\tR\x0esourceTargetId\x122\n" +
	"\x15destination_target_id\x18\x05 \x01(\tR\x13destinationTargetId\x12*\n" +
	"\x11object_set_digest\x18\x06 \x01(\tR\x0fobjectSetDigest\"\x92\x02\n" +
	"\x15ExecuteRestoreRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\x1b\n" +
	"\tbackup_id\x18\x03 \x01(\tR\bbackupId\x12(\n" +
	"\x10source_target_id\x18\x04 \x01(\tR\x0esourceTargetId\x122\n" +
	"\x15destination_target_id\x18\x05 \x01(\tR\x13destinationTargetId\x12*\n" +
	"\x11object_set_digest\x18\x06 \x01(\tR\x0fobjectSetDigest\"\x91\x02\n" +
	"\x14ExecuteRepairRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\x1b\n" +
	"\tbackup_id\x18\x03 \x01(\tR\bbackupId\x12(\n" +
	"\x10source_target_id\x18\x04 \x01(\tR\x0esourceTargetId\x122\n" +
	"\x15destination_target_id\x18\x05 \x01(\tR\x13destinationTargetId\x12*\n" +
	"\x11object_set_digest\x18\x06 \x01(\tR\x0fobjectSetDigest\"\x94\x02\n" +
	"\x17ExecuteRebalanceRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\x1b\n" +
	"\tbackup_id\x18\x03 \x01(\tR\bbackupId\x12(\n" +
	"\x10source_target_id\x18\x04 \x01(\tR\x0esourceTargetId\x122\n" +
	"\x15destination_target_id\x18\x05 \x01(\tR\x13destinationTargetId\x12*\n" +
	"\x11object_set_digest\x18\x06 \x01(\tR\x0fobjectSetDigest\"\xbb\x02\n" +
	"\x13StorageEffectResult\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x12\x1b\n" +
	"\teffect_id\x18\x03 \x01(\tR\beffectId\x12%\n" +
	"\x0ereceipt_digest\x18\x04 \x01(\tR\rreceiptDigest\x12#\n" +
	"\rcommit_digest\x18\x05 \x01(\tR\fcommitDigest\x12!\n" +
	"\fproof_digest\x18\x06 \x01(\tR\vproofDigest\x12*\n" +
	"\x11object_set_digest\x18\a \x01(\tR\x0fobjectSetDigestBJZHgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/storagev1;storagev1b\x06proto3"

var (
	file_storage_v1_storage_proto_rawDescOnce sync.Once
	file_storage_v1_storage_proto_rawDescData []byte
)

func file_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)))
	})
	return file_storage_v1_storage_proto_rawDescData
}

var file_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_storage_v1_storage_proto_goTypes = []any{
	(*ExecuteBackupRequest)(nil),    // 0: deepseek.storage.v1.ExecuteBackupRequest
	(*ExecuteRestoreRequest)(nil),   // 1: deepseek.storage.v1.ExecuteRestoreRequest
	(*ExecuteRepairRequest)(nil),    // 2: deepseek.storage.v1.ExecuteRepairRequest
	(*ExecuteRebalanceRequest)(nil), // 3: deepseek.storage.v1.ExecuteRebalanceRequest
	(*StorageEffectResult)(nil),     // 4: deepseek.storage.v1.StorageEffectResult
	(*commonv1.ActionFence)(nil),    // 5: deepseek.common.v1.ActionFence
	(commonv1.EffectState)(0),       // 6: deepseek.common.v1.EffectState
}
var file_storage_v1_storage_proto_depIdxs = []int32{
	5, // 0: deepseek.storage.v1.ExecuteBackupRequest.fence:type_name -> deepseek.common.v1.ActionFence
	5, // 1: deepseek.storage.v1.ExecuteRestoreRequest.fence:type_name -> deepseek.common.v1.ActionFence
	5, // 2: deepseek.storage.v1.ExecuteRepairRequest.fence:type_name -> deepseek.common.v1.ActionFence
	5, // 3: deepseek.storage.v1.ExecuteRebalanceRequest.fence:type_name -> deepseek.common.v1.ActionFence
	5, // 4: deepseek.storage.v1.StorageEffectResult.fence:type_name -> deepseek.common.v1.ActionFence
	6, // 5: deepseek.storage.v1.StorageEffectResult.state:type_name -> deepseek.common.v1.EffectState
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_storage_v1_storage_proto_init() }
func file_storage_v1_storage_proto_init() {
	if File_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_storage_v1_storage_proto = out.File
	file_storage_v1_storage_proto_goTypes = nil
	file_storage_v1_storage_proto_depIdxs = nil
}
