// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: federation/v1/federation.proto

package federationv1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteFederatedTransferRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Fence              *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	TransferId         string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	SourceFleetId      string                 `protobuf:"bytes,3,opt,name=source_fleet_id,json=sourceFleetId,proto3" json:"source_fleet_id,omitempty"`
	DestinationFleetId string                 `protobuf:"bytes,4,opt,name=destination_fleet_id,json=destinationFleetId,proto3" json:"destination_fleet_id,omitempty"`
	BackupId           string                 `protobuf:"bytes,5,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	ObjectSetDigest    string                 `protobuf:"bytes,6,opt,name=object_set_digest,json=objectSetDigest,proto3" json:"object_set_digest,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteFederatedTransferRequest) Reset() {
	*x = ExecuteFederatedTransferRequest{}
	mi := &file_federation_v1_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFederatedTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFederatedTransferRequest) ProtoMessage() {}

func (x *ExecuteFederatedTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_v1_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFederatedTransferRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFederatedTransferRequest) Descriptor() ([]byte, []int) {
	return file_federation_v1_federation_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteFederatedTransferRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ExecuteFederatedTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ExecuteFederatedTransferRequest) GetSourceFleetId() string {
	if x != nil {
		return x.SourceFleetId
	}
	return ""
}

func (x *ExecuteFederatedTransferRequest) GetDestinationFleetId() string {
	if x != nil {
		return x.DestinationFleetId
	}
	return ""
}

func (x *ExecuteFederatedTransferRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *ExecuteFederatedTransferRequest) GetObjectSetDigest() string {
	if x != nil {
		return x.ObjectSetDigest
	}
	return ""
}

type SignReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	FleetId       string                 `protobuf:"bytes,2,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	PayloadDigest string                 `protobuf:"bytes,3,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignReadinessRequest) Reset() {
	*x = SignReadinessRequest{}
	mi := &file_federation_v1_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReadinessRequest) ProtoMessage() {}

func (x *SignReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_v1_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReadinessRequest.ProtoReflect.Descriptor instead.
func (*SignReadinessRequest) Descriptor() ([]byte, []int) {
	return file_federation_v1_federation_proto_rawDescGZIP(), []int{1}
}

func (x *SignReadinessRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *SignReadinessRequest) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *SignReadinessRequest) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

type SignReadinessResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Fence                *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKeyFingerprint string                 `protobuf:"bytes,3,opt,name=public_key_fingerprint,json=publicKeyFingerprint,proto3" json:"public_key_fingerprint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SignReadinessResponse) Reset() {
	*x = SignReadinessResponse{}
	mi := &file_federation_v1_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReadinessResponse) ProtoMessage() {}

func (x *SignReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_v1_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReadinessResponse.ProtoReflect.Descriptor instead.
func (*SignReadinessResponse) Descriptor() ([]byte, []int) {
	return file_federation_v1_federation_proto_rawDescGZIP(), []int{2}
}

func (x *SignReadinessResponse) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *SignReadinessResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignReadinessResponse) GetPublicKeyFingerprint() string {
	if x != nil {
		return x.PublicKeyFingerprint
	}
	return ""
}

type FederationEffectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	State         commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	TransferId    string                 `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ReceiptDigest string                 `protobuf:"bytes,4,opt,name=receipt_digest,json=receiptDigest,proto3" json:"receipt_digest,omitempty"`
	CommitDigest  string                 `protobuf:"bytes,5,opt,name=commit_digest,json=commitDigest,proto3" json:"commit_digest,omitempty"`
	ProofDigest   string                 `protobuf:"bytes,6,opt,name=proof_digest,json=proofDigest,proto3" json:"proof_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationEffectResult) Reset() {
	*x = FederationEffectResult{}
	mi := &file_federation_v1_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationEffectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationEffectResult) ProtoMessage() {}

func (x *FederationEffectResult) ProtoReflect() protoreflect.Message {
	mi := &file_federation_v1_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationEffectResult.ProtoReflect.Descriptor instead.
func (*FederationEffectResult) Descriptor() ([]byte, []int) {
	return file_federation_v1_federation_proto_rawDescGZIP(), []int{3}
}

func (x *FederationEffectResult) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *FederationEffectResult) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *FederationEffectResult) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FederationEffectResult) GetReceiptDigest() string {
	if x != nil {
		return x.ReceiptDigest
	}
	return ""
}

func (x *FederationEffectResult) GetCommitDigest() string {
	if x != nil {
		return x.CommitDigest
	}
	return ""
}

func (x *FederationEffectResult) GetProofDigest() string {
	if x != nil {
		return x.ProofDigest
	}
	return ""
}

var File_federation_v1_federation_proto protoreflect.FileDescriptor

const file_federation_v1_federation_proto_rawDesc = "" +
	"\n" +
	"\x1efederation/v1/federation.proto\x12\x16deepseek.federation.v1\x1a\x16common/v1/common.proto\"\x9c\x02\n" +
	"\x1fExecuteFederatedTransferRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12&\n" +
	"\x0fsource_fleet_id\x18\x03 \x01(\tR\rsourceFleetId\x120\n" +
	"\x14destination_fleet_id\x18\x04 \x01(\tR\x12destinationFleetId\x12\x1b\n" +
	"\tbackup_id\x18\x05 \x01(\tR\bbackupId\x12*\n" +
	"\x11object_set_digest\x18\x06 \x01(\tR\x0fobjectSetDigest\"\x8f\x01\n" +
	"\x14SignReadinessRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x19\n" +
	"\bfleet_id\x18\x02 \x01(\tR\afleetId\x12%\n" +
	"\x0epayload_digest\x18\x03 \x01(\tR\rpayloadDigest\"\xa2\x01\n" +
	"\x15SignReadinessResponse\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x124\n" +
	"\x16public_key_fingerprint\x18\x03 \x01(\tR\x14publicKeyFingerprint\"\x96\x02\n" +
	"\x16FederationEffectResult\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x12\x1f\n" +
	"\vtransfer_id\x18\x03 \x01(\tR\n" +
	"transferId\x12%\n" +
	"\x0ereceipt_digest\x18\x04 \x01(\tR\rreceiptDigest\x12#\n" +
	"\rcommit_digest\x18\x05 \x01(\tR\fcommitDigest\x12!\n" +
	"\fproof_digest\x18\x06 \x01(\tR\vproofDigestBPZNgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/federationv1;federationv1b\x06proto3"

var (
	file_federation_v1_federation_proto_rawDescOnce sync.Once
	file_federation_v1_federation_proto_rawDescData []byte
)

func file_federation_v1_federation_proto_rawDescGZIP() []byte {
	file_federation_v1_federation_proto_rawDescOnce.Do(func() {
		file_federation_v1_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federation_v1_federation_proto_rawDesc), len(file_federation_v1_federation_proto_rawDesc)))
	})
	return file_federation_v1_federation_proto_rawDescData
}

var file_federation_v1_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_federation_v1_federation_proto_goTypes = []any{
	(*ExecuteFederatedTransferRequest)(nil), // 0: deepseek.federation.v1.ExecuteFederatedTransferRequest
	(*SignReadinessRequest)(nil),            // 1: deepseek.federation.v1.SignReadinessRequest
	(*SignReadinessResponse)(nil),           // 2: deepseek.federation.v1.SignReadinessResponse
	(*FederationEffectResult)(nil),          // 3: deepseek.federation.v1.FederationEffectResult
	(*commonv1.ActionFence)(nil),            // 4: deepseek.common.v1.ActionFence
	(commonv1.EffectState)(0),               // 5: deepseek.common.v1.EffectState
}
var file_federation_v1_federation_proto_depIdxs = []int32{
	4, // 0: deepseek.federation.v1.ExecuteFederatedTransferRequest.fence:type_name -> deepseek.common.v1.ActionFence
	4, // 1: deepseek.federation.v1.SignReadinessRequest.fence:type_name -> deepseek.common.v1.ActionFence
	4, // 2: deepseek.federation.v1.SignReadinessResponse.fence:type_name -> deepseek.common.v1.ActionFence
	4, // 3: deepseek.federation.v1.FederationEffectResult.fence:type_name -> deepseek.common.v1.ActionFence
	5, // 4: deepseek.federation.v1.FederationEffectResult.state:type_name -> deepseek.common.v1.EffectState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_federation_v1_federation_proto_init() }
func file_federation_v1_federation_proto_init() {
	if File_federation_v1_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federation_v1_federation_proto_rawDesc), len(file_federation_v1_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_federation_v1_federation_proto_goTypes,
		DependencyIndexes: file_federation_v1_federation_proto_depIdxs,
		MessageInfos:      file_federation_v1_federation_proto_msgTypes,
	}.Build()
	File_federation_v1_federation_proto = out.File
	file_federation_v1_federation_proto_goTypes = nil
	file_federation_v1_federation_proto_depIdxs = nil
}
