// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: evidence/v1/evidence.proto

package evidencev1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvidenceBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	EnvelopeType  string                 `protobuf:"bytes,2,opt,name=envelope_type,json=envelopeType,proto3" json:"envelope_type,omitempty"`
	ProofType     string                 `protobuf:"bytes,3,opt,name=proof_type,json=proofType,proto3" json:"proof_type,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceBinding) Reset() {
	*x = EvidenceBinding{}
	mi := &file_evidence_v1_evidence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceBinding) ProtoMessage() {}

func (x *EvidenceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_evidence_v1_evidence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceBinding.ProtoReflect.Descriptor instead.
func (*EvidenceBinding) Descriptor() ([]byte, []int) {
	return file_evidence_v1_evidence_proto_rawDescGZIP(), []int{0}
}

func (x *EvidenceBinding) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *EvidenceBinding) GetEnvelopeType() string {
	if x != nil {
		return x.EnvelopeType
	}
	return ""
}

func (x *EvidenceBinding) GetProofType() string {
	if x != nil {
		return x.ProofType
	}
	return ""
}

func (x *EvidenceBinding) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

var File_evidence_v1_evidence_proto protoreflect.FileDescriptor

const file_evidence_v1_evidence_proto_rawDesc = "" +
	"\n" +
	"\x1aevidence/v1/evidence.proto\x12\x14deepseek.evidence.v1\x1a\x16common/v1/common.proto\"\xa4\x01\n" +
	"\x0fEvidenceBinding\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12#\n" +
	"\renvelope_type\x18\x02 \x01(\tR\fenvelopeType\x12\x1d\n" +
	"\n" +
	"proof_type\x18\x03 \x01(\tR\tproofType\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digestBLZJgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/evidencev1;evidencev1b\x06proto3"

var (
	file_evidence_v1_evidence_proto_rawDescOnce sync.Once
	file_evidence_v1_evidence_proto_rawDescData []byte
)

func file_evidence_v1_evidence_proto_rawDescGZIP() []byte {
	file_evidence_v1_evidence_proto_rawDescOnce.Do(func() {
		file_evidence_v1_evidence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evidence_v1_evidence_proto_rawDesc), len(file_evidence_v1_evidence_proto_rawDesc)))
	})
	return file_evidence_v1_evidence_proto_rawDescData
}

var file_evidence_v1_evidence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_evidence_v1_evidence_proto_goTypes = []any{
	(*EvidenceBinding)(nil),      // 0: deepseek.evidence.v1.EvidenceBinding
	(*commonv1.ActionFence)(nil), // 1: deepseek.common.v1.ActionFence
}
var file_evidence_v1_evidence_proto_depIdxs = []int32{
	1, // 0: deepseek.evidence.v1.EvidenceBinding.fence:type_name -> deepseek.common.v1.ActionFence
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_evidence_v1_evidence_proto_init() }
func file_evidence_v1_evidence_proto_init() {
	if File_evidence_v1_evidence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evidence_v1_evidence_proto_rawDesc), len(file_evidence_v1_evidence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evidence_v1_evidence_proto_goTypes,
		DependencyIndexes: file_evidence_v1_evidence_proto_depIdxs,
		MessageInfos:      file_evidence_v1_evidence_proto_msgTypes,
	}.Build()
	File_evidence_v1_evidence_proto = out.File
	file_evidence_v1_evidence_proto_goTypes = nil
	file_evidence_v1_evidence_proto_depIdxs = nil
}
