from __future__ import annotations

from pathlib import Path

from scripts.check_go_coverage import is_generated_only_package
from scripts.run_rust_coverage import GENERATED_PROTO_COVERAGE_OMIT


ROOT = Path(__file__).resolve().parents[1]


def test_generated_only_go_package_is_excluded_from_business_coverage(tmp_path: Path) -> None:
    package = tmp_path / "generated"
    package.mkdir()
    (package / "contract.pb.go").write_text(
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage generated\n",
        encoding="utf-8",
    )

    assert is_generated_only_package(package, ["contract.pb.go"]) is True


def test_package_with_handwritten_go_remains_in_business_coverage(tmp_path: Path) -> None:
    package = tmp_path / "mixed"
    package.mkdir()
    (package / "contract.pb.go").write_text(
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage mixed\n",
        encoding="utf-8",
    )
    (package / "fence.go").write_text("package mixed\n", encoding="utf-8")

    assert is_generated_only_package(package, ["contract.pb.go", "fence.go"]) is False


def test_generated_marker_cannot_hide_non_pb_go_source(tmp_path: Path) -> None:
    package = tmp_path / "spoofed"
    package.mkdir()
    (package / "business.go").write_text(
        "// Code generated by fake. DO NOT EDIT.\npackage spoofed\n",
        encoding="utf-8",
    )

    assert is_generated_only_package(package, ["business.go"]) is False


def test_rust_coverage_omits_only_generated_proto_out_dir_sources() -> None:
    assert "target" in GENERATED_PROTO_COVERAGE_OMIT
    assert "build" in GENERATED_PROTO_COVERAGE_OMIT
    assert "deepseek-protocol" in GENERATED_PROTO_COVERAGE_OMIT
    assert "out" in GENERATED_PROTO_COVERAGE_OMIT
    assert "deepseek" in GENERATED_PROTO_COVERAGE_OMIT
    assert "v1" in GENERATED_PROTO_COVERAGE_OMIT
    runner = (ROOT / "scripts/run_rust_coverage.py").read_text(encoding="utf-8")
    assert runner.count('"--ignore-filename-regex"') == 2
    assert runner.count('"--locked"') >= 3
    assert '"coverageOmit": [GENERATED_PROTO_COVERAGE_OMIT]' in runner
    assert "cargo test --locked --manifest-path" in runner
