from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest

from scripts import native_codegen


ROOT = Path(__file__).resolve().parents[1]

EXPECTED_GO_BINDINGS = {
    "go/internal/protocol/actionv1/action.pb.go",
    "go/internal/protocol/actionv1/action_grpc.pb.go",
    "go/internal/protocol/agentv1/agent.pb.go",
    "go/internal/protocol/commonv1/common.pb.go",
    "go/internal/protocol/controlv1/control.pb.go",
    "go/internal/protocol/controlv1/control_grpc.pb.go",
    "go/internal/protocol/evidencev1/evidence.pb.go",
    "go/internal/protocol/federationv1/federation.pb.go",
    "go/internal/protocol/storagev1/storage.pb.go",
}


def _load_json(relative: str) -> dict[str, Any]:
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


def test_native_toolchain_pins_exact_generators_and_release_artifacts() -> None:
    toolchain = _load_json("release/native_runtime_toolchain_v1.json")

    assert toolchain["go"]["version"] == "1.27.1"
    protoc = toolchain["protoc"]
    assert protoc["version"] == "36.1"
    assert toolchain["go"]["artifacts"]["windows_amd64"]["sha256"] == ("a3911b5e0e1b1053f25ed0675f4c1c6aad1e2bfcf253df2b9be4caabd2edd95d")
    assert toolchain["go"]["artifacts"]["linux_amd64"]["sha256"] == ("63d339f0da5ab53635a56f2490a7984dfe12dfcff22ad749f63edaf590168445")
    assert protoc["artifacts"]["windows_amd64"]["sha256"] == ("390e515cb456e6a978553bdb57baf087b054885077fd6da7f7ff0160279c07d6")
    assert protoc["artifacts"]["linux_amd64"]["sha256"] == ("c4bc672d9d49214dc8cafdceadf4df92182d6ca8e3ec65a56b2d7de5602669b4")
    generators = toolchain["generators"]
    assert generators["protoc_gen_go"]["version"] == "1.36.11"
    assert generators["protoc_gen_go_grpc"]["version"] == "1.6.2"
    assert generators["prost"]["version"] == "0.13.5"
    assert generators["tonic_build"]["version"] == "0.12.3"
    assert generators["protox"]["version"] == "0.8.0"


def test_checked_in_go_bindings_cover_every_proto_and_service() -> None:
    manifest = _load_json("proto/generated/codegen-manifest.v1.json")
    manifest_outputs = {str(item["path"]) for item in manifest["outputs"]}

    assert EXPECTED_GO_BINDINGS <= manifest_outputs
    assert "proto/generated/descriptor.pb" in manifest_outputs
    for relative in EXPECTED_GO_BINDINGS:
        generated = (ROOT / relative).read_text(encoding="utf-8")
        if relative.endswith("_grpc.pb.go"):
            assert "Code generated by protoc-gen-go-grpc" in generated
            assert "protoc-gen-go-grpc v1.6.2" in generated
        else:
            assert "Code generated by protoc-gen-go" in generated
            assert "protoc-gen-go v1.36.11" in generated
        assert re.search(r"protoc\s+v7\.36\.1", generated)


def test_rust_protocol_compiles_generated_messages_and_services() -> None:
    cargo = (ROOT / "rust/crates/deepseek-protocol/Cargo.toml").read_text(encoding="utf-8")
    build = (ROOT / "rust/crates/deepseek-protocol/build.rs").read_text(encoding="utf-8")
    source = (ROOT / "rust/crates/deepseek-protocol/src/lib.rs").read_text(encoding="utf-8")

    assert "prost.workspace = true" in cargo
    assert "tonic.workspace = true" in cargo
    assert "protox.workspace = true" in cargo
    assert "tonic-build.workspace = true" in cargo
    assert "compile_fds" in build
    assert 'tonic::include_proto!("deepseek.common.v1")' in source
    assert 'tonic::include_proto!("deepseek.action.v1")' in source
    assert 'tonic::include_proto!("deepseek.control.v1")' in source


def test_codegen_rejects_spoofed_version_suffix(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    tool = tmp_path / "protoc"
    tool.write_bytes(b"placeholder")
    monkeypatch.setattr(native_codegen, "_run", lambda command: "totally-not-protoc libprotoc 36.1")

    with pytest.raises(native_codegen.CodegenError, match="TOOL_VERSION_MISMATCH"):
        native_codegen._require_version(tool, ["--version"], "libprotoc 36.1", "protoc")


@pytest.mark.parametrize(
    "reported",
    ("protoc-gen-go v1.36.11", "protoc-gen-go.exe v1.36.11"),
)
def test_codegen_accepts_only_canonical_cross_platform_generator_names(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    reported: str,
) -> None:
    tool = tmp_path / "protoc-gen-go.exe"
    tool.write_bytes(b"placeholder")
    monkeypatch.setattr(native_codegen, "_run", lambda command: reported)

    native_codegen._require_version(
        tool,
        ["--version"],
        ("protoc-gen-go v1.36.11", "protoc-gen-go.exe v1.36.11"),
        "protoc-gen-go",
    )
