// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: agent/v1/a2a.proto

package agentv1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Go owns task IDs, lifecycle, execution fencing, and durable artifact order.
// JSON fields contain existing A2A 0.3.0 wire documents (including extension
// fields); they are data, never a second RPC dispatch or an arbitrary store write.
type A2ASubmitRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ContextId   string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	MessageJson []byte                 `protobuf:"bytes,3,opt,name=message_json,json=messageJson,proto3" json:"message_json,omitempty"`
	// The edge proposes an idempotency identity with epoch ZERO (no authority).
	// Go alone installs epoch one atomically with the new task; caller-supplied
	// nonzero epochs are rejected. Retrying this identity cannot create another task.
	Fence         *commonv1.ActionFence `protobuf:"bytes,4,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2ASubmitRequest) Reset() {
	*x = A2ASubmitRequest{}
	mi := &file_agent_v1_a2a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2ASubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2ASubmitRequest) ProtoMessage() {}

func (x *A2ASubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_a2a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2ASubmitRequest.ProtoReflect.Descriptor instead.
func (*A2ASubmitRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_a2a_proto_rawDescGZIP(), []int{0}
}

func (x *A2ASubmitRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *A2ASubmitRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *A2ASubmitRequest) GetMessageJson() []byte {
	if x != nil {
		return x.MessageJson
	}
	return nil
}

func (x *A2ASubmitRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type A2ATaskRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2ATaskRef) Reset() {
	*x = A2ATaskRef{}
	mi := &file_agent_v1_a2a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2ATaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2ATaskRef) ProtoMessage() {}

func (x *A2ATaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_a2a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2ATaskRef.ProtoReflect.Descriptor instead.
func (*A2ATaskRef) Descriptor() ([]byte, []int) {
	return file_agent_v1_a2a_proto_rawDescGZIP(), []int{1}
}

func (x *A2ATaskRef) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type A2AExecutionRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Fence          *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	ExecutionToken string                 `protobuf:"bytes,2,opt,name=execution_token,json=executionToken,proto3" json:"execution_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *A2AExecutionRef) Reset() {
	*x = A2AExecutionRef{}
	mi := &file_agent_v1_a2a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2AExecutionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2AExecutionRef) ProtoMessage() {}

func (x *A2AExecutionRef) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_a2a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2AExecutionRef.ProtoReflect.Descriptor instead.
func (*A2AExecutionRef) Descriptor() ([]byte, []int) {
	return file_agent_v1_a2a_proto_rawDescGZIP(), []int{2}
}

func (x *A2AExecutionRef) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *A2AExecutionRef) GetExecutionToken() string {
	if x != nil {
		return x.ExecutionToken
	}
	return ""
}

type A2AFinishRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Fence          *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	ExecutionToken string                 `protobuf:"bytes,2,opt,name=execution_token,json=executionToken,proto3" json:"execution_token,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Failure        string                 `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *A2AFinishRequest) Reset() {
	*x = A2AFinishRequest{}
	mi := &file_agent_v1_a2a_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2AFinishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2AFinishRequest) ProtoMessage() {}

func (x *A2AFinishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_a2a_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2AFinishRequest.ProtoReflect.Descriptor instead.
func (*A2AFinishRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_a2a_proto_rawDescGZIP(), []int{3}
}

func (x *A2AFinishRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *A2AFinishRequest) GetExecutionToken() string {
	if x != nil {
		return x.ExecutionToken
	}
	return ""
}

func (x *A2AFinishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *A2AFinishRequest) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

// A read-only list filter carries no execution authority.
type A2AListFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2AListFilter) Reset() {
	*x = A2AListFilter{}
	mi := &file_agent_v1_a2a_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2AListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2AListFilter) ProtoMessage() {}

func (x *A2AListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_a2a_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2AListFilter.ProtoReflect.Descriptor instead.
func (*A2AListFilter) Descriptor() ([]byte, []int) {
	return file_agent_v1_a2a_proto_rawDescGZIP(), []int{4}
}

func (x *A2AListFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type A2ATaskSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State          string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Revision       uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	PublicTaskJson []byte                 `protobuf:"bytes,4,opt,name=public_task_json,json=publicTaskJson,proto3" json:"public_task_json,omitempty"`
	// Present only on Claim. Get/List/Cancel never expose execution credentials.
	Execution     *A2AExecutionRef      `protobuf:"bytes,5,opt,name=execution,proto3" json:"execution,omitempty"`
	Fence         *commonv1.ActionFence `protobuf:"bytes,6,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2ATaskSnapshot) Reset() {
	*x = A2ATaskSnapshot{}
	mi := &file_agent_v1_a2a_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2ATaskSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2ATaskSnapshot) ProtoMessage() {}

func (x *A2ATaskSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_a2a_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2ATaskSnapshot.ProtoReflect.Descriptor instead.
func (*A2ATaskSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_v1_a2a_proto_rawDescGZIP(), []int{5}
}

func (x *A2ATaskSnapshot) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *A2ATaskSnapshot) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *A2ATaskSnapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *A2ATaskSnapshot) GetPublicTaskJson() []byte {
	if x != nil {
		return x.PublicTaskJson
	}
	return nil
}

func (x *A2ATaskSnapshot) GetExecution() *A2AExecutionRef {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *A2ATaskSnapshot) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type A2ATaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*A2ATaskSnapshot     `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2ATaskList) Reset() {
	*x = A2ATaskList{}
	mi := &file_agent_v1_a2a_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2ATaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2ATaskList) ProtoMessage() {}

func (x *A2ATaskList) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_a2a_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2ATaskList.ProtoReflect.Descriptor instead.
func (*A2ATaskList) Descriptor() ([]byte, []int) {
	return file_agent_v1_a2a_proto_rawDescGZIP(), []int{6}
}

func (x *A2ATaskList) GetTasks() []*A2ATaskSnapshot {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_agent_v1_a2a_proto protoreflect.FileDescriptor

const file_agent_v1_a2a_proto_rawDesc = "" +
	"\n" +
	"\x12agent/v1/a2a.proto\x12\x11deepseek.agent.v1\x1a\x16common/v1/common.proto\"\xa6\x01\n" +
	"\x10A2ASubmitRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12!\n" +
	"\fmessage_json\x18\x03 \x01(\fR\vmessageJson\x125\n" +
	"\x05fence\x18\x04 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"%\n" +
	"\n" +
	"A2ATaskRef\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"q\n" +
	"\x0fA2AExecutionRef\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12'\n" +
	"\x0fexecution_token\x18\x02 \x01(\tR\x0eexecutionToken\"\xa6\x01\n" +
	"\x10A2AFinishRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12'\n" +
	"\x0fexecution_token\x18\x02 \x01(\tR\x0eexecutionToken\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\afailure\x18\x04 \x01(\tR\afailure\"%\n" +
	"\rA2AListFilter\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xff\x01\n" +
	"\x0fA2ATaskSnapshot\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12(\n" +
	"\x10public_task_json\x18\x04 \x01(\fR\x0epublicTaskJson\x12@\n" +
	"\texecution\x18\x05 \x01(\v2\".deepseek.agent.v1.A2AExecutionRefR\texecution\x125\n" +
	"\x05fence\x18\x06 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"G\n" +
	"\vA2ATaskList\x128\n" +
	"\x05tasks\x18\x01 \x03(\v2\".deepseek.agent.v1.A2ATaskSnapshotR\x05tasks2\xb4\x04\n" +
	"\x0eA2ATaskControl\x12Q\n" +
	"\x06Submit\x12#.deepseek.agent.v1.A2ASubmitRequest\x1a\".deepseek.agent.v1.A2ATaskSnapshot\x12H\n" +
	"\x03Get\x12\x1d.deepseek.agent.v1.A2ATaskRef\x1a\".deepseek.agent.v1.A2ATaskSnapshot\x12J\n" +
	"\x05Claim\x12\x1d.deepseek.agent.v1.A2ATaskRef\x1a\".deepseek.agent.v1.A2ATaskSnapshot\x12O\n" +
	"\x05Renew\x12\".deepseek.agent.v1.A2AExecutionRef\x1a\".deepseek.agent.v1.A2ATaskSnapshot\x12Q\n" +
	"\x06Finish\x12#.deepseek.agent.v1.A2AFinishRequest\x1a\".deepseek.agent.v1.A2ATaskSnapshot\x12K\n" +
	"\x06Cancel\x12\x1d.deepseek.agent.v1.A2ATaskRef\x1a\".deepseek.agent.v1.A2ATaskSnapshot\x12H\n" +
	"\x04List\x12 .deepseek.agent.v1.A2AListFilter\x1a\x1e.deepseek.agent.v1.A2ATaskListBFZDgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/agentv1;agentv1b\x06proto3"

var (
	file_agent_v1_a2a_proto_rawDescOnce sync.Once
	file_agent_v1_a2a_proto_rawDescData []byte
)

func file_agent_v1_a2a_proto_rawDescGZIP() []byte {
	file_agent_v1_a2a_proto_rawDescOnce.Do(func() {
		file_agent_v1_a2a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_a2a_proto_rawDesc), len(file_agent_v1_a2a_proto_rawDesc)))
	})
	return file_agent_v1_a2a_proto_rawDescData
}

var file_agent_v1_a2a_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_v1_a2a_proto_goTypes = []any{
	(*A2ASubmitRequest)(nil),     // 0: deepseek.agent.v1.A2ASubmitRequest
	(*A2ATaskRef)(nil),           // 1: deepseek.agent.v1.A2ATaskRef
	(*A2AExecutionRef)(nil),      // 2: deepseek.agent.v1.A2AExecutionRef
	(*A2AFinishRequest)(nil),     // 3: deepseek.agent.v1.A2AFinishRequest
	(*A2AListFilter)(nil),        // 4: deepseek.agent.v1.A2AListFilter
	(*A2ATaskSnapshot)(nil),      // 5: deepseek.agent.v1.A2ATaskSnapshot
	(*A2ATaskList)(nil),          // 6: deepseek.agent.v1.A2ATaskList
	(*commonv1.ActionFence)(nil), // 7: deepseek.common.v1.ActionFence
}
var file_agent_v1_a2a_proto_depIdxs = []int32{
	7,  // 0: deepseek.agent.v1.A2ASubmitRequest.fence:type_name -> deepseek.common.v1.ActionFence
	7,  // 1: deepseek.agent.v1.A2AExecutionRef.fence:type_name -> deepseek.common.v1.ActionFence
	7,  // 2: deepseek.agent.v1.A2AFinishRequest.fence:type_name -> deepseek.common.v1.ActionFence
	2,  // 3: deepseek.agent.v1.A2ATaskSnapshot.execution:type_name -> deepseek.agent.v1.A2AExecutionRef
	7,  // 4: deepseek.agent.v1.A2ATaskSnapshot.fence:type_name -> deepseek.common.v1.ActionFence
	5,  // 5: deepseek.agent.v1.A2ATaskList.tasks:type_name -> deepseek.agent.v1.A2ATaskSnapshot
	0,  // 6: deepseek.agent.v1.A2ATaskControl.Submit:input_type -> deepseek.agent.v1.A2ASubmitRequest
	1,  // 7: deepseek.agent.v1.A2ATaskControl.Get:input_type -> deepseek.agent.v1.A2ATaskRef
	1,  // 8: deepseek.agent.v1.A2ATaskControl.Claim:input_type -> deepseek.agent.v1.A2ATaskRef
	2,  // 9: deepseek.agent.v1.A2ATaskControl.Renew:input_type -> deepseek.agent.v1.A2AExecutionRef
	3,  // 10: deepseek.agent.v1.A2ATaskControl.Finish:input_type -> deepseek.agent.v1.A2AFinishRequest
	1,  // 11: deepseek.agent.v1.A2ATaskControl.Cancel:input_type -> deepseek.agent.v1.A2ATaskRef
	4,  // 12: deepseek.agent.v1.A2ATaskControl.List:input_type -> deepseek.agent.v1.A2AListFilter
	5,  // 13: deepseek.agent.v1.A2ATaskControl.Submit:output_type -> deepseek.agent.v1.A2ATaskSnapshot
	5,  // 14: deepseek.agent.v1.A2ATaskControl.Get:output_type -> deepseek.agent.v1.A2ATaskSnapshot
	5,  // 15: deepseek.agent.v1.A2ATaskControl.Claim:output_type -> deepseek.agent.v1.A2ATaskSnapshot
	5,  // 16: deepseek.agent.v1.A2ATaskControl.Renew:output_type -> deepseek.agent.v1.A2ATaskSnapshot
	5,  // 17: deepseek.agent.v1.A2ATaskControl.Finish:output_type -> deepseek.agent.v1.A2ATaskSnapshot
	5,  // 18: deepseek.agent.v1.A2ATaskControl.Cancel:output_type -> deepseek.agent.v1.A2ATaskSnapshot
	6,  // 19: deepseek.agent.v1.A2ATaskControl.List:output_type -> deepseek.agent.v1.A2ATaskList
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agent_v1_a2a_proto_init() }
func file_agent_v1_a2a_proto_init() {
	if File_agent_v1_a2a_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_a2a_proto_rawDesc), len(file_agent_v1_a2a_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_a2a_proto_goTypes,
		DependencyIndexes: file_agent_v1_a2a_proto_depIdxs,
		MessageInfos:      file_agent_v1_a2a_proto_msgTypes,
	}.Build()
	File_agent_v1_a2a_proto = out.File
	file_agent_v1_a2a_proto_goTypes = nil
	file_agent_v1_a2a_proto_depIdxs = nil
}
