// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: agent/v1/agent.proto

package agentv1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pure scheduling for the interactive chat path. This service does not create
// durable runs, authorize effects, or write a store. Durable task commands keep
// their ActionFence above. Both services share deepseekd's authenticated listener.
type AgentChatPhase int32

const (
	AgentChatPhase_AGENT_CHAT_PHASE_UNSPECIFIED AgentChatPhase = 0
	AgentChatPhase_AGENT_CHAT_PHASE_WORKERS     AgentChatPhase = 1
	AgentChatPhase_AGENT_CHAT_PHASE_REVISION    AgentChatPhase = 2
	AgentChatPhase_AGENT_CHAT_PHASE_SYNTHESIS   AgentChatPhase = 3
)

// Enum value maps for AgentChatPhase.
var (
	AgentChatPhase_name = map[int32]string{
		0: "AGENT_CHAT_PHASE_UNSPECIFIED",
		1: "AGENT_CHAT_PHASE_WORKERS",
		2: "AGENT_CHAT_PHASE_REVISION",
		3: "AGENT_CHAT_PHASE_SYNTHESIS",
	}
	AgentChatPhase_value = map[string]int32{
		"AGENT_CHAT_PHASE_UNSPECIFIED": 0,
		"AGENT_CHAT_PHASE_WORKERS":     1,
		"AGENT_CHAT_PHASE_REVISION":    2,
		"AGENT_CHAT_PHASE_SYNTHESIS":   3,
	}
)

func (x AgentChatPhase) Enum() *AgentChatPhase {
	p := new(AgentChatPhase)
	*p = x
	return p
}

func (x AgentChatPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentChatPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentChatPhase) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x AgentChatPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentChatPhase.Descriptor instead.
func (AgentChatPhase) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// Durable execution admission is separate from metadata append. A returned
// lease does not install a Rust epoch or prove a provider effect. A takeover's
// reconciliation_required flag prohibits another fresh dispatch.
type AgentRunExecutionPhase int32

const (
	AgentRunExecutionPhase_AGENT_RUN_EXECUTION_PHASE_UNSPECIFIED AgentRunExecutionPhase = 0
	AgentRunExecutionPhase_AGENT_RUN_EXECUTION_PHASE_PLAN        AgentRunExecutionPhase = 1
	AgentRunExecutionPhase_AGENT_RUN_EXECUTION_PHASE_TASKS       AgentRunExecutionPhase = 2
)

// Enum value maps for AgentRunExecutionPhase.
var (
	AgentRunExecutionPhase_name = map[int32]string{
		0: "AGENT_RUN_EXECUTION_PHASE_UNSPECIFIED",
		1: "AGENT_RUN_EXECUTION_PHASE_PLAN",
		2: "AGENT_RUN_EXECUTION_PHASE_TASKS",
	}
	AgentRunExecutionPhase_value = map[string]int32{
		"AGENT_RUN_EXECUTION_PHASE_UNSPECIFIED": 0,
		"AGENT_RUN_EXECUTION_PHASE_PLAN":        1,
		"AGENT_RUN_EXECUTION_PHASE_TASKS":       2,
	}
)

func (x AgentRunExecutionPhase) Enum() *AgentRunExecutionPhase {
	p := new(AgentRunExecutionPhase)
	*p = x
	return p
}

func (x AgentRunExecutionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRunExecutionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (AgentRunExecutionPhase) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[1]
}

func (x AgentRunExecutionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRunExecutionPhase.Descriptor instead.
func (AgentRunExecutionPhase) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type AgentTaskCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DependsOn     []string               `protobuf:"bytes,3,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTaskCommand) Reset() {
	*x = AgentTaskCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskCommand) ProtoMessage() {}

func (x *AgentTaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskCommand.ProtoReflect.Descriptor instead.
func (*AgentTaskCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentTaskCommand) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *AgentTaskCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentTaskCommand) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type AgentTaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	State         commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTaskResult) Reset() {
	*x = AgentTaskResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskResult) ProtoMessage() {}

func (x *AgentTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskResult.ProtoReflect.Descriptor instead.
func (*AgentTaskResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentTaskResult) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *AgentTaskResult) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *AgentTaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type AgentChatTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	DependsOn     []string               `protobuf:"bytes,3,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentChatTask) Reset() {
	*x = AgentChatTask{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentChatTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentChatTask) ProtoMessage() {}

func (x *AgentChatTask) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentChatTask.ProtoReflect.Descriptor instead.
func (*AgentChatTask) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentChatTask) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentChatTask) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *AgentChatTask) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *AgentChatTask) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type AgentChatOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Tokens        uint64                 `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Failed        bool                   `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Revision      bool                   `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentChatOutcome) Reset() {
	*x = AgentChatOutcome{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentChatOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentChatOutcome) ProtoMessage() {}

func (x *AgentChatOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentChatOutcome.ProtoReflect.Descriptor instead.
func (*AgentChatOutcome) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentChatOutcome) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentChatOutcome) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *AgentChatOutcome) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *AgentChatOutcome) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *AgentChatOutcome) GetRevision() bool {
	if x != nil {
		return x.Revision
	}
	return false
}

type AgentChatScheduleInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Candidates     []*AgentChatTask       `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Outcomes       []*AgentChatOutcome    `protobuf:"bytes,2,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	RevisionTarget string                 `protobuf:"bytes,3,opt,name=revision_target,json=revisionTarget,proto3" json:"revision_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentChatScheduleInput) Reset() {
	*x = AgentChatScheduleInput{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentChatScheduleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentChatScheduleInput) ProtoMessage() {}

func (x *AgentChatScheduleInput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentChatScheduleInput.ProtoReflect.Descriptor instead.
func (*AgentChatScheduleInput) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentChatScheduleInput) GetCandidates() []*AgentChatTask {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *AgentChatScheduleInput) GetOutcomes() []*AgentChatOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *AgentChatScheduleInput) GetRevisionTarget() string {
	if x != nil {
		return x.RevisionTarget
	}
	return ""
}

type AgentChatScheduleOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Plan            []*AgentChatTask       `protobuf:"bytes,1,rep,name=plan,proto3" json:"plan,omitempty"`
	Execute         []*AgentChatTask       `protobuf:"bytes,2,rep,name=execute,proto3" json:"execute,omitempty"`
	CompletedRoles  []string               `protobuf:"bytes,3,rep,name=completed_roles,json=completedRoles,proto3" json:"completed_roles,omitempty"`
	Phase           AgentChatPhase         `protobuf:"varint,4,opt,name=phase,proto3,enum=deepseek.agent.v1.AgentChatPhase" json:"phase,omitempty"`
	TokenLimit      uint64                 `protobuf:"varint,5,opt,name=token_limit,json=tokenLimit,proto3" json:"token_limit,omitempty"`
	UsedTokens      uint64                 `protobuf:"varint,6,opt,name=used_tokens,json=usedTokens,proto3" json:"used_tokens,omitempty"`
	TimeoutSeconds  uint64                 `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	BudgetExhausted bool                   `protobuf:"varint,8,opt,name=budget_exhausted,json=budgetExhausted,proto3" json:"budget_exhausted,omitempty"`
	Authoritative   bool                   `protobuf:"varint,9,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentChatScheduleOutput) Reset() {
	*x = AgentChatScheduleOutput{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentChatScheduleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentChatScheduleOutput) ProtoMessage() {}

func (x *AgentChatScheduleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentChatScheduleOutput.ProtoReflect.Descriptor instead.
func (*AgentChatScheduleOutput) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentChatScheduleOutput) GetPlan() []*AgentChatTask {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *AgentChatScheduleOutput) GetExecute() []*AgentChatTask {
	if x != nil {
		return x.Execute
	}
	return nil
}

func (x *AgentChatScheduleOutput) GetCompletedRoles() []string {
	if x != nil {
		return x.CompletedRoles
	}
	return nil
}

func (x *AgentChatScheduleOutput) GetPhase() AgentChatPhase {
	if x != nil {
		return x.Phase
	}
	return AgentChatPhase_AGENT_CHAT_PHASE_UNSPECIFIED
}

func (x *AgentChatScheduleOutput) GetTokenLimit() uint64 {
	if x != nil {
		return x.TokenLimit
	}
	return 0
}

func (x *AgentChatScheduleOutput) GetUsedTokens() uint64 {
	if x != nil {
		return x.UsedTokens
	}
	return 0
}

func (x *AgentChatScheduleOutput) GetTimeoutSeconds() uint64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AgentChatScheduleOutput) GetBudgetExhausted() bool {
	if x != nil {
		return x.BudgetExhausted
	}
	return false
}

func (x *AgentChatScheduleOutput) GetAuthoritative() bool {
	if x != nil {
		return x.Authoritative
	}
	return false
}

// These references identify immutable bytes owned by Rust. They are metadata,
// not effect proofs or execution grants.
type AgentArtifactReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentArtifactReference) Reset() {
	*x = AgentArtifactReference{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentArtifactReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentArtifactReference) ProtoMessage() {}

func (x *AgentArtifactReference) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentArtifactReference.ProtoReflect.Descriptor instead.
func (*AgentArtifactReference) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentArtifactReference) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *AgentArtifactReference) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type AgentRunPlanNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	DependsOn     []string               `protobuf:"bytes,3,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunPlanNode) Reset() {
	*x = AgentRunPlanNode{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunPlanNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunPlanNode) ProtoMessage() {}

func (x *AgentRunPlanNode) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunPlanNode.ProtoReflect.Descriptor instead.
func (*AgentRunPlanNode) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentRunPlanNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentRunPlanNode) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *AgentRunPlanNode) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type AgentRunEventMetadata struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Fence            *commonv1.ActionFence   `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	RunId            string                  `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Index            int64                   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	CreatedAt        string                  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type             string                  `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Phase            string                  `protobuf:"bytes,6,opt,name=phase,proto3" json:"phase,omitempty"`
	Status           string                  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Scope            string                  `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	Plan             []*AgentRunPlanNode     `protobuf:"bytes,9,rep,name=plan,proto3" json:"plan,omitempty"`
	HasPlan          bool                    `protobuf:"varint,10,opt,name=has_plan,json=hasPlan,proto3" json:"has_plan,omitempty"`
	Failed           bool                    `protobuf:"varint,11,opt,name=failed,proto3" json:"failed,omitempty"`
	DurationMs       *int64                  `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	PromptTokens     uint64                  `protobuf:"varint,13,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint64                  `protobuf:"varint,14,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Body             *AgentArtifactReference `protobuf:"bytes,15,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentRunEventMetadata) Reset() {
	*x = AgentRunEventMetadata{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunEventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunEventMetadata) ProtoMessage() {}

func (x *AgentRunEventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunEventMetadata.ProtoReflect.Descriptor instead.
func (*AgentRunEventMetadata) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentRunEventMetadata) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *AgentRunEventMetadata) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentRunEventMetadata) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AgentRunEventMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AgentRunEventMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentRunEventMetadata) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *AgentRunEventMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentRunEventMetadata) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AgentRunEventMetadata) GetPlan() []*AgentRunPlanNode {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *AgentRunEventMetadata) GetHasPlan() bool {
	if x != nil {
		return x.HasPlan
	}
	return false
}

func (x *AgentRunEventMetadata) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *AgentRunEventMetadata) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *AgentRunEventMetadata) GetPromptTokens() uint64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *AgentRunEventMetadata) GetCompletionTokens() uint64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *AgentRunEventMetadata) GetBody() *AgentArtifactReference {
	if x != nil {
		return x.Body
	}
	return nil
}

type AgentRunCreateMetadata struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Preset         string                  `protobuf:"bytes,1,opt,name=preset,proto3" json:"preset,omitempty"`
	ConfirmPlan    bool                    `protobuf:"varint,2,opt,name=confirm_plan,json=confirmPlan,proto3" json:"confirm_plan,omitempty"`
	ConversationId string                  `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                  `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Request        *AgentArtifactReference `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRunCreateMetadata) Reset() {
	*x = AgentRunCreateMetadata{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunCreateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunCreateMetadata) ProtoMessage() {}

func (x *AgentRunCreateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunCreateMetadata.ProtoReflect.Descriptor instead.
func (*AgentRunCreateMetadata) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentRunCreateMetadata) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *AgentRunCreateMetadata) GetConfirmPlan() bool {
	if x != nil {
		return x.ConfirmPlan
	}
	return false
}

func (x *AgentRunCreateMetadata) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentRunCreateMetadata) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentRunCreateMetadata) GetRequest() *AgentArtifactReference {
	if x != nil {
		return x.Request
	}
	return nil
}

type AgentRunNodeMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Attempts         uint64                 `protobuf:"varint,3,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LatencyMs        *int64                 `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3,oneof" json:"latency_ms,omitempty"`
	PromptTokens     uint64                 `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint64                 `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Failed           bool                   `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentRunNodeMetadata) Reset() {
	*x = AgentRunNodeMetadata{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunNodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunNodeMetadata) ProtoMessage() {}

func (x *AgentRunNodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunNodeMetadata.ProtoReflect.Descriptor instead.
func (*AgentRunNodeMetadata) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentRunNodeMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentRunNodeMetadata) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AgentRunNodeMetadata) GetAttempts() uint64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *AgentRunNodeMetadata) GetLatencyMs() int64 {
	if x != nil && x.LatencyMs != nil {
		return *x.LatencyMs
	}
	return 0
}

func (x *AgentRunNodeMetadata) GetPromptTokens() uint64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *AgentRunNodeMetadata) GetCompletionTokens() uint64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *AgentRunNodeMetadata) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type AgentRunSnapshot struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RunId          string                  `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status         string                  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NextIndex      int64                   `protobuf:"varint,3,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	Preset         string                  `protobuf:"bytes,4,opt,name=preset,proto3" json:"preset,omitempty"`
	ConfirmPlan    bool                    `protobuf:"varint,5,opt,name=confirm_plan,json=confirmPlan,proto3" json:"confirm_plan,omitempty"`
	ConversationId string                  `protobuf:"bytes,6,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                  `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Request        *AgentArtifactReference `protobuf:"bytes,8,opt,name=request,proto3" json:"request,omitempty"`
	Plan           []*AgentRunPlanNode     `protobuf:"bytes,9,rep,name=plan,proto3" json:"plan,omitempty"`
	Nodes          []*AgentRunNodeMetadata `protobuf:"bytes,10,rep,name=nodes,proto3" json:"nodes,omitempty"`
	FinalAfter     int64                   `protobuf:"varint,11,opt,name=final_after,json=finalAfter,proto3" json:"final_after,omitempty"`
	LastEvent      *AgentRunEventMetadata  `protobuf:"bytes,12,opt,name=last_event,json=lastEvent,proto3" json:"last_event,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRunSnapshot) Reset() {
	*x = AgentRunSnapshot{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunSnapshot) ProtoMessage() {}

func (x *AgentRunSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunSnapshot.ProtoReflect.Descriptor instead.
func (*AgentRunSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AgentRunSnapshot) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentRunSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentRunSnapshot) GetNextIndex() int64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *AgentRunSnapshot) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *AgentRunSnapshot) GetConfirmPlan() bool {
	if x != nil {
		return x.ConfirmPlan
	}
	return false
}

func (x *AgentRunSnapshot) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentRunSnapshot) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentRunSnapshot) GetRequest() *AgentArtifactReference {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AgentRunSnapshot) GetPlan() []*AgentRunPlanNode {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *AgentRunSnapshot) GetNodes() []*AgentRunNodeMetadata {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *AgentRunSnapshot) GetFinalAfter() int64 {
	if x != nil {
		return x.FinalAfter
	}
	return 0
}

func (x *AgentRunSnapshot) GetLastEvent() *AgentRunEventMetadata {
	if x != nil {
		return x.LastEvent
	}
	return nil
}

type AppendAgentRunEventRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SchemaVersion uint32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OperationId   string                  `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Actor         string                  `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	RunId         string                  `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExpectedIndex int64                   `protobuf:"varint,5,opt,name=expected_index,json=expectedIndex,proto3" json:"expected_index,omitempty"`
	Create        *AgentRunCreateMetadata `protobuf:"bytes,6,opt,name=create,proto3" json:"create,omitempty"`
	Event         *AgentRunEventMetadata  `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	// The current Go domain epoch, obtained from GetAuthority, must match inside
	// the write transaction. This is a metadata fence, not a worker effect grant.
	Fence         *commonv1.ActionFence `protobuf:"bytes,8,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendAgentRunEventRequest) Reset() {
	*x = AppendAgentRunEventRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendAgentRunEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendAgentRunEventRequest) ProtoMessage() {}

func (x *AppendAgentRunEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendAgentRunEventRequest.ProtoReflect.Descriptor instead.
func (*AppendAgentRunEventRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AppendAgentRunEventRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AppendAgentRunEventRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AppendAgentRunEventRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AppendAgentRunEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AppendAgentRunEventRequest) GetExpectedIndex() int64 {
	if x != nil {
		return x.ExpectedIndex
	}
	return 0
}

func (x *AppendAgentRunEventRequest) GetCreate() *AgentRunCreateMetadata {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *AppendAgentRunEventRequest) GetEvent() *AgentRunEventMetadata {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AppendAgentRunEventRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type AppendAgentRunEventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlreadyApplied bool                   `protobuf:"varint,1,opt,name=already_applied,json=alreadyApplied,proto3" json:"already_applied,omitempty"`
	Event          *AgentRunEventMetadata `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Run            *AgentRunSnapshot      `protobuf:"bytes,3,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendAgentRunEventResponse) Reset() {
	*x = AppendAgentRunEventResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendAgentRunEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendAgentRunEventResponse) ProtoMessage() {}

func (x *AppendAgentRunEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendAgentRunEventResponse.ProtoReflect.Descriptor instead.
func (*AppendAgentRunEventResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AppendAgentRunEventResponse) GetAlreadyApplied() bool {
	if x != nil {
		return x.AlreadyApplied
	}
	return false
}

func (x *AppendAgentRunEventResponse) GetEvent() *AgentRunEventMetadata {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AppendAgentRunEventResponse) GetRun() *AgentRunSnapshot {
	if x != nil {
		return x.Run
	}
	return nil
}

type GetAgentRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,2,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRunRequest) Reset() {
	*x = GetAgentRunRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRunRequest) ProtoMessage() {}

func (x *GetAgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRunRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRunRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GetAgentRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetAgentRunRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type GetAgentRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authoritative bool                   `protobuf:"varint,1,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	Run           *AgentRunSnapshot      `protobuf:"bytes,2,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRunResponse) Reset() {
	*x = GetAgentRunResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRunResponse) ProtoMessage() {}

func (x *GetAgentRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRunResponse.ProtoReflect.Descriptor instead.
func (*GetAgentRunResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetAgentRunResponse) GetAuthoritative() bool {
	if x != nil {
		return x.Authoritative
	}
	return false
}

func (x *GetAgentRunResponse) GetRun() *AgentRunSnapshot {
	if x != nil {
		return x.Run
	}
	return nil
}

type AgentRunEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	After         int64                  `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,4,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunEventsRequest) Reset() {
	*x = AgentRunEventsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunEventsRequest) ProtoMessage() {}

func (x *AgentRunEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunEventsRequest.ProtoReflect.Descriptor instead.
func (*AgentRunEventsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *AgentRunEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentRunEventsRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *AgentRunEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AgentRunEventsRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type AgentRunEventsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Authoritative bool                     `protobuf:"varint,1,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	Events        []*AgentRunEventMetadata `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunEventsResponse) Reset() {
	*x = AgentRunEventsResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunEventsResponse) ProtoMessage() {}

func (x *AgentRunEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunEventsResponse.ProtoReflect.Descriptor instead.
func (*AgentRunEventsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *AgentRunEventsResponse) GetAuthoritative() bool {
	if x != nil {
		return x.Authoritative
	}
	return false
}

func (x *AgentRunEventsResponse) GetEvents() []*AgentRunEventMetadata {
	if x != nil {
		return x.Events
	}
	return nil
}

// Read-only discovery of metadata authority. The epoch cannot authorize a
// provider effect or substitute for an action claim/lease.
type AgentRunAuthorityInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunAuthorityInput) Reset() {
	*x = AgentRunAuthorityInput{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunAuthorityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunAuthorityInput) ProtoMessage() {}

func (x *AgentRunAuthorityInput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunAuthorityInput.ProtoReflect.Descriptor instead.
func (*AgentRunAuthorityInput) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

type AgentRunAuthorityOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authoritative bool                   `protobuf:"varint,1,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	MetadataEpoch uint64                 `protobuf:"varint,2,opt,name=metadata_epoch,json=metadataEpoch,proto3" json:"metadata_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunAuthorityOutput) Reset() {
	*x = AgentRunAuthorityOutput{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunAuthorityOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunAuthorityOutput) ProtoMessage() {}

func (x *AgentRunAuthorityOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunAuthorityOutput.ProtoReflect.Descriptor instead.
func (*AgentRunAuthorityOutput) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *AgentRunAuthorityOutput) GetAuthoritative() bool {
	if x != nil {
		return x.Authoritative
	}
	return false
}

func (x *AgentRunAuthorityOutput) GetMetadataEpoch() uint64 {
	if x != nil {
		return x.MetadataEpoch
	}
	return 0
}

type AgentRunExecutionClaim struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Fence                  *commonv1.ActionFence   `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	RunId                  string                  `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Phase                  AgentRunExecutionPhase  `protobuf:"varint,3,opt,name=phase,proto3,enum=deepseek.agent.v1.AgentRunExecutionPhase" json:"phase,omitempty"`
	Request                *AgentArtifactReference `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	PlanDigest             string                  `protobuf:"bytes,5,opt,name=plan_digest,json=planDigest,proto3" json:"plan_digest,omitempty"`
	MetadataIndex          int64                   `protobuf:"varint,6,opt,name=metadata_index,json=metadataIndex,proto3" json:"metadata_index,omitempty"`
	MetadataEpoch          uint64                  `protobuf:"varint,7,opt,name=metadata_epoch,json=metadataEpoch,proto3" json:"metadata_epoch,omitempty"`
	Owner                  string                  `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	ClaimToken             string                  `protobuf:"bytes,9,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	LeaseUntil             int64                   `protobuf:"varint,10,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`
	ClaimRevision          int64                   `protobuf:"varint,11,opt,name=claim_revision,json=claimRevision,proto3" json:"claim_revision,omitempty"`
	WriterFencingToken     int64                   `protobuf:"varint,12,opt,name=writer_fencing_token,json=writerFencingToken,proto3" json:"writer_fencing_token,omitempty"`
	WriterLeaseUntil       int64                   `protobuf:"varint,13,opt,name=writer_lease_until,json=writerLeaseUntil,proto3" json:"writer_lease_until,omitempty"`
	State                  string                  `protobuf:"bytes,14,opt,name=state,proto3" json:"state,omitempty"`
	ReconciliationRequired bool                    `protobuf:"varint,15,opt,name=reconciliation_required,json=reconciliationRequired,proto3" json:"reconciliation_required,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentRunExecutionClaim) Reset() {
	*x = AgentRunExecutionClaim{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunExecutionClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunExecutionClaim) ProtoMessage() {}

func (x *AgentRunExecutionClaim) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunExecutionClaim.ProtoReflect.Descriptor instead.
func (*AgentRunExecutionClaim) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *AgentRunExecutionClaim) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *AgentRunExecutionClaim) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentRunExecutionClaim) GetPhase() AgentRunExecutionPhase {
	if x != nil {
		return x.Phase
	}
	return AgentRunExecutionPhase_AGENT_RUN_EXECUTION_PHASE_UNSPECIFIED
}

func (x *AgentRunExecutionClaim) GetRequest() *AgentArtifactReference {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AgentRunExecutionClaim) GetPlanDigest() string {
	if x != nil {
		return x.PlanDigest
	}
	return ""
}

func (x *AgentRunExecutionClaim) GetMetadataIndex() int64 {
	if x != nil {
		return x.MetadataIndex
	}
	return 0
}

func (x *AgentRunExecutionClaim) GetMetadataEpoch() uint64 {
	if x != nil {
		return x.MetadataEpoch
	}
	return 0
}

func (x *AgentRunExecutionClaim) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AgentRunExecutionClaim) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

func (x *AgentRunExecutionClaim) GetLeaseUntil() int64 {
	if x != nil {
		return x.LeaseUntil
	}
	return 0
}

func (x *AgentRunExecutionClaim) GetClaimRevision() int64 {
	if x != nil {
		return x.ClaimRevision
	}
	return 0
}

func (x *AgentRunExecutionClaim) GetWriterFencingToken() int64 {
	if x != nil {
		return x.WriterFencingToken
	}
	return 0
}

func (x *AgentRunExecutionClaim) GetWriterLeaseUntil() int64 {
	if x != nil {
		return x.WriterLeaseUntil
	}
	return 0
}

func (x *AgentRunExecutionClaim) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AgentRunExecutionClaim) GetReconciliationRequired() bool {
	if x != nil {
		return x.ReconciliationRequired
	}
	return false
}

type ClaimAgentRunExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	RunId         string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Phase         AgentRunExecutionPhase `protobuf:"varint,5,opt,name=phase,proto3,enum=deepseek.agent.v1.AgentRunExecutionPhase" json:"phase,omitempty"`
	ExpectedIndex int64                  `protobuf:"varint,6,opt,name=expected_index,json=expectedIndex,proto3" json:"expected_index,omitempty"`
	MetadataFence *commonv1.ActionFence  `protobuf:"bytes,7,opt,name=metadata_fence,json=metadataFence,proto3" json:"metadata_fence,omitempty"`
	Owner         string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	LeaseSeconds  uint32                 `protobuf:"varint,9,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimAgentRunExecutionRequest) Reset() {
	*x = ClaimAgentRunExecutionRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAgentRunExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAgentRunExecutionRequest) ProtoMessage() {}

func (x *ClaimAgentRunExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAgentRunExecutionRequest.ProtoReflect.Descriptor instead.
func (*ClaimAgentRunExecutionRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ClaimAgentRunExecutionRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ClaimAgentRunExecutionRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ClaimAgentRunExecutionRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ClaimAgentRunExecutionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ClaimAgentRunExecutionRequest) GetPhase() AgentRunExecutionPhase {
	if x != nil {
		return x.Phase
	}
	return AgentRunExecutionPhase_AGENT_RUN_EXECUTION_PHASE_UNSPECIFIED
}

func (x *ClaimAgentRunExecutionRequest) GetExpectedIndex() int64 {
	if x != nil {
		return x.ExpectedIndex
	}
	return 0
}

func (x *ClaimAgentRunExecutionRequest) GetMetadataFence() *commonv1.ActionFence {
	if x != nil {
		return x.MetadataFence
	}
	return nil
}

func (x *ClaimAgentRunExecutionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ClaimAgentRunExecutionRequest) GetLeaseSeconds() uint32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

type ClaimAgentRunExecutionResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	AlreadyApplied bool                    `protobuf:"varint,1,opt,name=already_applied,json=alreadyApplied,proto3" json:"already_applied,omitempty"`
	Claim          *AgentRunExecutionClaim `protobuf:"bytes,2,opt,name=claim,proto3" json:"claim,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimAgentRunExecutionResponse) Reset() {
	*x = ClaimAgentRunExecutionResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAgentRunExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAgentRunExecutionResponse) ProtoMessage() {}

func (x *ClaimAgentRunExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAgentRunExecutionResponse.ProtoReflect.Descriptor instead.
func (*ClaimAgentRunExecutionResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ClaimAgentRunExecutionResponse) GetAlreadyApplied() bool {
	if x != nil {
		return x.AlreadyApplied
	}
	return false
}

func (x *ClaimAgentRunExecutionResponse) GetClaim() *AgentRunExecutionClaim {
	if x != nil {
		return x.Claim
	}
	return nil
}

type RenewAgentRunExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	ClaimToken    string                 `protobuf:"bytes,4,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	LeaseSeconds  uint32                 `protobuf:"varint,5,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewAgentRunExecutionRequest) Reset() {
	*x = RenewAgentRunExecutionRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAgentRunExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAgentRunExecutionRequest) ProtoMessage() {}

func (x *RenewAgentRunExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAgentRunExecutionRequest.ProtoReflect.Descriptor instead.
func (*RenewAgentRunExecutionRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *RenewAgentRunExecutionRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *RenewAgentRunExecutionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RenewAgentRunExecutionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RenewAgentRunExecutionRequest) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

func (x *RenewAgentRunExecutionRequest) GetLeaseSeconds() uint32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

type RenewAgentRunExecutionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Claim         *AgentRunExecutionClaim `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewAgentRunExecutionResponse) Reset() {
	*x = RenewAgentRunExecutionResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAgentRunExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAgentRunExecutionResponse) ProtoMessage() {}

func (x *RenewAgentRunExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAgentRunExecutionResponse.ProtoReflect.Descriptor instead.
func (*RenewAgentRunExecutionResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *RenewAgentRunExecutionResponse) GetClaim() *AgentRunExecutionClaim {
	if x != nil {
		return x.Claim
	}
	return nil
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x11deepseek.agent.v1\x1a\x16common/v1/common.proto\"\x81\x01\n" +
	"\x10AgentTaskCommand\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\tR\tdependsOn\"\x98\x01\n" +
	"\x0fAgentTaskResult\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"p\n" +
	"\rAgentChatTask\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\tR\tdependsOn\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\"\x90\x01\n" +
	"\x10AgentChatOutcome\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x04R\x06tokens\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\bR\x06failed\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\bR\brevision\"\xc4\x01\n" +
	"\x16AgentChatScheduleInput\x12@\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2 .deepseek.agent.v1.AgentChatTaskR\n" +
	"candidates\x12?\n" +
	"\boutcomes\x18\x02 \x03(\v2#.deepseek.agent.v1.AgentChatOutcomeR\boutcomes\x12'\n" +
	"\x0frevision_target\x18\x03 \x01(\tR\x0erevisionTarget\"\xa9\x03\n" +
	"\x17AgentChatScheduleOutput\x124\n" +
	"\x04plan\x18\x01 \x03(\v2 .deepseek.agent.v1.AgentChatTaskR\x04plan\x12:\n" +
	"\aexecute\x18\x02 \x03(\v2 .deepseek.agent.v1.AgentChatTaskR\aexecute\x12'\n" +
	"\x0fcompleted_roles\x18\x03 \x03(\tR\x0ecompletedRoles\x127\n" +
	"\x05phase\x18\x04 \x01(\x0e2!.deepseek.agent.v1.AgentChatPhaseR\x05phase\x12\x1f\n" +
	"\vtoken_limit\x18\x05 \x01(\x04R\n" +
	"tokenLimit\x12\x1f\n" +
	"\vused_tokens\x18\x06 \x01(\x04R\n" +
	"usedTokens\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x04R\x0etimeoutSeconds\x12)\n" +
	"\x10budget_exhausted\x18\b \x01(\bR\x0fbudgetExhausted\x12$\n" +
	"\rauthoritative\x18\t \x01(\bR\rauthoritative\"H\n" +
	"\x16AgentArtifactReference\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\"U\n" +
	"\x10AgentRunPlanNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\tR\tdependsOn\"\xa5\x04\n" +
	"\x15AgentRunEventMetadata\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x03R\x05index\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05scope\x18\b \x01(\tR\x05scope\x127\n" +
	"\x04plan\x18\t \x03(\v2#.deepseek.agent.v1.AgentRunPlanNodeR\x04plan\x12\x19\n" +
	"\bhas_plan\x18\n" +
	" \x01(\bR\ahasPlan\x12\x16\n" +
	"\x06failed\x18\v \x01(\bR\x06failed\x12$\n" +
	"\vduration_ms\x18\f \x01(\x03H\x00R\n" +
	"durationMs\x88\x01\x01\x12#\n" +
	"\rprompt_tokens\x18\r \x01(\x04R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x0e \x01(\x04R\x10completionTokens\x12=\n" +
	"\x04body\x18\x0f \x01(\v2).deepseek.agent.v1.AgentArtifactReferenceR\x04bodyB\x0e\n" +
	"\f_duration_ms\"\xe0\x01\n" +
	"\x16AgentRunCreateMetadata\x12\x16\n" +
	"\x06preset\x18\x01 \x01(\tR\x06preset\x12!\n" +
	"\fconfirm_plan\x18\x02 \x01(\bR\vconfirmPlan\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12C\n" +
	"\arequest\x18\x05 \x01(\v2).deepseek.agent.v1.AgentArtifactReferenceR\arequest\"\xf5\x01\n" +
	"\x14AgentRunNodeMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\battempts\x18\x03 \x01(\x04R\battempts\x12\"\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03H\x00R\tlatencyMs\x88\x01\x01\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x04R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x04R\x10completionTokens\x12\x16\n" +
	"\x06failed\x18\a \x01(\bR\x06failedB\r\n" +
	"\v_latency_ms\"\x8a\x04\n" +
	"\x10AgentRunSnapshot\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"next_index\x18\x03 \x01(\x03R\tnextIndex\x12\x16\n" +
	"\x06preset\x18\x04 \x01(\tR\x06preset\x12!\n" +
	"\fconfirm_plan\x18\x05 \x01(\bR\vconfirmPlan\x12'\n" +
	"\x0fconversation_id\x18\x06 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\x12C\n" +
	"\arequest\x18\b \x01(\v2).deepseek.agent.v1.AgentArtifactReferenceR\arequest\x127\n" +
	"\x04plan\x18\t \x03(\v2#.deepseek.agent.v1.AgentRunPlanNodeR\x04plan\x12=\n" +
	"\x05nodes\x18\n" +
	" \x03(\v2'.deepseek.agent.v1.AgentRunNodeMetadataR\x05nodes\x12\x1f\n" +
	"\vfinal_after\x18\v \x01(\x03R\n" +
	"finalAfter\x12G\n" +
	"\n" +
	"last_event\x18\f \x01(\v2(.deepseek.agent.v1.AgentRunEventMetadataR\tlastEvent\"\xf4\x02\n" +
	"\x1aAppendAgentRunEventRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12%\n" +
	"\x0eexpected_index\x18\x05 \x01(\x03R\rexpectedIndex\x12A\n" +
	"\x06create\x18\x06 \x01(\v2).deepseek.agent.v1.AgentRunCreateMetadataR\x06create\x12>\n" +
	"\x05event\x18\a \x01(\v2(.deepseek.agent.v1.AgentRunEventMetadataR\x05event\x125\n" +
	"\x05fence\x18\b \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"\xbd\x01\n" +
	"\x1bAppendAgentRunEventResponse\x12'\n" +
	"\x0falready_applied\x18\x01 \x01(\bR\x0ealreadyApplied\x12>\n" +
	"\x05event\x18\x02 \x01(\v2(.deepseek.agent.v1.AgentRunEventMetadataR\x05event\x125\n" +
	"\x03run\x18\x03 \x01(\v2#.deepseek.agent.v1.AgentRunSnapshotR\x03run\"b\n" +
	"\x12GetAgentRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x125\n" +
	"\x05fence\x18\x02 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"r\n" +
	"\x13GetAgentRunResponse\x12$\n" +
	"\rauthoritative\x18\x01 \x01(\bR\rauthoritative\x125\n" +
	"\x03run\x18\x02 \x01(\v2#.deepseek.agent.v1.AgentRunSnapshotR\x03run\"\x91\x01\n" +
	"\x15AgentRunEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x125\n" +
	"\x05fence\x18\x04 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"\x80\x01\n" +
	"\x16AgentRunEventsResponse\x12$\n" +
	"\rauthoritative\x18\x01 \x01(\bR\rauthoritative\x12@\n" +
	"\x06events\x18\x02 \x03(\v2(.deepseek.agent.v1.AgentRunEventMetadataR\x06events\"\x18\n" +
	"\x16AgentRunAuthorityInput\"f\n" +
	"\x17AgentRunAuthorityOutput\x12$\n" +
	"\rauthoritative\x18\x01 \x01(\bR\rauthoritative\x12%\n" +
	"\x0emetadata_epoch\x18\x02 \x01(\x04R\rmetadataEpoch\"\x89\x05\n" +
	"\x16AgentRunExecutionClaim\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12?\n" +
	"\x05phase\x18\x03 \x01(\x0e2).deepseek.agent.v1.AgentRunExecutionPhaseR\x05phase\x12C\n" +
	"\arequest\x18\x04 \x01(\v2).deepseek.agent.v1.AgentArtifactReferenceR\arequest\x12\x1f\n" +
	"\vplan_digest\x18\x05 \x01(\tR\n" +
	"planDigest\x12%\n" +
	"\x0emetadata_index\x18\x06 \x01(\x03R\rmetadataIndex\x12%\n" +
	"\x0emetadata_epoch\x18\a \x01(\x04R\rmetadataEpoch\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x1f\n" +
	"\vclaim_token\x18\t \x01(\tR\n" +
	"claimToken\x12\x1f\n" +
	"\vlease_until\x18\n" +
	" \x01(\x03R\n" +
	"leaseUntil\x12%\n" +
	"\x0eclaim_revision\x18\v \x01(\x03R\rclaimRevision\x120\n" +
	"\x14writer_fencing_token\x18\f \x01(\x03R\x12writerFencingToken\x12,\n" +
	"\x12writer_lease_until\x18\r \x01(\x03R\x10writerLeaseUntil\x12\x14\n" +
	"\x05state\x18\x0e \x01(\tR\x05state\x127\n" +
	"\x17reconciliation_required\x18\x0f \x01(\bR\x16reconciliationRequired\"\x81\x03\n" +
	"\x1dClaimAgentRunExecutionRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12?\n" +
	"\x05phase\x18\x05 \x01(\x0e2).deepseek.agent.v1.AgentRunExecutionPhaseR\x05phase\x12%\n" +
	"\x0eexpected_index\x18\x06 \x01(\x03R\rexpectedIndex\x12F\n" +
	"\x0emetadata_fence\x18\a \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\rmetadataFence\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12#\n" +
	"\rlease_seconds\x18\t \x01(\rR\fleaseSeconds\"\x8a\x01\n" +
	"\x1eClaimAgentRunExecutionResponse\x12'\n" +
	"\x0falready_applied\x18\x01 \x01(\bR\x0ealreadyApplied\x12?\n" +
	"\x05claim\x18\x02 \x01(\v2).deepseek.agent.v1.AgentRunExecutionClaimR\x05claim\"\xc9\x01\n" +
	"\x1dRenewAgentRunExecutionRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1f\n" +
	"\vclaim_token\x18\x04 \x01(\tR\n" +
	"claimToken\x12#\n" +
	"\rlease_seconds\x18\x05 \x01(\rR\fleaseSeconds\"a\n" +
	"\x1eRenewAgentRunExecutionResponse\x12?\n" +
	"\x05claim\x18\x01 \x01(\v2).deepseek.agent.v1.AgentRunExecutionClaimR\x05claim*\x8f\x01\n" +
	"\x0eAgentChatPhase\x12 \n" +
	"\x1cAGENT_CHAT_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AGENT_CHAT_PHASE_WORKERS\x10\x01\x12\x1d\n" +
	"\x19AGENT_CHAT_PHASE_REVISION\x10\x02\x12\x1e\n" +
	"\x1aAGENT_CHAT_PHASE_SYNTHESIS\x10\x03*\x8c\x01\n" +
	"\x16AgentRunExecutionPhase\x12)\n" +
	"%AGENT_RUN_EXECUTION_PHASE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eAGENT_RUN_EXECUTION_PHASE_PLAN\x10\x01\x12#\n" +
	"\x1fAGENT_RUN_EXECUTION_PHASE_TASKS\x10\x022w\n" +
	"\x12AgentChatScheduler\x12a\n" +
	"\bEvaluate\x12).deepseek.agent.v1.AgentChatScheduleInput\x1a*.deepseek.agent.v1.AgentChatScheduleOutput2\x91\x05\n" +
	"\x0fAgentRunControl\x12e\n" +
	"\fGetAuthority\x12).deepseek.agent.v1.AgentRunAuthorityInput\x1a*.deepseek.agent.v1.AgentRunAuthorityOutput\x12l\n" +
	"\vAppendEvent\x12-.deepseek.agent.v1.AppendAgentRunEventRequest\x1a..deepseek.agent.v1.AppendAgentRunEventResponse\x12W\n" +
	"\x06GetRun\x12%.deepseek.agent.v1.GetAgentRunRequest\x1a&.deepseek.agent.v1.GetAgentRunResponse\x12b\n" +
	"\vEventsAfter\x12(.deepseek.agent.v1.AgentRunEventsRequest\x1a).deepseek.agent.v1.AgentRunEventsResponse\x12u\n" +
	"\x0eClaimExecution\x120.deepseek.agent.v1.ClaimAgentRunExecutionRequest\x1a1.deepseek.agent.v1.ClaimAgentRunExecutionResponse\x12u\n" +
	"\x0eRenewExecution\x120.deepseek.agent.v1.RenewAgentRunExecutionRequest\x1a1.deepseek.agent.v1.RenewAgentRunExecutionResponseBFZDgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/agentv1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_agent_v1_agent_proto_goTypes = []any{
	(AgentChatPhase)(0),                    // 0: deepseek.agent.v1.AgentChatPhase
	(AgentRunExecutionPhase)(0),            // 1: deepseek.agent.v1.AgentRunExecutionPhase
	(*AgentTaskCommand)(nil),               // 2: deepseek.agent.v1.AgentTaskCommand
	(*AgentTaskResult)(nil),                // 3: deepseek.agent.v1.AgentTaskResult
	(*AgentChatTask)(nil),                  // 4: deepseek.agent.v1.AgentChatTask
	(*AgentChatOutcome)(nil),               // 5: deepseek.agent.v1.AgentChatOutcome
	(*AgentChatScheduleInput)(nil),         // 6: deepseek.agent.v1.AgentChatScheduleInput
	(*AgentChatScheduleOutput)(nil),        // 7: deepseek.agent.v1.AgentChatScheduleOutput
	(*AgentArtifactReference)(nil),         // 8: deepseek.agent.v1.AgentArtifactReference
	(*AgentRunPlanNode)(nil),               // 9: deepseek.agent.v1.AgentRunPlanNode
	(*AgentRunEventMetadata)(nil),          // 10: deepseek.agent.v1.AgentRunEventMetadata
	(*AgentRunCreateMetadata)(nil),         // 11: deepseek.agent.v1.AgentRunCreateMetadata
	(*AgentRunNodeMetadata)(nil),           // 12: deepseek.agent.v1.AgentRunNodeMetadata
	(*AgentRunSnapshot)(nil),               // 13: deepseek.agent.v1.AgentRunSnapshot
	(*AppendAgentRunEventRequest)(nil),     // 14: deepseek.agent.v1.AppendAgentRunEventRequest
	(*AppendAgentRunEventResponse)(nil),    // 15: deepseek.agent.v1.AppendAgentRunEventResponse
	(*GetAgentRunRequest)(nil),             // 16: deepseek.agent.v1.GetAgentRunRequest
	(*GetAgentRunResponse)(nil),            // 17: deepseek.agent.v1.GetAgentRunResponse
	(*AgentRunEventsRequest)(nil),          // 18: deepseek.agent.v1.AgentRunEventsRequest
	(*AgentRunEventsResponse)(nil),         // 19: deepseek.agent.v1.AgentRunEventsResponse
	(*AgentRunAuthorityInput)(nil),         // 20: deepseek.agent.v1.AgentRunAuthorityInput
	(*AgentRunAuthorityOutput)(nil),        // 21: deepseek.agent.v1.AgentRunAuthorityOutput
	(*AgentRunExecutionClaim)(nil),         // 22: deepseek.agent.v1.AgentRunExecutionClaim
	(*ClaimAgentRunExecutionRequest)(nil),  // 23: deepseek.agent.v1.ClaimAgentRunExecutionRequest
	(*ClaimAgentRunExecutionResponse)(nil), // 24: deepseek.agent.v1.ClaimAgentRunExecutionResponse
	(*RenewAgentRunExecutionRequest)(nil),  // 25: deepseek.agent.v1.RenewAgentRunExecutionRequest
	(*RenewAgentRunExecutionResponse)(nil), // 26: deepseek.agent.v1.RenewAgentRunExecutionResponse
	(*commonv1.ActionFence)(nil),           // 27: deepseek.common.v1.ActionFence
	(commonv1.EffectState)(0),              // 28: deepseek.common.v1.EffectState
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	27, // 0: deepseek.agent.v1.AgentTaskCommand.fence:type_name -> deepseek.common.v1.ActionFence
	27, // 1: deepseek.agent.v1.AgentTaskResult.fence:type_name -> deepseek.common.v1.ActionFence
	28, // 2: deepseek.agent.v1.AgentTaskResult.state:type_name -> deepseek.common.v1.EffectState
	4,  // 3: deepseek.agent.v1.AgentChatScheduleInput.candidates:type_name -> deepseek.agent.v1.AgentChatTask
	5,  // 4: deepseek.agent.v1.AgentChatScheduleInput.outcomes:type_name -> deepseek.agent.v1.AgentChatOutcome
	4,  // 5: deepseek.agent.v1.AgentChatScheduleOutput.plan:type_name -> deepseek.agent.v1.AgentChatTask
	4,  // 6: deepseek.agent.v1.AgentChatScheduleOutput.execute:type_name -> deepseek.agent.v1.AgentChatTask
	0,  // 7: deepseek.agent.v1.AgentChatScheduleOutput.phase:type_name -> deepseek.agent.v1.AgentChatPhase
	27, // 8: deepseek.agent.v1.AgentRunEventMetadata.fence:type_name -> deepseek.common.v1.ActionFence
	9,  // 9: deepseek.agent.v1.AgentRunEventMetadata.plan:type_name -> deepseek.agent.v1.AgentRunPlanNode
	8,  // 10: deepseek.agent.v1.AgentRunEventMetadata.body:type_name -> deepseek.agent.v1.AgentArtifactReference
	8,  // 11: deepseek.agent.v1.AgentRunCreateMetadata.request:type_name -> deepseek.agent.v1.AgentArtifactReference
	8,  // 12: deepseek.agent.v1.AgentRunSnapshot.request:type_name -> deepseek.agent.v1.AgentArtifactReference
	9,  // 13: deepseek.agent.v1.AgentRunSnapshot.plan:type_name -> deepseek.agent.v1.AgentRunPlanNode
	12, // 14: deepseek.agent.v1.AgentRunSnapshot.nodes:type_name -> deepseek.agent.v1.AgentRunNodeMetadata
	10, // 15: deepseek.agent.v1.AgentRunSnapshot.last_event:type_name -> deepseek.agent.v1.AgentRunEventMetadata
	11, // 16: deepseek.agent.v1.AppendAgentRunEventRequest.create:type_name -> deepseek.agent.v1.AgentRunCreateMetadata
	10, // 17: deepseek.agent.v1.AppendAgentRunEventRequest.event:type_name -> deepseek.agent.v1.AgentRunEventMetadata
	27, // 18: deepseek.agent.v1.AppendAgentRunEventRequest.fence:type_name -> deepseek.common.v1.ActionFence
	10, // 19: deepseek.agent.v1.AppendAgentRunEventResponse.event:type_name -> deepseek.agent.v1.AgentRunEventMetadata
	13, // 20: deepseek.agent.v1.AppendAgentRunEventResponse.run:type_name -> deepseek.agent.v1.AgentRunSnapshot
	27, // 21: deepseek.agent.v1.GetAgentRunRequest.fence:type_name -> deepseek.common.v1.ActionFence
	13, // 22: deepseek.agent.v1.GetAgentRunResponse.run:type_name -> deepseek.agent.v1.AgentRunSnapshot
	27, // 23: deepseek.agent.v1.AgentRunEventsRequest.fence:type_name -> deepseek.common.v1.ActionFence
	10, // 24: deepseek.agent.v1.AgentRunEventsResponse.events:type_name -> deepseek.agent.v1.AgentRunEventMetadata
	27, // 25: deepseek.agent.v1.AgentRunExecutionClaim.fence:type_name -> deepseek.common.v1.ActionFence
	1,  // 26: deepseek.agent.v1.AgentRunExecutionClaim.phase:type_name -> deepseek.agent.v1.AgentRunExecutionPhase
	8,  // 27: deepseek.agent.v1.AgentRunExecutionClaim.request:type_name -> deepseek.agent.v1.AgentArtifactReference
	1,  // 28: deepseek.agent.v1.ClaimAgentRunExecutionRequest.phase:type_name -> deepseek.agent.v1.AgentRunExecutionPhase
	27, // 29: deepseek.agent.v1.ClaimAgentRunExecutionRequest.metadata_fence:type_name -> deepseek.common.v1.ActionFence
	22, // 30: deepseek.agent.v1.ClaimAgentRunExecutionResponse.claim:type_name -> deepseek.agent.v1.AgentRunExecutionClaim
	27, // 31: deepseek.agent.v1.RenewAgentRunExecutionRequest.fence:type_name -> deepseek.common.v1.ActionFence
	22, // 32: deepseek.agent.v1.RenewAgentRunExecutionResponse.claim:type_name -> deepseek.agent.v1.AgentRunExecutionClaim
	6,  // 33: deepseek.agent.v1.AgentChatScheduler.Evaluate:input_type -> deepseek.agent.v1.AgentChatScheduleInput
	20, // 34: deepseek.agent.v1.AgentRunControl.GetAuthority:input_type -> deepseek.agent.v1.AgentRunAuthorityInput
	14, // 35: deepseek.agent.v1.AgentRunControl.AppendEvent:input_type -> deepseek.agent.v1.AppendAgentRunEventRequest
	16, // 36: deepseek.agent.v1.AgentRunControl.GetRun:input_type -> deepseek.agent.v1.GetAgentRunRequest
	18, // 37: deepseek.agent.v1.AgentRunControl.EventsAfter:input_type -> deepseek.agent.v1.AgentRunEventsRequest
	23, // 38: deepseek.agent.v1.AgentRunControl.ClaimExecution:input_type -> deepseek.agent.v1.ClaimAgentRunExecutionRequest
	25, // 39: deepseek.agent.v1.AgentRunControl.RenewExecution:input_type -> deepseek.agent.v1.RenewAgentRunExecutionRequest
	7,  // 40: deepseek.agent.v1.AgentChatScheduler.Evaluate:output_type -> deepseek.agent.v1.AgentChatScheduleOutput
	21, // 41: deepseek.agent.v1.AgentRunControl.GetAuthority:output_type -> deepseek.agent.v1.AgentRunAuthorityOutput
	15, // 42: deepseek.agent.v1.AgentRunControl.AppendEvent:output_type -> deepseek.agent.v1.AppendAgentRunEventResponse
	17, // 43: deepseek.agent.v1.AgentRunControl.GetRun:output_type -> deepseek.agent.v1.GetAgentRunResponse
	19, // 44: deepseek.agent.v1.AgentRunControl.EventsAfter:output_type -> deepseek.agent.v1.AgentRunEventsResponse
	24, // 45: deepseek.agent.v1.AgentRunControl.ClaimExecution:output_type -> deepseek.agent.v1.ClaimAgentRunExecutionResponse
	26, // 46: deepseek.agent.v1.AgentRunControl.RenewExecution:output_type -> deepseek.agent.v1.RenewAgentRunExecutionResponse
	40, // [40:47] is the sub-list for method output_type
	33, // [33:40] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[8].OneofWrappers = []any{}
	file_agent_v1_agent_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
