// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChatScheduler_Evaluate_FullMethodName = "/deepseek.agent.v1.AgentChatScheduler/Evaluate"
)

// AgentChatSchedulerClient is the client API for AgentChatScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentChatSchedulerClient interface {
	Evaluate(ctx context.Context, in *AgentChatScheduleInput, opts ...grpc.CallOption) (*AgentChatScheduleOutput, error)
}

type agentChatSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChatSchedulerClient(cc grpc.ClientConnInterface) AgentChatSchedulerClient {
	return &agentChatSchedulerClient{cc}
}

func (c *agentChatSchedulerClient) Evaluate(ctx context.Context, in *AgentChatScheduleInput, opts ...grpc.CallOption) (*AgentChatScheduleOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentChatScheduleOutput)
	err := c.cc.Invoke(ctx, AgentChatScheduler_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentChatSchedulerServer is the server API for AgentChatScheduler service.
// All implementations must embed UnimplementedAgentChatSchedulerServer
// for forward compatibility.
type AgentChatSchedulerServer interface {
	Evaluate(context.Context, *AgentChatScheduleInput) (*AgentChatScheduleOutput, error)
	mustEmbedUnimplementedAgentChatSchedulerServer()
}

// UnimplementedAgentChatSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChatSchedulerServer struct{}

func (UnimplementedAgentChatSchedulerServer) Evaluate(context.Context, *AgentChatScheduleInput) (*AgentChatScheduleOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedAgentChatSchedulerServer) mustEmbedUnimplementedAgentChatSchedulerServer() {}
func (UnimplementedAgentChatSchedulerServer) testEmbeddedByValue()                            {}

// UnsafeAgentChatSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChatSchedulerServer will
// result in compilation errors.
type UnsafeAgentChatSchedulerServer interface {
	mustEmbedUnimplementedAgentChatSchedulerServer()
}

func RegisterAgentChatSchedulerServer(s grpc.ServiceRegistrar, srv AgentChatSchedulerServer) {
	// If the following call panics, it indicates UnimplementedAgentChatSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChatScheduler_ServiceDesc, srv)
}

func _AgentChatScheduler_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentChatScheduleInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentChatSchedulerServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentChatScheduler_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentChatSchedulerServer).Evaluate(ctx, req.(*AgentChatScheduleInput))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentChatScheduler_ServiceDesc is the grpc.ServiceDesc for AgentChatScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChatScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepseek.agent.v1.AgentChatScheduler",
	HandlerType: (*AgentChatSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _AgentChatScheduler_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}

const (
	AgentRunControl_GetAuthority_FullMethodName   = "/deepseek.agent.v1.AgentRunControl/GetAuthority"
	AgentRunControl_AppendEvent_FullMethodName    = "/deepseek.agent.v1.AgentRunControl/AppendEvent"
	AgentRunControl_GetRun_FullMethodName         = "/deepseek.agent.v1.AgentRunControl/GetRun"
	AgentRunControl_EventsAfter_FullMethodName    = "/deepseek.agent.v1.AgentRunControl/EventsAfter"
	AgentRunControl_ClaimExecution_FullMethodName = "/deepseek.agent.v1.AgentRunControl/ClaimExecution"
	AgentRunControl_RenewExecution_FullMethodName = "/deepseek.agent.v1.AgentRunControl/RenewExecution"
)

// AgentRunControlClient is the client API for AgentRunControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Authenticated Go control metadata only. Rust retains event/request bodies;
// fenced worker execution and effect reconciliation are separate commands.
type AgentRunControlClient interface {
	GetAuthority(ctx context.Context, in *AgentRunAuthorityInput, opts ...grpc.CallOption) (*AgentRunAuthorityOutput, error)
	AppendEvent(ctx context.Context, in *AppendAgentRunEventRequest, opts ...grpc.CallOption) (*AppendAgentRunEventResponse, error)
	GetRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*GetAgentRunResponse, error)
	EventsAfter(ctx context.Context, in *AgentRunEventsRequest, opts ...grpc.CallOption) (*AgentRunEventsResponse, error)
	ClaimExecution(ctx context.Context, in *ClaimAgentRunExecutionRequest, opts ...grpc.CallOption) (*ClaimAgentRunExecutionResponse, error)
	RenewExecution(ctx context.Context, in *RenewAgentRunExecutionRequest, opts ...grpc.CallOption) (*RenewAgentRunExecutionResponse, error)
}

type agentRunControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRunControlClient(cc grpc.ClientConnInterface) AgentRunControlClient {
	return &agentRunControlClient{cc}
}

func (c *agentRunControlClient) GetAuthority(ctx context.Context, in *AgentRunAuthorityInput, opts ...grpc.CallOption) (*AgentRunAuthorityOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRunAuthorityOutput)
	err := c.cc.Invoke(ctx, AgentRunControl_GetAuthority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunControlClient) AppendEvent(ctx context.Context, in *AppendAgentRunEventRequest, opts ...grpc.CallOption) (*AppendAgentRunEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendAgentRunEventResponse)
	err := c.cc.Invoke(ctx, AgentRunControl_AppendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunControlClient) GetRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*GetAgentRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentRunResponse)
	err := c.cc.Invoke(ctx, AgentRunControl_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunControlClient) EventsAfter(ctx context.Context, in *AgentRunEventsRequest, opts ...grpc.CallOption) (*AgentRunEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRunEventsResponse)
	err := c.cc.Invoke(ctx, AgentRunControl_EventsAfter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunControlClient) ClaimExecution(ctx context.Context, in *ClaimAgentRunExecutionRequest, opts ...grpc.CallOption) (*ClaimAgentRunExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimAgentRunExecutionResponse)
	err := c.cc.Invoke(ctx, AgentRunControl_ClaimExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunControlClient) RenewExecution(ctx context.Context, in *RenewAgentRunExecutionRequest, opts ...grpc.CallOption) (*RenewAgentRunExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewAgentRunExecutionResponse)
	err := c.cc.Invoke(ctx, AgentRunControl_RenewExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRunControlServer is the server API for AgentRunControl service.
// All implementations must embed UnimplementedAgentRunControlServer
// for forward compatibility.
//
// Authenticated Go control metadata only. Rust retains event/request bodies;
// fenced worker execution and effect reconciliation are separate commands.
type AgentRunControlServer interface {
	GetAuthority(context.Context, *AgentRunAuthorityInput) (*AgentRunAuthorityOutput, error)
	AppendEvent(context.Context, *AppendAgentRunEventRequest) (*AppendAgentRunEventResponse, error)
	GetRun(context.Context, *GetAgentRunRequest) (*GetAgentRunResponse, error)
	EventsAfter(context.Context, *AgentRunEventsRequest) (*AgentRunEventsResponse, error)
	ClaimExecution(context.Context, *ClaimAgentRunExecutionRequest) (*ClaimAgentRunExecutionResponse, error)
	RenewExecution(context.Context, *RenewAgentRunExecutionRequest) (*RenewAgentRunExecutionResponse, error)
	mustEmbedUnimplementedAgentRunControlServer()
}

// UnimplementedAgentRunControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRunControlServer struct{}

func (UnimplementedAgentRunControlServer) GetAuthority(context.Context, *AgentRunAuthorityInput) (*AgentRunAuthorityOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthority not implemented")
}
func (UnimplementedAgentRunControlServer) AppendEvent(context.Context, *AppendAgentRunEventRequest) (*AppendAgentRunEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEvent not implemented")
}
func (UnimplementedAgentRunControlServer) GetRun(context.Context, *GetAgentRunRequest) (*GetAgentRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedAgentRunControlServer) EventsAfter(context.Context, *AgentRunEventsRequest) (*AgentRunEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EventsAfter not implemented")
}
func (UnimplementedAgentRunControlServer) ClaimExecution(context.Context, *ClaimAgentRunExecutionRequest) (*ClaimAgentRunExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimExecution not implemented")
}
func (UnimplementedAgentRunControlServer) RenewExecution(context.Context, *RenewAgentRunExecutionRequest) (*RenewAgentRunExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewExecution not implemented")
}
func (UnimplementedAgentRunControlServer) mustEmbedUnimplementedAgentRunControlServer() {}
func (UnimplementedAgentRunControlServer) testEmbeddedByValue()                         {}

// UnsafeAgentRunControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRunControlServer will
// result in compilation errors.
type UnsafeAgentRunControlServer interface {
	mustEmbedUnimplementedAgentRunControlServer()
}

func RegisterAgentRunControlServer(s grpc.ServiceRegistrar, srv AgentRunControlServer) {
	// If the following call panics, it indicates UnimplementedAgentRunControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRunControl_ServiceDesc, srv)
}

func _AgentRunControl_GetAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRunAuthorityInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunControlServer).GetAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunControl_GetAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunControlServer).GetAuthority(ctx, req.(*AgentRunAuthorityInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunControl_AppendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendAgentRunEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunControlServer).AppendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunControl_AppendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunControlServer).AppendEvent(ctx, req.(*AppendAgentRunEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunControl_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunControlServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunControl_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunControlServer).GetRun(ctx, req.(*GetAgentRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunControl_EventsAfter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRunEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunControlServer).EventsAfter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunControl_EventsAfter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunControlServer).EventsAfter(ctx, req.(*AgentRunEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunControl_ClaimExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimAgentRunExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunControlServer).ClaimExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunControl_ClaimExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunControlServer).ClaimExecution(ctx, req.(*ClaimAgentRunExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunControl_RenewExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewAgentRunExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunControlServer).RenewExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunControl_RenewExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunControlServer).RenewExecution(ctx, req.(*RenewAgentRunExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRunControl_ServiceDesc is the grpc.ServiceDesc for AgentRunControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRunControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepseek.agent.v1.AgentRunControl",
	HandlerType: (*AgentRunControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthority",
			Handler:    _AgentRunControl_GetAuthority_Handler,
		},
		{
			MethodName: "AppendEvent",
			Handler:    _AgentRunControl_AppendEvent_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _AgentRunControl_GetRun_Handler,
		},
		{
			MethodName: "EventsAfter",
			Handler:    _AgentRunControl_EventsAfter_Handler,
		},
		{
			MethodName: "ClaimExecution",
			Handler:    _AgentRunControl_ClaimExecution_Handler,
		},
		{
			MethodName: "RenewExecution",
			Handler:    _AgentRunControl_RenewExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}
