// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: control/v1/control.proto

package controlv1

import (
	_ "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeMode int32

const (
	RuntimeMode_RUNTIME_MODE_UNSPECIFIED     RuntimeMode = 0
	RuntimeMode_RUNTIME_MODE_SHADOW_READONLY RuntimeMode = 1
	RuntimeMode_RUNTIME_MODE_AUTHORITATIVE   RuntimeMode = 2
)

// Enum value maps for RuntimeMode.
var (
	RuntimeMode_name = map[int32]string{
		0: "RUNTIME_MODE_UNSPECIFIED",
		1: "RUNTIME_MODE_SHADOW_READONLY",
		2: "RUNTIME_MODE_AUTHORITATIVE",
	}
	RuntimeMode_value = map[string]int32{
		"RUNTIME_MODE_UNSPECIFIED":     0,
		"RUNTIME_MODE_SHADOW_READONLY": 1,
		"RUNTIME_MODE_AUTHORITATIVE":   2,
	}
)

func (x RuntimeMode) Enum() *RuntimeMode {
	p := new(RuntimeMode)
	*p = x
	return p
}

func (x RuntimeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (RuntimeMode) Type() protoreflect.EnumType {
	return &file_control_v1_control_proto_enumTypes[0]
}

func (x RuntimeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeMode.Descriptor instead.
func (RuntimeMode) EnumDescriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ok                bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Mode              RuntimeMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=deepseek.control.v1.RuntimeMode" json:"mode,omitempty"`
	MutationAuthority string                 `protobuf:"bytes,3,opt,name=mutation_authority,json=mutationAuthority,proto3" json:"mutation_authority,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetMode() RuntimeMode {
	if x != nil {
		return x.Mode
	}
	return RuntimeMode_RUNTIME_MODE_UNSPECIFIED
}

func (x *HealthResponse) GetMutationAuthority() string {
	if x != nil {
		return x.MutationAuthority
	}
	return ""
}

type ShadowEvaluateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Domain         string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	CanonicalInput []byte                 `protobuf:"bytes,2,opt,name=canonical_input,json=canonicalInput,proto3" json:"canonical_input,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShadowEvaluateRequest) Reset() {
	*x = ShadowEvaluateRequest{}
	mi := &file_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowEvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowEvaluateRequest) ProtoMessage() {}

func (x *ShadowEvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowEvaluateRequest.ProtoReflect.Descriptor instead.
func (*ShadowEvaluateRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ShadowEvaluateRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ShadowEvaluateRequest) GetCanonicalInput() []byte {
	if x != nil {
		return x.CanonicalInput
	}
	return nil
}

type ShadowEvaluateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DecisionDigest string                 `protobuf:"bytes,1,opt,name=decision_digest,json=decisionDigest,proto3" json:"decision_digest,omitempty"`
	MutationDenied bool                   `protobuf:"varint,2,opt,name=mutation_denied,json=mutationDenied,proto3" json:"mutation_denied,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShadowEvaluateResponse) Reset() {
	*x = ShadowEvaluateResponse{}
	mi := &file_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowEvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowEvaluateResponse) ProtoMessage() {}

func (x *ShadowEvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowEvaluateResponse.ProtoReflect.Descriptor instead.
func (*ShadowEvaluateResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ShadowEvaluateResponse) GetDecisionDigest() string {
	if x != nil {
		return x.DecisionDigest
	}
	return ""
}

func (x *ShadowEvaluateResponse) GetMutationDenied() bool {
	if x != nil {
		return x.MutationDenied
	}
	return false
}

var File_control_v1_control_proto protoreflect.FileDescriptor

const file_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18control/v1/control.proto\x12\x13deepseek.control.v1\x1a\x16common/v1/common.proto\"\x0f\n" +
	"\rHealthRequest\"\x85\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x124\n" +
	"\x04mode\x18\x02 \x01(\x0e2 .deepseek.control.v1.RuntimeModeR\x04mode\x12-\n" +
	"\x12mutation_authority\x18\x03 \x01(\tR\x11mutationAuthority\"X\n" +
	"\x15ShadowEvaluateRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12'\n" +
	"\x0fcanonical_input\x18\x02 \x01(\fR\x0ecanonicalInput\"j\n" +
	"\x16ShadowEvaluateResponse\x12'\n" +
	"\x0fdecision_digest\x18\x01 \x01(\tR\x0edecisionDigest\x12'\n" +
	"\x0fmutation_denied\x18\x02 \x01(\bR\x0emutationDenied*m\n" +
	"\vRuntimeMode\x12\x1c\n" +
	"\x18RUNTIME_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cRUNTIME_MODE_SHADOW_READONLY\x10\x01\x12\x1e\n" +
	"\x1aRUNTIME_MODE_AUTHORITATIVE\x10\x022\xcc\x01\n" +
	"\fControlPlane\x12Q\n" +
	"\x06Health\x12\".deepseek.control.v1.HealthRequest\x1a#.deepseek.control.v1.HealthResponse\x12i\n" +
	"\x0eShadowEvaluate\x12*.deepseek.control.v1.ShadowEvaluateRequest\x1a+.deepseek.control.v1.ShadowEvaluateResponseBJZHgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/controlv1;controlv1b\x06proto3"

var (
	file_control_v1_control_proto_rawDescOnce sync.Once
	file_control_v1_control_proto_rawDescData []byte
)

func file_control_v1_control_proto_rawDescGZIP() []byte {
	file_control_v1_control_proto_rawDescOnce.Do(func() {
		file_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)))
	})
	return file_control_v1_control_proto_rawDescData
}

var file_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_control_v1_control_proto_goTypes = []any{
	(RuntimeMode)(0),               // 0: deepseek.control.v1.RuntimeMode
	(*HealthRequest)(nil),          // 1: deepseek.control.v1.HealthRequest
	(*HealthResponse)(nil),         // 2: deepseek.control.v1.HealthResponse
	(*ShadowEvaluateRequest)(nil),  // 3: deepseek.control.v1.ShadowEvaluateRequest
	(*ShadowEvaluateResponse)(nil), // 4: deepseek.control.v1.ShadowEvaluateResponse
}
var file_control_v1_control_proto_depIdxs = []int32{
	0, // 0: deepseek.control.v1.HealthResponse.mode:type_name -> deepseek.control.v1.RuntimeMode
	1, // 1: deepseek.control.v1.ControlPlane.Health:input_type -> deepseek.control.v1.HealthRequest
	3, // 2: deepseek.control.v1.ControlPlane.ShadowEvaluate:input_type -> deepseek.control.v1.ShadowEvaluateRequest
	2, // 3: deepseek.control.v1.ControlPlane.Health:output_type -> deepseek.control.v1.HealthResponse
	4, // 4: deepseek.control.v1.ControlPlane.ShadowEvaluate:output_type -> deepseek.control.v1.ShadowEvaluateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_v1_control_proto_init() }
func file_control_v1_control_proto_init() {
	if File_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_v1_control_proto_goTypes,
		DependencyIndexes: file_control_v1_control_proto_depIdxs,
		EnumInfos:         file_control_v1_control_proto_enumTypes,
		MessageInfos:      file_control_v1_control_proto_msgTypes,
	}.Build()
	File_control_v1_control_proto = out.File
	file_control_v1_control_proto_goTypes = nil
	file_control_v1_control_proto_depIdxs = nil
}
