"""Native OpenAI-chat composition parity probe, Python side.

The native route's composition is `openai_to_internal_payload` -> `preflight_deepseek_payload`
-> `prepare_memory_state` -> `build_deepseek_request`, which is what
`call_deepseek` (`deepseek_client.py:1486`) -> `prepare_deepseek_call` (`:651`) runs for
`POST /v1/chat/completions`. `openai_facade_parity_probe.py` pins the first step alone;
this probe pins the **composition**, because the two can each be right and still compose
wrongly -- the memory state sits between them and the order is load-bearing.

Two facts the composition measurement turned up, and pins here:

- `forced_search_mode` is **structurally unreachable** on this route: `search_mode` is
  `payload.get("searchMode") or "auto"` and the facade never forwards `searchMode`, so
  the prefetch branch is dead. Nothing is guarded for it;
- `web_search` is **absent** from the assembled tool list, because `tools_for_payload`
  adds it only when `search_tool_enabled(payload)` sees `searchEnabled is True`, another
  field the facade does not forward.

The expander, the clock and the downgrade decision are stubbed exactly as
`request_assembly_parity_probe.py` stubs them, so the comparison covers the composition
rather than the environment. `DEEPSEEK_API_KEY` is pinned to the same value the Rust side
passes as `api_key_fallback`, so validation is deterministic on both sides.

Usage::

    python tasks/native-runtime/native_chat_composition_parity_probe.py > python.json
    cd rust && cargo run -p deepseek-gateway --example native_chat_composition_parity_probe > ../rust.json
    diff <(tr -d '\\r' < python.json) <(tr -d '\\r' < rust.json)
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]

# Pinned before the config module is imported, so `preflight_deepseek_payload`'s fallback
# is the same string the Rust probe passes as `api_key_fallback`.
os.environ["DEEPSEEK_API_KEY"] = "probe-key"
os.environ["DEEPSEEK_INFRA_ROOT"] = os.environ.get("DEEPSEEK_INFRA_ROOT", str(REPO))

sys.path.insert(0, str(REPO))

from deepseek_infra.core.errors import AppError  # noqa: E402
from deepseek_infra.infra.gateway import budget_manager as bm  # noqa: E402
from deepseek_infra.infra.gateway import deepseek_client as dc  # noqa: E402
from deepseek_infra.infra.gateway import openai_api  # noqa: E402

BASE_URL = "http://127.0.0.1:8000"
EXPANDED = "[expanded]"  # the injected expander's anchor
# The injected clock, generated by the oracle's own formatter at a fixed instant — the
# same constants `request_assembly_parity_probe.py` uses, so the Rust side (a `LocalNow`
# with epoch 1_789_696_800, offset 28_800, name "CST") produces the same text.
CLOCK = dc.format_current_time_context(
    now=datetime(2026, 9, 18, 10, 0, 0, tzinfo=timezone(timedelta(hours=8), "CST"))
)
MEMORY_STATE: dict[str, Any] = {"enabled": False}

TURNS: list[dict[str, Any]] = [{"role": "user", "content": "你好"}]

CASES: list[tuple[str, Any]] = [
    ("minimal", {"model": "deepseek-v4-pro", "messages": TURNS}),
    ("alias-model", {"model": "fast", "messages": TURNS}),
    ("temperature", {"messages": TURNS, "temperature": 0.25}),
    ("multi-turn", {
        "model": "deepseek-v4-pro",
        "messages": [
            {"role": "system", "content": "你是助手"},
            {"role": "user", "content": "第一问"},
            {"role": "assistant", "content": "第一答"},
            {"role": "user", "content": "第二问"},
        ],
    }),
    ("blank-content-turn", {
        "messages": [
            {"role": "user", "content": "   "},
            {"role": "user", "content": "真正的问题"},
        ]
    }),
    ("tool-turn", {
        "messages": [
            {"role": "user", "content": "问题"},
            {"role": "assistant", "content": "", "tool_calls": [
                {"id": "call-1", "type": "function",
                 "function": {"name": "generate_chart", "arguments": "{}"}}
            ]},
            {"role": "tool", "tool_call_id": "call-1", "content": "结果"},
        ]
    }),
    ("client-tools-dropped", {
        "model": "deepseek-v4-pro",
        "messages": TURNS,
        "tools": [{"type": "function", "function": {"name": "client_tool", "parameters": {}}}],
        "tool_choice": "auto",
    }),
    ("search-fields-dropped", {
        "messages": TURNS,
        "searchEnabled": True,
        "searchMode": "force",
        "allowedTools": ["generate_chart"],
    }),
    ("system-prompt", {"messages": TURNS, "systemPrompt": "系统提示"}),
    ("context-summary", {"messages": TURNS, "contextSummary": "早前摘要"}),
    ("too-many-turns", {"messages": [{"role": "user", "content": f"t{i}"} for i in range(41)]}),
    ("refused-non-object", []),
    ("refused-no-messages", {"model": "deepseek-v4-pro"}),
    ("refused-empty-messages", {"messages": []}),
]


def view(case: Any) -> dict[str, Any]:
    try:
        payload = openai_api.openai_to_internal_payload(case, local_base_url=BASE_URL)
        validated = dc.preflight_deepseek_payload(payload)
        prepared = dc.build_deepseek_request(
            payload,
            stream=False,
            memory_state=dict(MEMORY_STATE),
            validated=validated,
        )
    except AppError as exc:
        return {"error": str(exc), "code": exc.code.value, "status": exc.status}
    return {
        "api_key": prepared.api_key,
        "body": json.dumps(prepared.body, ensure_ascii=False, separators=(", ", ": ")),
        "diagnostics": json.dumps(prepared.diagnostics, ensure_ascii=False, separators=(",", ":")),
        "tool_names": sorted(
            str(tool.get("function", {}).get("name") or "")
            for tool in (prepared.body.get("tools") or [])
        ),
    }


def main() -> int:
    reconfigure = getattr(sys.stdout, "reconfigure", None)
    if callable(reconfigure):
        reconfigure(encoding="utf-8")

    saved = (dc.expanded_message_content, dc.format_current_time_context, bm.should_downgrade)
    dc.expanded_message_content = lambda message: EXPANDED
    dc.format_current_time_context = lambda now=None: CLOCK
    bm.should_downgrade = lambda scope, policy, day=None: False
    out: dict[str, Any] = {"probe::base-url": BASE_URL}
    try:
        for label, case in CASES:
            out[f"case::{label}"] = view(case)
    finally:
        dc.expanded_message_content, dc.format_current_time_context, bm.should_downgrade = saved

    json.dump(out, sys.stdout, ensure_ascii=False, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
