// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: action/v1/action.proto

package actionv1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandKind int32

const (
	CommandKind_COMMAND_KIND_UNSPECIFIED                CommandKind = 0
	CommandKind_COMMAND_KIND_EXECUTE_BACKUP             CommandKind = 1
	CommandKind_COMMAND_KIND_EXECUTE_RESTORE            CommandKind = 2
	CommandKind_COMMAND_KIND_EXECUTE_REPAIR             CommandKind = 3
	CommandKind_COMMAND_KIND_EXECUTE_REBALANCE          CommandKind = 4
	CommandKind_COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER CommandKind = 5
	CommandKind_COMMAND_KIND_SIGN_READINESS             CommandKind = 6
)

// Enum value maps for CommandKind.
var (
	CommandKind_name = map[int32]string{
		0: "COMMAND_KIND_UNSPECIFIED",
		1: "COMMAND_KIND_EXECUTE_BACKUP",
		2: "COMMAND_KIND_EXECUTE_RESTORE",
		3: "COMMAND_KIND_EXECUTE_REPAIR",
		4: "COMMAND_KIND_EXECUTE_REBALANCE",
		5: "COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER",
		6: "COMMAND_KIND_SIGN_READINESS",
	}
	CommandKind_value = map[string]int32{
		"COMMAND_KIND_UNSPECIFIED":                0,
		"COMMAND_KIND_EXECUTE_BACKUP":             1,
		"COMMAND_KIND_EXECUTE_RESTORE":            2,
		"COMMAND_KIND_EXECUTE_REPAIR":             3,
		"COMMAND_KIND_EXECUTE_REBALANCE":          4,
		"COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER": 5,
		"COMMAND_KIND_SIGN_READINESS":             6,
	}
)

func (x CommandKind) Enum() *CommandKind {
	p := new(CommandKind)
	*p = x
	return p
}

func (x CommandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_proto_enumTypes[0].Descriptor()
}

func (CommandKind) Type() protoreflect.EnumType {
	return &file_action_v1_action_proto_enumTypes[0]
}

func (x CommandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandKind.Descriptor instead.
func (CommandKind) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{0}
}

type AdmitStatus int32

const (
	AdmitStatus_ADMIT_STATUS_UNSPECIFIED AdmitStatus = 0
	AdmitStatus_ADMIT_STATUS_ADMITTED    AdmitStatus = 1
	AdmitStatus_ADMIT_STATUS_REJECTED    AdmitStatus = 2
)

// Enum value maps for AdmitStatus.
var (
	AdmitStatus_name = map[int32]string{
		0: "ADMIT_STATUS_UNSPECIFIED",
		1: "ADMIT_STATUS_ADMITTED",
		2: "ADMIT_STATUS_REJECTED",
	}
	AdmitStatus_value = map[string]int32{
		"ADMIT_STATUS_UNSPECIFIED": 0,
		"ADMIT_STATUS_ADMITTED":    1,
		"ADMIT_STATUS_REJECTED":    2,
	}
)

func (x AdmitStatus) Enum() *AdmitStatus {
	p := new(AdmitStatus)
	*p = x
	return p
}

func (x AdmitStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdmitStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_proto_enumTypes[1].Descriptor()
}

func (AdmitStatus) Type() protoreflect.EnumType {
	return &file_action_v1_action_proto_enumTypes[1]
}

func (x AdmitStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdmitStatus.Descriptor instead.
func (AdmitStatus) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{1}
}

type StorageMutationStatus int32

const (
	StorageMutationStatus_STORAGE_MUTATION_STATUS_UNSPECIFIED    StorageMutationStatus = 0
	StorageMutationStatus_STORAGE_MUTATION_STATUS_CONFIRMED      StorageMutationStatus = 1
	StorageMutationStatus_STORAGE_MUTATION_STATUS_EFFECT_UNKNOWN StorageMutationStatus = 2
	StorageMutationStatus_STORAGE_MUTATION_STATUS_RECONCILING    StorageMutationStatus = 3
	StorageMutationStatus_STORAGE_MUTATION_STATUS_REJECTED       StorageMutationStatus = 4
	StorageMutationStatus_STORAGE_MUTATION_STATUS_FAILED         StorageMutationStatus = 5
)

// Enum value maps for StorageMutationStatus.
var (
	StorageMutationStatus_name = map[int32]string{
		0: "STORAGE_MUTATION_STATUS_UNSPECIFIED",
		1: "STORAGE_MUTATION_STATUS_CONFIRMED",
		2: "STORAGE_MUTATION_STATUS_EFFECT_UNKNOWN",
		3: "STORAGE_MUTATION_STATUS_RECONCILING",
		4: "STORAGE_MUTATION_STATUS_REJECTED",
		5: "STORAGE_MUTATION_STATUS_FAILED",
	}
	StorageMutationStatus_value = map[string]int32{
		"STORAGE_MUTATION_STATUS_UNSPECIFIED":    0,
		"STORAGE_MUTATION_STATUS_CONFIRMED":      1,
		"STORAGE_MUTATION_STATUS_EFFECT_UNKNOWN": 2,
		"STORAGE_MUTATION_STATUS_RECONCILING":    3,
		"STORAGE_MUTATION_STATUS_REJECTED":       4,
		"STORAGE_MUTATION_STATUS_FAILED":         5,
	}
)

func (x StorageMutationStatus) Enum() *StorageMutationStatus {
	p := new(StorageMutationStatus)
	*p = x
	return p
}

func (x StorageMutationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageMutationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_proto_enumTypes[2].Descriptor()
}

func (StorageMutationStatus) Type() protoreflect.EnumType {
	return &file_action_v1_action_proto_enumTypes[2]
}

func (x StorageMutationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageMutationStatus.Descriptor instead.
func (StorageMutationStatus) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{2}
}

type StorageConditionType int32

const (
	StorageConditionType_STORAGE_CONDITION_TYPE_UNSPECIFIED StorageConditionType = 0
	StorageConditionType_STORAGE_CONDITION_TYPE_CREATE_ONLY StorageConditionType = 1
	StorageConditionType_STORAGE_CONDITION_TYPE_IF_MATCH    StorageConditionType = 2
)

// Enum value maps for StorageConditionType.
var (
	StorageConditionType_name = map[int32]string{
		0: "STORAGE_CONDITION_TYPE_UNSPECIFIED",
		1: "STORAGE_CONDITION_TYPE_CREATE_ONLY",
		2: "STORAGE_CONDITION_TYPE_IF_MATCH",
	}
	StorageConditionType_value = map[string]int32{
		"STORAGE_CONDITION_TYPE_UNSPECIFIED": 0,
		"STORAGE_CONDITION_TYPE_CREATE_ONLY": 1,
		"STORAGE_CONDITION_TYPE_IF_MATCH":    2,
	}
)

func (x StorageConditionType) Enum() *StorageConditionType {
	p := new(StorageConditionType)
	*p = x
	return p
}

func (x StorageConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_proto_enumTypes[3].Descriptor()
}

func (StorageConditionType) Type() protoreflect.EnumType {
	return &file_action_v1_action_proto_enumTypes[3]
}

func (x StorageConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageConditionType.Descriptor instead.
func (StorageConditionType) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{3}
}

// Typed, bounded issuance. The signer never accepts an arbitrary message/digest,
// private key, or caller-selected signature domain.
type ControlSigningPurpose int32

const (
	ControlSigningPurpose_CONTROL_SIGNING_PURPOSE_UNSPECIFIED   ControlSigningPurpose = 0
	ControlSigningPurpose_CONTROL_SIGNING_PURPOSE_INSTALL_EPOCH ControlSigningPurpose = 1
	ControlSigningPurpose_CONTROL_SIGNING_PURPOSE_STORAGE_PUT   ControlSigningPurpose = 2
)

// Enum value maps for ControlSigningPurpose.
var (
	ControlSigningPurpose_name = map[int32]string{
		0: "CONTROL_SIGNING_PURPOSE_UNSPECIFIED",
		1: "CONTROL_SIGNING_PURPOSE_INSTALL_EPOCH",
		2: "CONTROL_SIGNING_PURPOSE_STORAGE_PUT",
	}
	ControlSigningPurpose_value = map[string]int32{
		"CONTROL_SIGNING_PURPOSE_UNSPECIFIED":   0,
		"CONTROL_SIGNING_PURPOSE_INSTALL_EPOCH": 1,
		"CONTROL_SIGNING_PURPOSE_STORAGE_PUT":   2,
	}
)

func (x ControlSigningPurpose) Enum() *ControlSigningPurpose {
	p := new(ControlSigningPurpose)
	*p = x
	return p
}

func (x ControlSigningPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlSigningPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_proto_enumTypes[4].Descriptor()
}

func (ControlSigningPurpose) Type() protoreflect.EnumType {
	return &file_action_v1_action_proto_enumTypes[4]
}

func (x ControlSigningPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlSigningPurpose.Descriptor instead.
func (ControlSigningPurpose) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{4}
}

type AdmitCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CommandKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=deepseek.action.v1.CommandKind" json:"kind,omitempty"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,2,opt,name=fence,proto3" json:"fence,omitempty"`
	LiveEpoch     uint64                 `protobuf:"varint,3,opt,name=live_epoch,json=liveEpoch,proto3" json:"live_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitCommandRequest) Reset() {
	*x = AdmitCommandRequest{}
	mi := &file_action_v1_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitCommandRequest) ProtoMessage() {}

func (x *AdmitCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitCommandRequest.ProtoReflect.Descriptor instead.
func (*AdmitCommandRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *AdmitCommandRequest) GetKind() CommandKind {
	if x != nil {
		return x.Kind
	}
	return CommandKind_COMMAND_KIND_UNSPECIFIED
}

func (x *AdmitCommandRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *AdmitCommandRequest) GetLiveEpoch() uint64 {
	if x != nil {
		return x.LiveEpoch
	}
	return 0
}

type AdmitCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AdmitStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=deepseek.action.v1.AdmitStatus" json:"status,omitempty"`
	State         commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitCommandResponse) Reset() {
	*x = AdmitCommandResponse{}
	mi := &file_action_v1_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitCommandResponse) ProtoMessage() {}

func (x *AdmitCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitCommandResponse.ProtoReflect.Descriptor instead.
func (*AdmitCommandResponse) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{1}
}

func (x *AdmitCommandResponse) GetStatus() AdmitStatus {
	if x != nil {
		return x.Status
	}
	return AdmitStatus_ADMIT_STATUS_UNSPECIFIED
}

func (x *AdmitCommandResponse) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *AdmitCommandResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type QueryEffectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEffectRequest) Reset() {
	*x = QueryEffectRequest{}
	mi := &file_action_v1_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEffectRequest) ProtoMessage() {}

func (x *QueryEffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEffectRequest.ProtoReflect.Descriptor instead.
func (*QueryEffectRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{2}
}

func (x *QueryEffectRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type EffectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	State         commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	EffectId      string                 `protobuf:"bytes,3,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	ReceiptDigest string                 `protobuf:"bytes,4,opt,name=receipt_digest,json=receiptDigest,proto3" json:"receipt_digest,omitempty"`
	CommitDigest  string                 `protobuf:"bytes,5,opt,name=commit_digest,json=commitDigest,proto3" json:"commit_digest,omitempty"`
	ProofDigest   string                 `protobuf:"bytes,6,opt,name=proof_digest,json=proofDigest,proto3" json:"proof_digest,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectResult) Reset() {
	*x = EffectResult{}
	mi := &file_action_v1_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectResult) ProtoMessage() {}

func (x *EffectResult) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectResult.ProtoReflect.Descriptor instead.
func (*EffectResult) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{3}
}

func (x *EffectResult) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *EffectResult) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *EffectResult) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *EffectResult) GetReceiptDigest() string {
	if x != nil {
		return x.ReceiptDigest
	}
	return ""
}

func (x *EffectResult) GetCommitDigest() string {
	if x != nil {
		return x.CommitDigest
	}
	return ""
}

func (x *EffectResult) GetProofDigest() string {
	if x != nil {
		return x.ProofDigest
	}
	return ""
}

func (x *EffectResult) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type InstallAuthoritativeEpochRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Fence            *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	CanonicalRequest []byte                 `protobuf:"bytes,2,opt,name=canonical_request,json=canonicalRequest,proto3" json:"canonical_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InstallAuthoritativeEpochRequest) Reset() {
	*x = InstallAuthoritativeEpochRequest{}
	mi := &file_action_v1_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAuthoritativeEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAuthoritativeEpochRequest) ProtoMessage() {}

func (x *InstallAuthoritativeEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAuthoritativeEpochRequest.ProtoReflect.Descriptor instead.
func (*InstallAuthoritativeEpochRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{4}
}

func (x *InstallAuthoritativeEpochRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *InstallAuthoritativeEpochRequest) GetCanonicalRequest() []byte {
	if x != nil {
		return x.CanonicalRequest
	}
	return nil
}

type InstallAuthoritativeEpochResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AdmitStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=deepseek.action.v1.AdmitStatus" json:"status,omitempty"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,2,opt,name=fence,proto3" json:"fence,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAuthoritativeEpochResponse) Reset() {
	*x = InstallAuthoritativeEpochResponse{}
	mi := &file_action_v1_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAuthoritativeEpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAuthoritativeEpochResponse) ProtoMessage() {}

func (x *InstallAuthoritativeEpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAuthoritativeEpochResponse.ProtoReflect.Descriptor instead.
func (*InstallAuthoritativeEpochResponse) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{5}
}

func (x *InstallAuthoritativeEpochResponse) GetStatus() AdmitStatus {
	if x != nil {
		return x.Status
	}
	return AdmitStatus_ADMIT_STATUS_UNSPECIFIED
}

func (x *InstallAuthoritativeEpochResponse) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *InstallAuthoritativeEpochResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type StoragePrecondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConditionType StorageConditionType   `protobuf:"varint,1,opt,name=condition_type,json=conditionType,proto3,enum=deepseek.action.v1.StorageConditionType" json:"condition_type,omitempty"`
	ExpectedEtag  string                 `protobuf:"bytes,2,opt,name=expected_etag,json=expectedEtag,proto3" json:"expected_etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePrecondition) Reset() {
	*x = StoragePrecondition{}
	mi := &file_action_v1_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePrecondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePrecondition) ProtoMessage() {}

func (x *StoragePrecondition) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePrecondition.ProtoReflect.Descriptor instead.
func (*StoragePrecondition) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{6}
}

func (x *StoragePrecondition) GetConditionType() StorageConditionType {
	if x != nil {
		return x.ConditionType
	}
	return StorageConditionType_STORAGE_CONDITION_TYPE_UNSPECIFIED
}

func (x *StoragePrecondition) GetExpectedEtag() string {
	if x != nil {
		return x.ExpectedEtag
	}
	return ""
}

type StorageMutationRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Fence                  *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	OperationId            string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RequestId              string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Nonce                  string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MutationType           string                 `protobuf:"bytes,5,opt,name=mutation_type,json=mutationType,proto3" json:"mutation_type,omitempty"`
	Provider               string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	TargetIdentity         string                 `protobuf:"bytes,7,opt,name=target_identity,json=targetIdentity,proto3" json:"target_identity,omitempty"`
	Bucket                 string                 `protobuf:"bytes,8,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix                 string                 `protobuf:"bytes,9,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ObjectKey              string                 `protobuf:"bytes,10,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	PayloadDigest          string                 `protobuf:"bytes,11,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	ExpectedLength         uint64                 `protobuf:"varint,12,opt,name=expected_length,json=expectedLength,proto3" json:"expected_length,omitempty"`
	Precondition           *StoragePrecondition   `protobuf:"bytes,13,opt,name=precondition,proto3" json:"precondition,omitempty"`
	CanonicalAuthorization []byte                 `protobuf:"bytes,14,opt,name=canonical_authorization,json=canonicalAuthorization,proto3" json:"canonical_authorization,omitempty"`
	SchemaVersion          uint32                 `protobuf:"varint,15,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Payload                []byte                 `protobuf:"bytes,16,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StorageMutationRequest) Reset() {
	*x = StorageMutationRequest{}
	mi := &file_action_v1_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMutationRequest) ProtoMessage() {}

func (x *StorageMutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMutationRequest.ProtoReflect.Descriptor instead.
func (*StorageMutationRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{7}
}

func (x *StorageMutationRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *StorageMutationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StorageMutationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StorageMutationRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *StorageMutationRequest) GetMutationType() string {
	if x != nil {
		return x.MutationType
	}
	return ""
}

func (x *StorageMutationRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StorageMutationRequest) GetTargetIdentity() string {
	if x != nil {
		return x.TargetIdentity
	}
	return ""
}

func (x *StorageMutationRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *StorageMutationRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *StorageMutationRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *StorageMutationRequest) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

func (x *StorageMutationRequest) GetExpectedLength() uint64 {
	if x != nil {
		return x.ExpectedLength
	}
	return 0
}

func (x *StorageMutationRequest) GetPrecondition() *StoragePrecondition {
	if x != nil {
		return x.Precondition
	}
	return nil
}

func (x *StorageMutationRequest) GetCanonicalAuthorization() []byte {
	if x != nil {
		return x.CanonicalAuthorization
	}
	return nil
}

func (x *StorageMutationRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *StorageMutationRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StorageMutationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           StorageMutationStatus  `protobuf:"varint,1,opt,name=status,proto3,enum=deepseek.action.v1.StorageMutationStatus" json:"status,omitempty"`
	State            commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	Fence            *commonv1.ActionFence  `protobuf:"bytes,3,opt,name=fence,proto3" json:"fence,omitempty"`
	OperationId      string                 `protobuf:"bytes,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	EffectId         string                 `protobuf:"bytes,5,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	Etag             string                 `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	ProviderMetadata string                 `protobuf:"bytes,7,opt,name=provider_metadata,json=providerMetadata,proto3" json:"provider_metadata,omitempty"`
	Error            *commonv1.ErrorDetail  `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StorageMutationResponse) Reset() {
	*x = StorageMutationResponse{}
	mi := &file_action_v1_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMutationResponse) ProtoMessage() {}

func (x *StorageMutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMutationResponse.ProtoReflect.Descriptor instead.
func (*StorageMutationResponse) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{8}
}

func (x *StorageMutationResponse) GetStatus() StorageMutationStatus {
	if x != nil {
		return x.Status
	}
	return StorageMutationStatus_STORAGE_MUTATION_STATUS_UNSPECIFIED
}

func (x *StorageMutationResponse) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *StorageMutationResponse) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *StorageMutationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StorageMutationResponse) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *StorageMutationResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *StorageMutationResponse) GetProviderMetadata() string {
	if x != nil {
		return x.ProviderMetadata
	}
	return ""
}

func (x *StorageMutationResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type QueryStorageEffectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStorageEffectRequest) Reset() {
	*x = QueryStorageEffectRequest{}
	mi := &file_action_v1_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStorageEffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStorageEffectRequest) ProtoMessage() {}

func (x *QueryStorageEffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStorageEffectRequest.ProtoReflect.Descriptor instead.
func (*QueryStorageEffectRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{9}
}

func (x *QueryStorageEffectRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *QueryStorageEffectRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type SignControlRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Purpose      ControlSigningPurpose  `protobuf:"varint,1,opt,name=purpose,proto3,enum=deepseek.action.v1.ControlSigningPurpose" json:"purpose,omitempty"`
	Fence        *commonv1.ActionFence  `protobuf:"bytes,2,opt,name=fence,proto3" json:"fence,omitempty"`
	RequestId    string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Nonce        string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Revision     int64                  `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	FencingToken uint64                 `protobuf:"varint,6,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	FleetId      string                 `protobuf:"bytes,7,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	Environment  string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	IssuedAt     string                 `protobuf:"bytes,9,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt    string                 `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// For STORAGE_PUT only. Payload and canonical_authorization must be empty.
	StorageIntent *StorageMutationRequest `protobuf:"bytes,11,opt,name=storage_intent,json=storageIntent,proto3" json:"storage_intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignControlRequest) Reset() {
	*x = SignControlRequest{}
	mi := &file_action_v1_action_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignControlRequest) ProtoMessage() {}

func (x *SignControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignControlRequest.ProtoReflect.Descriptor instead.
func (*SignControlRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{10}
}

func (x *SignControlRequest) GetPurpose() ControlSigningPurpose {
	if x != nil {
		return x.Purpose
	}
	return ControlSigningPurpose_CONTROL_SIGNING_PURPOSE_UNSPECIFIED
}

func (x *SignControlRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *SignControlRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignControlRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *SignControlRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SignControlRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *SignControlRequest) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *SignControlRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SignControlRequest) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

func (x *SignControlRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *SignControlRequest) GetStorageIntent() *StorageMutationRequest {
	if x != nil {
		return x.StorageIntent
	}
	return nil
}

type SignControlResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Fence             *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	CanonicalDocument []byte                 `protobuf:"bytes,2,opt,name=canonical_document,json=canonicalDocument,proto3" json:"canonical_document,omitempty"`
	SignerPublicKey   string                 `protobuf:"bytes,3,opt,name=signer_public_key,json=signerPublicKey,proto3" json:"signer_public_key,omitempty"`
	SignerKeyId       string                 `protobuf:"bytes,4,opt,name=signer_key_id,json=signerKeyId,proto3" json:"signer_key_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignControlResponse) Reset() {
	*x = SignControlResponse{}
	mi := &file_action_v1_action_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignControlResponse) ProtoMessage() {}

func (x *SignControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignControlResponse.ProtoReflect.Descriptor instead.
func (*SignControlResponse) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{11}
}

func (x *SignControlResponse) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *SignControlResponse) GetCanonicalDocument() []byte {
	if x != nil {
		return x.CanonicalDocument
	}
	return nil
}

func (x *SignControlResponse) GetSignerPublicKey() string {
	if x != nil {
		return x.SignerPublicKey
	}
	return ""
}

func (x *SignControlResponse) GetSignerKeyId() string {
	if x != nil {
		return x.SignerKeyId
	}
	return ""
}

var File_action_v1_action_proto protoreflect.FileDescriptor

const file_action_v1_action_proto_rawDesc = "" +
	"\n" +
	"\x16action/v1/action.proto\x12\x12deepseek.action.v1\x1a\x16common/v1/common.proto\"\xa0\x01\n" +
	"\x13AdmitCommandRequest\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.deepseek.action.v1.CommandKindR\x04kind\x125\n" +
	"\x05fence\x18\x02 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"live_epoch\x18\x03 \x01(\x04R\tliveEpoch\"\xbd\x01\n" +
	"\x14AdmitCommandResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.deepseek.action.v1.AdmitStatusR\x06status\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x125\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"K\n" +
	"\x12QueryEffectRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"\xbf\x02\n" +
	"\fEffectResult\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x12\x1b\n" +
	"\teffect_id\x18\x03 \x01(\tR\beffectId\x12%\n" +
	"\x0ereceipt_digest\x18\x04 \x01(\tR\rreceiptDigest\x12#\n" +
	"\rcommit_digest\x18\x05 \x01(\tR\fcommitDigest\x12!\n" +
	"\fproof_digest\x18\x06 \x01(\tR\vproofDigest\x125\n" +
	"\x05error\x18\a \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"\x86\x01\n" +
	" InstallAuthoritativeEpochRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12+\n" +
	"\x11canonical_request\x18\x02 \x01(\fR\x10canonicalRequest\"\xca\x01\n" +
	"!InstallAuthoritativeEpochResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.deepseek.action.v1.AdmitStatusR\x06status\x125\n" +
	"\x05fence\x18\x02 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x125\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"\x8b\x01\n" +
	"\x13StoragePrecondition\x12O\n" +
	"\x0econdition_type\x18\x01 \x01(\x0e2(.deepseek.action.v1.StorageConditionTypeR\rconditionType\x12#\n" +
	"\rexpected_etag\x18\x02 \x01(\tR\fexpectedEtag\"\xf7\x04\n" +
	"\x16StorageMutationRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12#\n" +
	"\rmutation_type\x18\x05 \x01(\tR\fmutationType\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12'\n" +
	"\x0ftarget_identity\x18\a \x01(\tR\x0etargetIdentity\x12\x16\n" +
	"\x06bucket\x18\b \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\t \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"object_key\x18\n" +
	" \x01(\tR\tobjectKey\x12%\n" +
	"\x0epayload_digest\x18\v \x01(\tR\rpayloadDigest\x12'\n" +
	"\x0fexpected_length\x18\f \x01(\x04R\x0eexpectedLength\x12K\n" +
	"\fprecondition\x18\r \x01(\v2'.deepseek.action.v1.StoragePreconditionR\fprecondition\x127\n" +
	"\x17canonical_authorization\x18\x0e \x01(\fR\x16canonicalAuthorization\x12%\n" +
	"\x0eschema_version\x18\x0f \x01(\rR\rschemaVersion\x12\x18\n" +
	"\apayload\x18\x10 \x01(\fR\apayload\"\x82\x03\n" +
	"\x17StorageMutationResponse\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).deepseek.action.v1.StorageMutationStatusR\x06status\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x125\n" +
	"\x05fence\x18\x03 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12!\n" +
	"\foperation_id\x18\x04 \x01(\tR\voperationId\x12\x1b\n" +
	"\teffect_id\x18\x05 \x01(\tR\beffectId\x12\x12\n" +
	"\x04etag\x18\x06 \x01(\tR\x04etag\x12+\n" +
	"\x11provider_metadata\x18\a \x01(\tR\x10providerMetadata\x125\n" +
	"\x05error\x18\b \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"u\n" +
	"\x19QueryStorageEffectRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"\xd2\x03\n" +
	"\x12SignControlRequest\x12C\n" +
	"\apurpose\x18\x01 \x01(\x0e2).deepseek.action.v1.ControlSigningPurposeR\apurpose\x125\n" +
	"\x05fence\x18\x02 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x03R\brevision\x12#\n" +
	"\rfencing_token\x18\x06 \x01(\x04R\ffencingToken\x12\x19\n" +
	"\bfleet_id\x18\a \x01(\tR\afleetId\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12\x1b\n" +
	"\tissued_at\x18\t \x01(\tR\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\x12Q\n" +
	"\x0estorage_intent\x18\v \x01(\v2*.deepseek.action.v1.StorageMutationRequestR\rstorageIntent\"\xcb\x01\n" +
	"\x13SignControlResponse\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12-\n" +
	"\x12canonical_document\x18\x02 \x01(\fR\x11canonicalDocument\x12*\n" +
	"\x11signer_public_key\x18\x03 \x01(\tR\x0fsignerPublicKey\x12\"\n" +
	"\rsigner_key_id\x18\x04 \x01(\tR\vsignerKeyId*\x81\x02\n" +
	"\vCommandKind\x12\x1c\n" +
	"\x18COMMAND_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCOMMAND_KIND_EXECUTE_BACKUP\x10\x01\x12 \n" +
	"\x1cCOMMAND_KIND_EXECUTE_RESTORE\x10\x02\x12\x1f\n" +
	"\x1bCOMMAND_KIND_EXECUTE_REPAIR\x10\x03\x12\"\n" +
	"\x1eCOMMAND_KIND_EXECUTE_REBALANCE\x10\x04\x12+\n" +
	"'COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER\x10\x05\x12\x1f\n" +
	"\x1bCOMMAND_KIND_SIGN_READINESS\x10\x06*a\n" +
	"\vAdmitStatus\x12\x1c\n" +
	"\x18ADMIT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ADMIT_STATUS_ADMITTED\x10\x01\x12\x19\n" +
	"\x15ADMIT_STATUS_REJECTED\x10\x02*\x86\x02\n" +
	"\x15StorageMutationStatus\x12'\n" +
	"#STORAGE_MUTATION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!STORAGE_MUTATION_STATUS_CONFIRMED\x10\x01\x12*\n" +
	"&STORAGE_MUTATION_STATUS_EFFECT_UNKNOWN\x10\x02\x12'\n" +
	"#STORAGE_MUTATION_STATUS_RECONCILING\x10\x03\x12$\n" +
	" STORAGE_MUTATION_STATUS_REJECTED\x10\x04\x12\"\n" +
	"\x1eSTORAGE_MUTATION_STATUS_FAILED\x10\x05*\x8b\x01\n" +
	"\x14StorageConditionType\x12&\n" +
	"\"STORAGE_CONDITION_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"STORAGE_CONDITION_TYPE_CREATE_ONLY\x10\x01\x12#\n" +
	"\x1fSTORAGE_CONDITION_TYPE_IF_MATCH\x10\x02*\x94\x01\n" +
	"\x15ControlSigningPurpose\x12'\n" +
	"#CONTROL_SIGNING_PURPOSE_UNSPECIFIED\x10\x00\x12)\n" +
	"%CONTROL_SIGNING_PURPOSE_INSTALL_EPOCH\x10\x01\x12'\n" +
	"#CONTROL_SIGNING_PURPOSE_STORAGE_PUT\x10\x022\xb4\x04\n" +
	"\x06Worker\x12a\n" +
	"\fAdmitCommand\x12'.deepseek.action.v1.AdmitCommandRequest\x1a(.deepseek.action.v1.AdmitCommandResponse\x12W\n" +
	"\vQueryEffect\x12&.deepseek.action.v1.QueryEffectRequest\x1a .deepseek.action.v1.EffectResult\x12\x88\x01\n" +
	"\x19InstallAuthoritativeEpoch\x124.deepseek.action.v1.InstallAuthoritativeEpochRequest\x1a5.deepseek.action.v1.InstallAuthoritativeEpochResponse\x12q\n" +
	"\x16ExecuteStorageMutation\x12*.deepseek.action.v1.StorageMutationRequest\x1a+.deepseek.action.v1.StorageMutationResponse\x12p\n" +
	"\x12QueryStorageEffect\x12-.deepseek.action.v1.QueryStorageEffectRequest\x1a+.deepseek.action.v1.StorageMutationResponse2o\n" +
	"\rControlSigner\x12^\n" +
	"\vSignControl\x12&.deepseek.action.v1.SignControlRequest\x1a'.deepseek.action.v1.SignControlResponseBHZFgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/actionv1;actionv1b\x06proto3"

var (
	file_action_v1_action_proto_rawDescOnce sync.Once
	file_action_v1_action_proto_rawDescData []byte
)

func file_action_v1_action_proto_rawDescGZIP() []byte {
	file_action_v1_action_proto_rawDescOnce.Do(func() {
		file_action_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_v1_action_proto_rawDesc), len(file_action_v1_action_proto_rawDesc)))
	})
	return file_action_v1_action_proto_rawDescData
}

var file_action_v1_action_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_action_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_action_v1_action_proto_goTypes = []any{
	(CommandKind)(0),                          // 0: deepseek.action.v1.CommandKind
	(AdmitStatus)(0),                          // 1: deepseek.action.v1.AdmitStatus
	(StorageMutationStatus)(0),                // 2: deepseek.action.v1.StorageMutationStatus
	(StorageConditionType)(0),                 // 3: deepseek.action.v1.StorageConditionType
	(ControlSigningPurpose)(0),                // 4: deepseek.action.v1.ControlSigningPurpose
	(*AdmitCommandRequest)(nil),               // 5: deepseek.action.v1.AdmitCommandRequest
	(*AdmitCommandResponse)(nil),              // 6: deepseek.action.v1.AdmitCommandResponse
	(*QueryEffectRequest)(nil),                // 7: deepseek.action.v1.QueryEffectRequest
	(*EffectResult)(nil),                      // 8: deepseek.action.v1.EffectResult
	(*InstallAuthoritativeEpochRequest)(nil),  // 9: deepseek.action.v1.InstallAuthoritativeEpochRequest
	(*InstallAuthoritativeEpochResponse)(nil), // 10: deepseek.action.v1.InstallAuthoritativeEpochResponse
	(*StoragePrecondition)(nil),               // 11: deepseek.action.v1.StoragePrecondition
	(*StorageMutationRequest)(nil),            // 12: deepseek.action.v1.StorageMutationRequest
	(*StorageMutationResponse)(nil),           // 13: deepseek.action.v1.StorageMutationResponse
	(*QueryStorageEffectRequest)(nil),         // 14: deepseek.action.v1.QueryStorageEffectRequest
	(*SignControlRequest)(nil),                // 15: deepseek.action.v1.SignControlRequest
	(*SignControlResponse)(nil),               // 16: deepseek.action.v1.SignControlResponse
	(*commonv1.ActionFence)(nil),              // 17: deepseek.common.v1.ActionFence
	(commonv1.EffectState)(0),                 // 18: deepseek.common.v1.EffectState
	(*commonv1.ErrorDetail)(nil),              // 19: deepseek.common.v1.ErrorDetail
}
var file_action_v1_action_proto_depIdxs = []int32{
	0,  // 0: deepseek.action.v1.AdmitCommandRequest.kind:type_name -> deepseek.action.v1.CommandKind
	17, // 1: deepseek.action.v1.AdmitCommandRequest.fence:type_name -> deepseek.common.v1.ActionFence
	1,  // 2: deepseek.action.v1.AdmitCommandResponse.status:type_name -> deepseek.action.v1.AdmitStatus
	18, // 3: deepseek.action.v1.AdmitCommandResponse.state:type_name -> deepseek.common.v1.EffectState
	19, // 4: deepseek.action.v1.AdmitCommandResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	17, // 5: deepseek.action.v1.QueryEffectRequest.fence:type_name -> deepseek.common.v1.ActionFence
	17, // 6: deepseek.action.v1.EffectResult.fence:type_name -> deepseek.common.v1.ActionFence
	18, // 7: deepseek.action.v1.EffectResult.state:type_name -> deepseek.common.v1.EffectState
	19, // 8: deepseek.action.v1.EffectResult.error:type_name -> deepseek.common.v1.ErrorDetail
	17, // 9: deepseek.action.v1.InstallAuthoritativeEpochRequest.fence:type_name -> deepseek.common.v1.ActionFence
	1,  // 10: deepseek.action.v1.InstallAuthoritativeEpochResponse.status:type_name -> deepseek.action.v1.AdmitStatus
	17, // 11: deepseek.action.v1.InstallAuthoritativeEpochResponse.fence:type_name -> deepseek.common.v1.ActionFence
	19, // 12: deepseek.action.v1.InstallAuthoritativeEpochResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	3,  // 13: deepseek.action.v1.StoragePrecondition.condition_type:type_name -> deepseek.action.v1.StorageConditionType
	17, // 14: deepseek.action.v1.StorageMutationRequest.fence:type_name -> deepseek.common.v1.ActionFence
	11, // 15: deepseek.action.v1.StorageMutationRequest.precondition:type_name -> deepseek.action.v1.StoragePrecondition
	2,  // 16: deepseek.action.v1.StorageMutationResponse.status:type_name -> deepseek.action.v1.StorageMutationStatus
	18, // 17: deepseek.action.v1.StorageMutationResponse.state:type_name -> deepseek.common.v1.EffectState
	17, // 18: deepseek.action.v1.StorageMutationResponse.fence:type_name -> deepseek.common.v1.ActionFence
	19, // 19: deepseek.action.v1.StorageMutationResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	17, // 20: deepseek.action.v1.QueryStorageEffectRequest.fence:type_name -> deepseek.common.v1.ActionFence
	4,  // 21: deepseek.action.v1.SignControlRequest.purpose:type_name -> deepseek.action.v1.ControlSigningPurpose
	17, // 22: deepseek.action.v1.SignControlRequest.fence:type_name -> deepseek.common.v1.ActionFence
	12, // 23: deepseek.action.v1.SignControlRequest.storage_intent:type_name -> deepseek.action.v1.StorageMutationRequest
	17, // 24: deepseek.action.v1.SignControlResponse.fence:type_name -> deepseek.common.v1.ActionFence
	5,  // 25: deepseek.action.v1.Worker.AdmitCommand:input_type -> deepseek.action.v1.AdmitCommandRequest
	7,  // 26: deepseek.action.v1.Worker.QueryEffect:input_type -> deepseek.action.v1.QueryEffectRequest
	9,  // 27: deepseek.action.v1.Worker.InstallAuthoritativeEpoch:input_type -> deepseek.action.v1.InstallAuthoritativeEpochRequest
	12, // 28: deepseek.action.v1.Worker.ExecuteStorageMutation:input_type -> deepseek.action.v1.StorageMutationRequest
	14, // 29: deepseek.action.v1.Worker.QueryStorageEffect:input_type -> deepseek.action.v1.QueryStorageEffectRequest
	15, // 30: deepseek.action.v1.ControlSigner.SignControl:input_type -> deepseek.action.v1.SignControlRequest
	6,  // 31: deepseek.action.v1.Worker.AdmitCommand:output_type -> deepseek.action.v1.AdmitCommandResponse
	8,  // 32: deepseek.action.v1.Worker.QueryEffect:output_type -> deepseek.action.v1.EffectResult
	10, // 33: deepseek.action.v1.Worker.InstallAuthoritativeEpoch:output_type -> deepseek.action.v1.InstallAuthoritativeEpochResponse
	13, // 34: deepseek.action.v1.Worker.ExecuteStorageMutation:output_type -> deepseek.action.v1.StorageMutationResponse
	13, // 35: deepseek.action.v1.Worker.QueryStorageEffect:output_type -> deepseek.action.v1.StorageMutationResponse
	16, // 36: deepseek.action.v1.ControlSigner.SignControl:output_type -> deepseek.action.v1.SignControlResponse
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_action_v1_action_proto_init() }
func file_action_v1_action_proto_init() {
	if File_action_v1_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_v1_action_proto_rawDesc), len(file_action_v1_action_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_action_v1_action_proto_goTypes,
		DependencyIndexes: file_action_v1_action_proto_depIdxs,
		EnumInfos:         file_action_v1_action_proto_enumTypes,
		MessageInfos:      file_action_v1_action_proto_msgTypes,
	}.Build()
	File_action_v1_action_proto = out.File
	file_action_v1_action_proto_goTypes = nil
	file_action_v1_action_proto_depIdxs = nil
}
