// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: action/v1/action.proto

package actionv1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandKind int32

const (
	CommandKind_COMMAND_KIND_UNSPECIFIED                CommandKind = 0
	CommandKind_COMMAND_KIND_EXECUTE_BACKUP             CommandKind = 1
	CommandKind_COMMAND_KIND_EXECUTE_RESTORE            CommandKind = 2
	CommandKind_COMMAND_KIND_EXECUTE_REPAIR             CommandKind = 3
	CommandKind_COMMAND_KIND_EXECUTE_REBALANCE          CommandKind = 4
	CommandKind_COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER CommandKind = 5
	CommandKind_COMMAND_KIND_SIGN_READINESS             CommandKind = 6
)

// Enum value maps for CommandKind.
var (
	CommandKind_name = map[int32]string{
		0: "COMMAND_KIND_UNSPECIFIED",
		1: "COMMAND_KIND_EXECUTE_BACKUP",
		2: "COMMAND_KIND_EXECUTE_RESTORE",
		3: "COMMAND_KIND_EXECUTE_REPAIR",
		4: "COMMAND_KIND_EXECUTE_REBALANCE",
		5: "COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER",
		6: "COMMAND_KIND_SIGN_READINESS",
	}
	CommandKind_value = map[string]int32{
		"COMMAND_KIND_UNSPECIFIED":                0,
		"COMMAND_KIND_EXECUTE_BACKUP":             1,
		"COMMAND_KIND_EXECUTE_RESTORE":            2,
		"COMMAND_KIND_EXECUTE_REPAIR":             3,
		"COMMAND_KIND_EXECUTE_REBALANCE":          4,
		"COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER": 5,
		"COMMAND_KIND_SIGN_READINESS":             6,
	}
)

func (x CommandKind) Enum() *CommandKind {
	p := new(CommandKind)
	*p = x
	return p
}

func (x CommandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_proto_enumTypes[0].Descriptor()
}

func (CommandKind) Type() protoreflect.EnumType {
	return &file_action_v1_action_proto_enumTypes[0]
}

func (x CommandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandKind.Descriptor instead.
func (CommandKind) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{0}
}

type AdmitStatus int32

const (
	AdmitStatus_ADMIT_STATUS_UNSPECIFIED AdmitStatus = 0
	AdmitStatus_ADMIT_STATUS_ADMITTED    AdmitStatus = 1
	AdmitStatus_ADMIT_STATUS_REJECTED    AdmitStatus = 2
)

// Enum value maps for AdmitStatus.
var (
	AdmitStatus_name = map[int32]string{
		0: "ADMIT_STATUS_UNSPECIFIED",
		1: "ADMIT_STATUS_ADMITTED",
		2: "ADMIT_STATUS_REJECTED",
	}
	AdmitStatus_value = map[string]int32{
		"ADMIT_STATUS_UNSPECIFIED": 0,
		"ADMIT_STATUS_ADMITTED":    1,
		"ADMIT_STATUS_REJECTED":    2,
	}
)

func (x AdmitStatus) Enum() *AdmitStatus {
	p := new(AdmitStatus)
	*p = x
	return p
}

func (x AdmitStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdmitStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_proto_enumTypes[1].Descriptor()
}

func (AdmitStatus) Type() protoreflect.EnumType {
	return &file_action_v1_action_proto_enumTypes[1]
}

func (x AdmitStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdmitStatus.Descriptor instead.
func (AdmitStatus) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{1}
}

type AdmitCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CommandKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=deepseek.action.v1.CommandKind" json:"kind,omitempty"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,2,opt,name=fence,proto3" json:"fence,omitempty"`
	LiveEpoch     uint64                 `protobuf:"varint,3,opt,name=live_epoch,json=liveEpoch,proto3" json:"live_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitCommandRequest) Reset() {
	*x = AdmitCommandRequest{}
	mi := &file_action_v1_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitCommandRequest) ProtoMessage() {}

func (x *AdmitCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitCommandRequest.ProtoReflect.Descriptor instead.
func (*AdmitCommandRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *AdmitCommandRequest) GetKind() CommandKind {
	if x != nil {
		return x.Kind
	}
	return CommandKind_COMMAND_KIND_UNSPECIFIED
}

func (x *AdmitCommandRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *AdmitCommandRequest) GetLiveEpoch() uint64 {
	if x != nil {
		return x.LiveEpoch
	}
	return 0
}

type AdmitCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AdmitStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=deepseek.action.v1.AdmitStatus" json:"status,omitempty"`
	State         commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitCommandResponse) Reset() {
	*x = AdmitCommandResponse{}
	mi := &file_action_v1_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitCommandResponse) ProtoMessage() {}

func (x *AdmitCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitCommandResponse.ProtoReflect.Descriptor instead.
func (*AdmitCommandResponse) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{1}
}

func (x *AdmitCommandResponse) GetStatus() AdmitStatus {
	if x != nil {
		return x.Status
	}
	return AdmitStatus_ADMIT_STATUS_UNSPECIFIED
}

func (x *AdmitCommandResponse) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *AdmitCommandResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type QueryEffectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEffectRequest) Reset() {
	*x = QueryEffectRequest{}
	mi := &file_action_v1_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEffectRequest) ProtoMessage() {}

func (x *QueryEffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEffectRequest.ProtoReflect.Descriptor instead.
func (*QueryEffectRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{2}
}

func (x *QueryEffectRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type EffectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	State         commonv1.EffectState   `protobuf:"varint,2,opt,name=state,proto3,enum=deepseek.common.v1.EffectState" json:"state,omitempty"`
	EffectId      string                 `protobuf:"bytes,3,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	ReceiptDigest string                 `protobuf:"bytes,4,opt,name=receipt_digest,json=receiptDigest,proto3" json:"receipt_digest,omitempty"`
	CommitDigest  string                 `protobuf:"bytes,5,opt,name=commit_digest,json=commitDigest,proto3" json:"commit_digest,omitempty"`
	ProofDigest   string                 `protobuf:"bytes,6,opt,name=proof_digest,json=proofDigest,proto3" json:"proof_digest,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectResult) Reset() {
	*x = EffectResult{}
	mi := &file_action_v1_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectResult) ProtoMessage() {}

func (x *EffectResult) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectResult.ProtoReflect.Descriptor instead.
func (*EffectResult) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{3}
}

func (x *EffectResult) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *EffectResult) GetState() commonv1.EffectState {
	if x != nil {
		return x.State
	}
	return commonv1.EffectState(0)
}

func (x *EffectResult) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *EffectResult) GetReceiptDigest() string {
	if x != nil {
		return x.ReceiptDigest
	}
	return ""
}

func (x *EffectResult) GetCommitDigest() string {
	if x != nil {
		return x.CommitDigest
	}
	return ""
}

func (x *EffectResult) GetProofDigest() string {
	if x != nil {
		return x.ProofDigest
	}
	return ""
}

func (x *EffectResult) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_action_v1_action_proto protoreflect.FileDescriptor

const file_action_v1_action_proto_rawDesc = "" +
	"\n" +
	"\x16action/v1/action.proto\x12\x12deepseek.action.v1\x1a\x16common/v1/common.proto\"\xa0\x01\n" +
	"\x13AdmitCommandRequest\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.deepseek.action.v1.CommandKindR\x04kind\x125\n" +
	"\x05fence\x18\x02 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"live_epoch\x18\x03 \x01(\x04R\tliveEpoch\"\xbd\x01\n" +
	"\x14AdmitCommandResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.deepseek.action.v1.AdmitStatusR\x06status\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x125\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"K\n" +
	"\x12QueryEffectRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"\xbf\x02\n" +
	"\fEffectResult\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.deepseek.common.v1.EffectStateR\x05state\x12\x1b\n" +
	"\teffect_id\x18\x03 \x01(\tR\beffectId\x12%\n" +
	"\x0ereceipt_digest\x18\x04 \x01(\tR\rreceiptDigest\x12#\n" +
	"\rcommit_digest\x18\x05 \x01(\tR\fcommitDigest\x12!\n" +
	"\fproof_digest\x18\x06 \x01(\tR\vproofDigest\x125\n" +
	"\x05error\x18\a \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error*\x81\x02\n" +
	"\vCommandKind\x12\x1c\n" +
	"\x18COMMAND_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCOMMAND_KIND_EXECUTE_BACKUP\x10\x01\x12 \n" +
	"\x1cCOMMAND_KIND_EXECUTE_RESTORE\x10\x02\x12\x1f\n" +
	"\x1bCOMMAND_KIND_EXECUTE_REPAIR\x10\x03\x12\"\n" +
	"\x1eCOMMAND_KIND_EXECUTE_REBALANCE\x10\x04\x12+\n" +
	"'COMMAND_KIND_EXECUTE_FEDERATED_TRANSFER\x10\x05\x12\x1f\n" +
	"\x1bCOMMAND_KIND_SIGN_READINESS\x10\x06*a\n" +
	"\vAdmitStatus\x12\x1c\n" +
	"\x18ADMIT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ADMIT_STATUS_ADMITTED\x10\x01\x12\x19\n" +
	"\x15ADMIT_STATUS_REJECTED\x10\x022\xc4\x01\n" +
	"\x06Worker\x12a\n" +
	"\fAdmitCommand\x12'.deepseek.action.v1.AdmitCommandRequest\x1a(.deepseek.action.v1.AdmitCommandResponse\x12W\n" +
	"\vQueryEffect\x12&.deepseek.action.v1.QueryEffectRequest\x1a .deepseek.action.v1.EffectResultBHZFgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/actionv1;actionv1b\x06proto3"

var (
	file_action_v1_action_proto_rawDescOnce sync.Once
	file_action_v1_action_proto_rawDescData []byte
)

func file_action_v1_action_proto_rawDescGZIP() []byte {
	file_action_v1_action_proto_rawDescOnce.Do(func() {
		file_action_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_v1_action_proto_rawDesc), len(file_action_v1_action_proto_rawDesc)))
	})
	return file_action_v1_action_proto_rawDescData
}

var file_action_v1_action_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_action_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_action_v1_action_proto_goTypes = []any{
	(CommandKind)(0),             // 0: deepseek.action.v1.CommandKind
	(AdmitStatus)(0),             // 1: deepseek.action.v1.AdmitStatus
	(*AdmitCommandRequest)(nil),  // 2: deepseek.action.v1.AdmitCommandRequest
	(*AdmitCommandResponse)(nil), // 3: deepseek.action.v1.AdmitCommandResponse
	(*QueryEffectRequest)(nil),   // 4: deepseek.action.v1.QueryEffectRequest
	(*EffectResult)(nil),         // 5: deepseek.action.v1.EffectResult
	(*commonv1.ActionFence)(nil), // 6: deepseek.common.v1.ActionFence
	(commonv1.EffectState)(0),    // 7: deepseek.common.v1.EffectState
	(*commonv1.ErrorDetail)(nil), // 8: deepseek.common.v1.ErrorDetail
}
var file_action_v1_action_proto_depIdxs = []int32{
	0,  // 0: deepseek.action.v1.AdmitCommandRequest.kind:type_name -> deepseek.action.v1.CommandKind
	6,  // 1: deepseek.action.v1.AdmitCommandRequest.fence:type_name -> deepseek.common.v1.ActionFence
	1,  // 2: deepseek.action.v1.AdmitCommandResponse.status:type_name -> deepseek.action.v1.AdmitStatus
	7,  // 3: deepseek.action.v1.AdmitCommandResponse.state:type_name -> deepseek.common.v1.EffectState
	8,  // 4: deepseek.action.v1.AdmitCommandResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	6,  // 5: deepseek.action.v1.QueryEffectRequest.fence:type_name -> deepseek.common.v1.ActionFence
	6,  // 6: deepseek.action.v1.EffectResult.fence:type_name -> deepseek.common.v1.ActionFence
	7,  // 7: deepseek.action.v1.EffectResult.state:type_name -> deepseek.common.v1.EffectState
	8,  // 8: deepseek.action.v1.EffectResult.error:type_name -> deepseek.common.v1.ErrorDetail
	2,  // 9: deepseek.action.v1.Worker.AdmitCommand:input_type -> deepseek.action.v1.AdmitCommandRequest
	4,  // 10: deepseek.action.v1.Worker.QueryEffect:input_type -> deepseek.action.v1.QueryEffectRequest
	3,  // 11: deepseek.action.v1.Worker.AdmitCommand:output_type -> deepseek.action.v1.AdmitCommandResponse
	5,  // 12: deepseek.action.v1.Worker.QueryEffect:output_type -> deepseek.action.v1.EffectResult
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_action_v1_action_proto_init() }
func file_action_v1_action_proto_init() {
	if File_action_v1_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_v1_action_proto_rawDesc), len(file_action_v1_action_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_action_v1_action_proto_goTypes,
		DependencyIndexes: file_action_v1_action_proto_depIdxs,
		EnumInfos:         file_action_v1_action_proto_enumTypes,
		MessageInfos:      file_action_v1_action_proto_msgTypes,
	}.Build()
	File_action_v1_action_proto = out.File
	file_action_v1_action_proto_goTypes = nil
	file_action_v1_action_proto_depIdxs = nil
}
