// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: platform/v1/ocr.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentHeader struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SourceBytes  uint64                 `protobuf:"varint,1,opt,name=source_bytes,json=sourceBytes,proto3" json:"source_bytes,omitempty"`
	SourceSha256 []byte                 `protobuf:"bytes,2,opt,name=source_sha256,json=sourceSha256,proto3" json:"source_sha256,omitempty"`
	// One-based PDF page number, already clamped by Rust. Zero for OCR.
	PageIndex uint32 `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	// Render scale multiplied by 1000. Zero selects the platform OCR scale.
	ScaleMilli    uint32 `protobuf:"varint,4,opt,name=scale_milli,json=scaleMilli,proto3" json:"scale_milli,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentHeader) Reset() {
	*x = DocumentHeader{}
	mi := &file_platform_v1_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentHeader) ProtoMessage() {}

func (x *DocumentHeader) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentHeader.ProtoReflect.Descriptor instead.
func (*DocumentHeader) Descriptor() ([]byte, []int) {
	return file_platform_v1_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentHeader) GetSourceBytes() uint64 {
	if x != nil {
		return x.SourceBytes
	}
	return 0
}

func (x *DocumentHeader) GetSourceSha256() []byte {
	if x != nil {
		return x.SourceSha256
	}
	return nil
}

func (x *DocumentHeader) GetPageIndex() uint32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *DocumentHeader) GetScaleMilli() uint32 {
	if x != nil {
		return x.ScaleMilli
	}
	return 0
}

type DocumentChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*DocumentChunk_Header
	//	*DocumentChunk_Data
	Part          isDocumentChunk_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_platform_v1_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_platform_v1_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentChunk) GetPart() isDocumentChunk_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *DocumentChunk) GetHeader() *DocumentHeader {
	if x != nil {
		if x, ok := x.Part.(*DocumentChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *DocumentChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Part.(*DocumentChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isDocumentChunk_Part interface {
	isDocumentChunk_Part()
}

type DocumentChunk_Header struct {
	Header *DocumentHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type DocumentChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DocumentChunk_Header) isDocumentChunk_Part() {}

func (*DocumentChunk_Data) isDocumentChunk_Part() {}

type OcrCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrCandidate) Reset() {
	*x = OcrCandidate{}
	mi := &file_platform_v1_ocr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrCandidate) ProtoMessage() {}

func (x *OcrCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_ocr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrCandidate.ProtoReflect.Descriptor instead.
func (*OcrCandidate) Descriptor() ([]byte, []int) {
	return file_platform_v1_ocr_proto_rawDescGZIP(), []int{2}
}

func (x *OcrCandidate) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *OcrCandidate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type OcrPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageIndex     uint32                 `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Blank         bool                   `protobuf:"varint,4,opt,name=blank,proto3" json:"blank,omitempty"`
	Candidates    []*OcrCandidate        `protobuf:"bytes,5,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrPage) Reset() {
	*x = OcrPage{}
	mi := &file_platform_v1_ocr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrPage) ProtoMessage() {}

func (x *OcrPage) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_ocr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrPage.ProtoReflect.Descriptor instead.
func (*OcrPage) Descriptor() ([]byte, []int) {
	return file_platform_v1_ocr_proto_rawDescGZIP(), []int{3}
}

func (x *OcrPage) GetPageIndex() uint32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *OcrPage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *OcrPage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *OcrPage) GetBlank() bool {
	if x != nil {
		return x.Blank
	}
	return false
}

func (x *OcrPage) GetCandidates() []*OcrCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// Decoded read-only data. Recognition does not admit or execute an action and
// cannot install an epoch, issue a receipt, or write any authoritative store.
type RecognizedDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceSha256  []byte                 `protobuf:"bytes,1,opt,name=source_sha256,json=sourceSha256,proto3" json:"source_sha256,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Pages         []*OcrPage             `protobuf:"bytes,3,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizedDocument) Reset() {
	*x = RecognizedDocument{}
	mi := &file_platform_v1_ocr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizedDocument) ProtoMessage() {}

func (x *RecognizedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_ocr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizedDocument.ProtoReflect.Descriptor instead.
func (*RecognizedDocument) Descriptor() ([]byte, []int) {
	return file_platform_v1_ocr_proto_rawDescGZIP(), []int{4}
}

func (x *RecognizedDocument) GetSourceSha256() []byte {
	if x != nil {
		return x.SourceSha256
	}
	return nil
}

func (x *RecognizedDocument) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *RecognizedDocument) GetPages() []*OcrPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

type RenderedPdfPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceSha256  []byte                 `protobuf:"bytes,1,opt,name=source_sha256,json=sourceSha256,proto3" json:"source_sha256,omitempty"`
	Png           []byte                 `protobuf:"bytes,2,opt,name=png,proto3" json:"png,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	PageIndex     uint32                 `protobuf:"varint,5,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,6,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderedPdfPage) Reset() {
	*x = RenderedPdfPage{}
	mi := &file_platform_v1_ocr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderedPdfPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderedPdfPage) ProtoMessage() {}

func (x *RenderedPdfPage) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_ocr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderedPdfPage.ProtoReflect.Descriptor instead.
func (*RenderedPdfPage) Descriptor() ([]byte, []int) {
	return file_platform_v1_ocr_proto_rawDescGZIP(), []int{5}
}

func (x *RenderedPdfPage) GetSourceSha256() []byte {
	if x != nil {
		return x.SourceSha256
	}
	return nil
}

func (x *RenderedPdfPage) GetPng() []byte {
	if x != nil {
		return x.Png
	}
	return nil
}

func (x *RenderedPdfPage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RenderedPdfPage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RenderedPdfPage) GetPageIndex() uint32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *RenderedPdfPage) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_platform_v1_ocr_proto protoreflect.FileDescriptor

const file_platform_v1_ocr_proto_rawDesc = "" +
	"\n" +
	"\x15platform/v1/ocr.proto\x12\x14deepseek.platform.v1\"\x98\x01\n" +
	"\x0eDocumentHeader\x12!\n" +
	"\fsource_bytes\x18\x01 \x01(\x04R\vsourceBytes\x12#\n" +
	"\rsource_sha256\x18\x02 \x01(\fR\fsourceSha256\x12\x1d\n" +
	"\n" +
	"page_index\x18\x03 \x01(\rR\tpageIndex\x12\x1f\n" +
	"\vscale_milli\x18\x04 \x01(\rR\n" +
	"scaleMilli\"m\n" +
	"\rDocumentChunk\x12>\n" +
	"\x06header\x18\x01 \x01(\v2$.deepseek.platform.v1.DocumentHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x06\n" +
	"\x04part\":\n" +
	"\fOcrCandidate\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xb0\x01\n" +
	"\aOcrPage\x12\x1d\n" +
	"\n" +
	"page_index\x18\x01 \x01(\rR\tpageIndex\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x14\n" +
	"\x05blank\x18\x04 \x01(\bR\x05blank\x12B\n" +
	"\n" +
	"candidates\x18\x05 \x03(\v2\".deepseek.platform.v1.OcrCandidateR\n" +
	"candidates\"\x8f\x01\n" +
	"\x12RecognizedDocument\x12#\n" +
	"\rsource_sha256\x18\x01 \x01(\fR\fsourceSha256\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\rR\n" +
	"totalPages\x123\n" +
	"\x05pages\x18\x03 \x03(\v2\x1d.deepseek.platform.v1.OcrPageR\x05pages\"\xb6\x01\n" +
	"\x0fRenderedPdfPage\x12#\n" +
	"\rsource_sha256\x18\x01 \x01(\fR\fsourceSha256\x12\x10\n" +
	"\x03png\x18\x02 \x01(\fR\x03png\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"page_index\x18\x05 \x01(\rR\tpageIndex\x12\x1f\n" +
	"\vtotal_pages\x18\x06 \x01(\rR\n" +
	"totalPages2\xb6\x02\n" +
	"\x11PlatformOcrEngine\x12a\n" +
	"\x0eRecognizeImage\x12#.deepseek.platform.v1.DocumentChunk\x1a(.deepseek.platform.v1.RecognizedDocument(\x01\x12_\n" +
	"\fRecognizePdf\x12#.deepseek.platform.v1.DocumentChunk\x1a(.deepseek.platform.v1.RecognizedDocument(\x01\x12]\n" +
	"\rRenderPdfPage\x12#.deepseek.platform.v1.DocumentChunk\x1a%.deepseek.platform.v1.RenderedPdfPage(\x01B{\n" +
	"\x1fcom.deepseek.mobile.platform.v1B\vPlatformOcrZKgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_ocr_proto_rawDescOnce sync.Once
	file_platform_v1_ocr_proto_rawDescData []byte
)

func file_platform_v1_ocr_proto_rawDescGZIP() []byte {
	file_platform_v1_ocr_proto_rawDescOnce.Do(func() {
		file_platform_v1_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_ocr_proto_rawDesc), len(file_platform_v1_ocr_proto_rawDesc)))
	})
	return file_platform_v1_ocr_proto_rawDescData
}

var file_platform_v1_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_platform_v1_ocr_proto_goTypes = []any{
	(*DocumentHeader)(nil),     // 0: deepseek.platform.v1.DocumentHeader
	(*DocumentChunk)(nil),      // 1: deepseek.platform.v1.DocumentChunk
	(*OcrCandidate)(nil),       // 2: deepseek.platform.v1.OcrCandidate
	(*OcrPage)(nil),            // 3: deepseek.platform.v1.OcrPage
	(*RecognizedDocument)(nil), // 4: deepseek.platform.v1.RecognizedDocument
	(*RenderedPdfPage)(nil),    // 5: deepseek.platform.v1.RenderedPdfPage
}
var file_platform_v1_ocr_proto_depIdxs = []int32{
	0, // 0: deepseek.platform.v1.DocumentChunk.header:type_name -> deepseek.platform.v1.DocumentHeader
	2, // 1: deepseek.platform.v1.OcrPage.candidates:type_name -> deepseek.platform.v1.OcrCandidate
	3, // 2: deepseek.platform.v1.RecognizedDocument.pages:type_name -> deepseek.platform.v1.OcrPage
	1, // 3: deepseek.platform.v1.PlatformOcrEngine.RecognizeImage:input_type -> deepseek.platform.v1.DocumentChunk
	1, // 4: deepseek.platform.v1.PlatformOcrEngine.RecognizePdf:input_type -> deepseek.platform.v1.DocumentChunk
	1, // 5: deepseek.platform.v1.PlatformOcrEngine.RenderPdfPage:input_type -> deepseek.platform.v1.DocumentChunk
	4, // 6: deepseek.platform.v1.PlatformOcrEngine.RecognizeImage:output_type -> deepseek.platform.v1.RecognizedDocument
	4, // 7: deepseek.platform.v1.PlatformOcrEngine.RecognizePdf:output_type -> deepseek.platform.v1.RecognizedDocument
	5, // 8: deepseek.platform.v1.PlatformOcrEngine.RenderPdfPage:output_type -> deepseek.platform.v1.RenderedPdfPage
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_platform_v1_ocr_proto_init() }
func file_platform_v1_ocr_proto_init() {
	if File_platform_v1_ocr_proto != nil {
		return
	}
	file_platform_v1_ocr_proto_msgTypes[1].OneofWrappers = []any{
		(*DocumentChunk_Header)(nil),
		(*DocumentChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_ocr_proto_rawDesc), len(file_platform_v1_ocr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_v1_ocr_proto_goTypes,
		DependencyIndexes: file_platform_v1_ocr_proto_depIdxs,
		MessageInfos:      file_platform_v1_ocr_proto_msgTypes,
	}.Build()
	File_platform_v1_ocr_proto = out.File
	file_platform_v1_ocr_proto_goTypes = nil
	file_platform_v1_ocr_proto_depIdxs = nil
}
