// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: platform/v1/ocr.proto

package platformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformOcrEngine_RecognizeImage_FullMethodName = "/deepseek.platform.v1.PlatformOcrEngine/RecognizeImage"
	PlatformOcrEngine_RecognizePdf_FullMethodName   = "/deepseek.platform.v1.PlatformOcrEngine/RecognizePdf"
	PlatformOcrEngine_RenderPdfPage_FullMethodName  = "/deepseek.platform.v1.PlatformOcrEngine/RenderPdfPage"
)

// PlatformOcrEngineClient is the client API for PlatformOcrEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Read-only platform decoding and bundled ML Kit inference. No product paths,
// credentials, business state, or authority private keys cross this boundary.
// The Android launcher supplies a per-process random credential over authenticated
// loopback gRPC. Uploads begin with exactly one header, followed by <=64 KiB data
// frames. Half-close commits only an exact length and SHA-256 match. The service
// uses private temporary files and deletes them on completion/cancellation.
type PlatformOcrEngineClient interface {
	RecognizeImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentChunk, RecognizedDocument], error)
	RecognizePdf(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentChunk, RecognizedDocument], error)
	RenderPdfPage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentChunk, RenderedPdfPage], error)
}

type platformOcrEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformOcrEngineClient(cc grpc.ClientConnInterface) PlatformOcrEngineClient {
	return &platformOcrEngineClient{cc}
}

func (c *platformOcrEngineClient) RecognizeImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentChunk, RecognizedDocument], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlatformOcrEngine_ServiceDesc.Streams[0], PlatformOcrEngine_RecognizeImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocumentChunk, RecognizedDocument]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformOcrEngine_RecognizeImageClient = grpc.ClientStreamingClient[DocumentChunk, RecognizedDocument]

func (c *platformOcrEngineClient) RecognizePdf(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentChunk, RecognizedDocument], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlatformOcrEngine_ServiceDesc.Streams[1], PlatformOcrEngine_RecognizePdf_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocumentChunk, RecognizedDocument]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformOcrEngine_RecognizePdfClient = grpc.ClientStreamingClient[DocumentChunk, RecognizedDocument]

func (c *platformOcrEngineClient) RenderPdfPage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentChunk, RenderedPdfPage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlatformOcrEngine_ServiceDesc.Streams[2], PlatformOcrEngine_RenderPdfPage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocumentChunk, RenderedPdfPage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformOcrEngine_RenderPdfPageClient = grpc.ClientStreamingClient[DocumentChunk, RenderedPdfPage]

// PlatformOcrEngineServer is the server API for PlatformOcrEngine service.
// All implementations must embed UnimplementedPlatformOcrEngineServer
// for forward compatibility.
//
// Read-only platform decoding and bundled ML Kit inference. No product paths,
// credentials, business state, or authority private keys cross this boundary.
// The Android launcher supplies a per-process random credential over authenticated
// loopback gRPC. Uploads begin with exactly one header, followed by <=64 KiB data
// frames. Half-close commits only an exact length and SHA-256 match. The service
// uses private temporary files and deletes them on completion/cancellation.
type PlatformOcrEngineServer interface {
	RecognizeImage(grpc.ClientStreamingServer[DocumentChunk, RecognizedDocument]) error
	RecognizePdf(grpc.ClientStreamingServer[DocumentChunk, RecognizedDocument]) error
	RenderPdfPage(grpc.ClientStreamingServer[DocumentChunk, RenderedPdfPage]) error
	mustEmbedUnimplementedPlatformOcrEngineServer()
}

// UnimplementedPlatformOcrEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformOcrEngineServer struct{}

func (UnimplementedPlatformOcrEngineServer) RecognizeImage(grpc.ClientStreamingServer[DocumentChunk, RecognizedDocument]) error {
	return status.Error(codes.Unimplemented, "method RecognizeImage not implemented")
}
func (UnimplementedPlatformOcrEngineServer) RecognizePdf(grpc.ClientStreamingServer[DocumentChunk, RecognizedDocument]) error {
	return status.Error(codes.Unimplemented, "method RecognizePdf not implemented")
}
func (UnimplementedPlatformOcrEngineServer) RenderPdfPage(grpc.ClientStreamingServer[DocumentChunk, RenderedPdfPage]) error {
	return status.Error(codes.Unimplemented, "method RenderPdfPage not implemented")
}
func (UnimplementedPlatformOcrEngineServer) mustEmbedUnimplementedPlatformOcrEngineServer() {}
func (UnimplementedPlatformOcrEngineServer) testEmbeddedByValue()                           {}

// UnsafePlatformOcrEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformOcrEngineServer will
// result in compilation errors.
type UnsafePlatformOcrEngineServer interface {
	mustEmbedUnimplementedPlatformOcrEngineServer()
}

func RegisterPlatformOcrEngineServer(s grpc.ServiceRegistrar, srv PlatformOcrEngineServer) {
	// If the following call panics, it indicates UnimplementedPlatformOcrEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformOcrEngine_ServiceDesc, srv)
}

func _PlatformOcrEngine_RecognizeImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlatformOcrEngineServer).RecognizeImage(&grpc.GenericServerStream[DocumentChunk, RecognizedDocument]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformOcrEngine_RecognizeImageServer = grpc.ClientStreamingServer[DocumentChunk, RecognizedDocument]

func _PlatformOcrEngine_RecognizePdf_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlatformOcrEngineServer).RecognizePdf(&grpc.GenericServerStream[DocumentChunk, RecognizedDocument]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformOcrEngine_RecognizePdfServer = grpc.ClientStreamingServer[DocumentChunk, RecognizedDocument]

func _PlatformOcrEngine_RenderPdfPage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlatformOcrEngineServer).RenderPdfPage(&grpc.GenericServerStream[DocumentChunk, RenderedPdfPage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformOcrEngine_RenderPdfPageServer = grpc.ClientStreamingServer[DocumentChunk, RenderedPdfPage]

// PlatformOcrEngine_ServiceDesc is the grpc.ServiceDesc for PlatformOcrEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformOcrEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepseek.platform.v1.PlatformOcrEngine",
	HandlerType: (*PlatformOcrEngineServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecognizeImage",
			Handler:       _PlatformOcrEngine_RecognizeImage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RecognizePdf",
			Handler:       _PlatformOcrEngine_RecognizePdf_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RenderPdfPage",
			Handler:       _PlatformOcrEngine_RenderPdfPage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "platform/v1/ocr.proto",
}
