// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: browser/v1/browser.proto

package browserv1

import (
	commonv1 "github.com/leizd/DeepSeek-Infra/go/internal/protocol/commonv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// `Status` says what the engine can actually do right now. A sidecar without a browser
// answers `available: false` with a reason, and every action above refuses with the
// same code. That refusal is the static fallback's cue, not a failure: the gateway
// keeps reporting `playwright_available() == false` until a real engine answers.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type StatusResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Available bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	// "cdp_chromium" once the engine exists; empty while it does not.
	EngineKind       string `protobuf:"bytes,2,opt,name=engine_kind,json=engineKind,proto3" json:"engine_kind,omitempty"`
	ChromiumRevision string `protobuf:"bytes,3,opt,name=chromium_revision,json=chromiumRevision,proto3" json:"chromium_revision,omitempty"`
	// Empty when available; otherwise why not, in one line.
	Reason        string                `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Error         *commonv1.ErrorDetail `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *StatusResponse) GetEngineKind() string {
	if x != nil {
		return x.EngineKind
	}
	return ""
}

func (x *StatusResponse) GetChromiumRevision() string {
	if x != nil {
		return x.ChromiumRevision
	}
	return ""
}

func (x *StatusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StatusResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

// Mirrors the oracle's `read_page` shape: `{url, title, text, html, selector}`.
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Html          string                 `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	Selector      string                 `protobuf:"bytes,5,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_browser_v1_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Page) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *Page) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type OpenUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenUrlRequest) Reset() {
	*x = OpenUrlRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenUrlRequest) ProtoMessage() {}

func (x *OpenUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenUrlRequest.ProtoReflect.Descriptor instead.
func (*OpenUrlRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{3}
}

func (x *OpenUrlRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *OpenUrlRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ReadPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPageRequest) Reset() {
	*x = ReadPageRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPageRequest) ProtoMessage() {}

func (x *ReadPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPageRequest.ProtoReflect.Descriptor instead.
func (*ReadPageRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{4}
}

func (x *ReadPageRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ReadPageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadPageRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{5}
}

func (x *SessionRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SelectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectorRequest) Reset() {
	*x = SelectorRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorRequest) ProtoMessage() {}

func (x *SelectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorRequest.ProtoReflect.Descriptor instead.
func (*SelectorRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{6}
}

func (x *SelectorRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *SelectorRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SelectorRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type TypeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTextRequest) Reset() {
	*x = TypeTextRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTextRequest) ProtoMessage() {}

func (x *TypeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTextRequest.ProtoReflect.Descriptor instead.
func (*TypeTextRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{7}
}

func (x *TypeTextRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *TypeTextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TypeTextRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *TypeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRequest) Reset() {
	*x = SelectRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequest) ProtoMessage() {}

func (x *SelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequest.ProtoReflect.Descriptor instead.
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{8}
}

func (x *SelectRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *SelectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SelectRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SelectRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ScrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollRequest) Reset() {
	*x = ScrollRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollRequest) ProtoMessage() {}

func (x *ScrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollRequest.ProtoReflect.Descriptor instead.
func (*ScrollRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{9}
}

func (x *ScrollRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ScrollRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScrollRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScrollRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{10}
}

func (x *ScreenshotRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *ScreenshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScreenshotRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Selector      string                 `protobuf:"bytes,4,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *DownloadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DownloadRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

// Mirrors `{href, text, title}` from the oracle's `ParsedHTML.links`.
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_browser_v1_browser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{12}
}

func (x *Link) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Link) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{13}
}

func (x *PageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PageResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type LinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Links         []*Link                `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinksResponse) Reset() {
	*x = LinksResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksResponse) ProtoMessage() {}

func (x *LinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksResponse.ProtoReflect.Descriptor instead.
func (*LinksResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{14}
}

func (x *LinksResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinksResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *LinksResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Selector      string                 `protobuf:"bytes,4,opt,name=selector,proto3" json:"selector,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{15}
}

func (x *ScreenshotResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScreenshotResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ScreenshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScreenshotResponse) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ScreenshotResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type SelectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Selected      []string               `protobuf:"bytes,4,rep,name=selected,proto3" json:"selected,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectResponse) Reset() {
	*x = SelectResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectResponse) ProtoMessage() {}

func (x *SelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectResponse.ProtoReflect.Descriptor instead.
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{16}
}

func (x *SelectResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SelectResponse) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SelectResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SelectResponse) GetSelected() []string {
	if x != nil {
		return x.Selected
	}
	return nil
}

func (x *SelectResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Error         *commonv1.ErrorDetail  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{18}
}

func (x *ActionResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ActionResponse) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ActionResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *commonv1.ActionFence  `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_browser_v1_browser_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{19}
}

func (x *CloseSessionRequest) GetFence() *commonv1.ActionFence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when this process had no browser for the session id.
	Closed        bool                  `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	Error         *commonv1.ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_browser_v1_browser_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_browser_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_browser_proto_rawDescGZIP(), []int{20}
}

func (x *CloseSessionResponse) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *CloseSessionResponse) GetError() *commonv1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_browser_v1_browser_proto protoreflect.FileDescriptor

const file_browser_v1_browser_proto_rawDesc = "" +
	"\n" +
	"\x18browser/v1/browser.proto\x12\x13deepseek.browser.v1\x1a\x16common/v1/common.proto\"F\n" +
	"\rStatusRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\"\xcb\x01\n" +
	"\x0eStatusResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x1f\n" +
	"\vengine_kind\x18\x02 \x01(\tR\n" +
	"engineKind\x12+\n" +
	"\x11chromium_revision\x18\x03 \x01(\tR\x10chromiumRevision\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x125\n" +
	"\x05error\x18\x05 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"r\n" +
	"\x04Page\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x12\n" +
	"\x04html\x18\x04 \x01(\tR\x04html\x12\x1a\n" +
	"\bselector\x18\x05 \x01(\tR\bselector\"x\n" +
	"\x0eOpenUrlRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x83\x01\n" +
	"\x0fReadPageRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\"f\n" +
	"\x0eSessionRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x83\x01\n" +
	"\x0fSelectorRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\"\x97\x01\n" +
	"\x0fTypeTextRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x97\x01\n" +
	"\rSelectRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x81\x01\n" +
	"\rScrollRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\"\x85\x01\n" +
	"\x11ScreenshotRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\"\x95\x01\n" +
	"\x0fDownloadRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bselector\x18\x04 \x01(\tR\bselector\"D\n" +
	"\x04Link\x12\x12\n" +
	"\x04href\x18\x01 \x01(\tR\x04href\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"t\n" +
	"\fPageResponse\x12-\n" +
	"\x04page\x18\x01 \x01(\v2\x19.deepseek.browser.v1.PageR\x04page\x125\n" +
	"\x05error\x18\x02 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"\x89\x01\n" +
	"\rLinksResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12/\n" +
	"\x05links\x18\x02 \x03(\v2\x19.deepseek.browser.v1.LinkR\x05links\x125\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"\xaa\x01\n" +
	"\x12ScreenshotResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bselector\x18\x04 \x01(\tR\bselector\x125\n" +
	"\x05error\x18\x05 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"\xa7\x01\n" +
	"\x0eSelectResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1a\n" +
	"\bselected\x18\x04 \x03(\tR\bselected\x125\n" +
	"\x05error\x18\x05 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"\x8b\x01\n" +
	"\x10DownloadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x125\n" +
	"\x05error\x18\x04 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"u\n" +
	"\x0eActionResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x125\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error\"k\n" +
	"\x13CloseSessionRequest\x125\n" +
	"\x05fence\x18\x01 \x01(\v2\x1f.deepseek.common.v1.ActionFenceR\x05fence\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"e\n" +
	"\x14CloseSessionResponse\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed\x125\n" +
	"\x05error\x18\x02 \x01(\v2\x1f.deepseek.common.v1.ErrorDetailR\x05error2\xd1\a\n" +
	"\rBrowserEngine\x12Q\n" +
	"\x06Status\x12\".deepseek.browser.v1.StatusRequest\x1a#.deepseek.browser.v1.StatusResponse\x12Q\n" +
	"\aOpenUrl\x12#.deepseek.browser.v1.OpenUrlRequest\x1a!.deepseek.browser.v1.PageResponse\x12S\n" +
	"\bReadPage\x12$.deepseek.browser.v1.ReadPageRequest\x1a!.deepseek.browser.v1.PageResponse\x12W\n" +
	"\fExtractLinks\x12#.deepseek.browser.v1.SessionRequest\x1a\".deepseek.browser.v1.LinksResponse\x12]\n" +
	"\n" +
	"Screenshot\x12&.deepseek.browser.v1.ScreenshotRequest\x1a'.deepseek.browser.v1.ScreenshotResponse\x12R\n" +
	"\x05Click\x12$.deepseek.browser.v1.SelectorRequest\x1a#.deepseek.browser.v1.ActionResponse\x12U\n" +
	"\bTypeText\x12$.deepseek.browser.v1.TypeTextRequest\x1a#.deepseek.browser.v1.ActionResponse\x12Q\n" +
	"\x06Select\x12\".deepseek.browser.v1.SelectRequest\x1a#.deepseek.browser.v1.SelectResponse\x12Q\n" +
	"\x06Scroll\x12\".deepseek.browser.v1.ScrollRequest\x1a#.deepseek.browser.v1.ActionResponse\x12W\n" +
	"\bDownload\x12$.deepseek.browser.v1.DownloadRequest\x1a%.deepseek.browser.v1.DownloadResponse\x12c\n" +
	"\fCloseSession\x12(.deepseek.browser.v1.CloseSessionRequest\x1a).deepseek.browser.v1.CloseSessionResponseBJZHgithub.com/leizd/DeepSeek-Infra/go/internal/protocol/browserv1;browserv1b\x06proto3"

var (
	file_browser_v1_browser_proto_rawDescOnce sync.Once
	file_browser_v1_browser_proto_rawDescData []byte
)

func file_browser_v1_browser_proto_rawDescGZIP() []byte {
	file_browser_v1_browser_proto_rawDescOnce.Do(func() {
		file_browser_v1_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browser_v1_browser_proto_rawDesc), len(file_browser_v1_browser_proto_rawDesc)))
	})
	return file_browser_v1_browser_proto_rawDescData
}

var file_browser_v1_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_browser_v1_browser_proto_goTypes = []any{
	(*StatusRequest)(nil),        // 0: deepseek.browser.v1.StatusRequest
	(*StatusResponse)(nil),       // 1: deepseek.browser.v1.StatusResponse
	(*Page)(nil),                 // 2: deepseek.browser.v1.Page
	(*OpenUrlRequest)(nil),       // 3: deepseek.browser.v1.OpenUrlRequest
	(*ReadPageRequest)(nil),      // 4: deepseek.browser.v1.ReadPageRequest
	(*SessionRequest)(nil),       // 5: deepseek.browser.v1.SessionRequest
	(*SelectorRequest)(nil),      // 6: deepseek.browser.v1.SelectorRequest
	(*TypeTextRequest)(nil),      // 7: deepseek.browser.v1.TypeTextRequest
	(*SelectRequest)(nil),        // 8: deepseek.browser.v1.SelectRequest
	(*ScrollRequest)(nil),        // 9: deepseek.browser.v1.ScrollRequest
	(*ScreenshotRequest)(nil),    // 10: deepseek.browser.v1.ScreenshotRequest
	(*DownloadRequest)(nil),      // 11: deepseek.browser.v1.DownloadRequest
	(*Link)(nil),                 // 12: deepseek.browser.v1.Link
	(*PageResponse)(nil),         // 13: deepseek.browser.v1.PageResponse
	(*LinksResponse)(nil),        // 14: deepseek.browser.v1.LinksResponse
	(*ScreenshotResponse)(nil),   // 15: deepseek.browser.v1.ScreenshotResponse
	(*SelectResponse)(nil),       // 16: deepseek.browser.v1.SelectResponse
	(*DownloadResponse)(nil),     // 17: deepseek.browser.v1.DownloadResponse
	(*ActionResponse)(nil),       // 18: deepseek.browser.v1.ActionResponse
	(*CloseSessionRequest)(nil),  // 19: deepseek.browser.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 20: deepseek.browser.v1.CloseSessionResponse
	(*commonv1.ActionFence)(nil), // 21: deepseek.common.v1.ActionFence
	(*commonv1.ErrorDetail)(nil), // 22: deepseek.common.v1.ErrorDetail
}
var file_browser_v1_browser_proto_depIdxs = []int32{
	21, // 0: deepseek.browser.v1.StatusRequest.fence:type_name -> deepseek.common.v1.ActionFence
	22, // 1: deepseek.browser.v1.StatusResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	21, // 2: deepseek.browser.v1.OpenUrlRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 3: deepseek.browser.v1.ReadPageRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 4: deepseek.browser.v1.SessionRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 5: deepseek.browser.v1.SelectorRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 6: deepseek.browser.v1.TypeTextRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 7: deepseek.browser.v1.SelectRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 8: deepseek.browser.v1.ScrollRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 9: deepseek.browser.v1.ScreenshotRequest.fence:type_name -> deepseek.common.v1.ActionFence
	21, // 10: deepseek.browser.v1.DownloadRequest.fence:type_name -> deepseek.common.v1.ActionFence
	2,  // 11: deepseek.browser.v1.PageResponse.page:type_name -> deepseek.browser.v1.Page
	22, // 12: deepseek.browser.v1.PageResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	12, // 13: deepseek.browser.v1.LinksResponse.links:type_name -> deepseek.browser.v1.Link
	22, // 14: deepseek.browser.v1.LinksResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	22, // 15: deepseek.browser.v1.ScreenshotResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	22, // 16: deepseek.browser.v1.SelectResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	22, // 17: deepseek.browser.v1.DownloadResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	22, // 18: deepseek.browser.v1.ActionResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	21, // 19: deepseek.browser.v1.CloseSessionRequest.fence:type_name -> deepseek.common.v1.ActionFence
	22, // 20: deepseek.browser.v1.CloseSessionResponse.error:type_name -> deepseek.common.v1.ErrorDetail
	0,  // 21: deepseek.browser.v1.BrowserEngine.Status:input_type -> deepseek.browser.v1.StatusRequest
	3,  // 22: deepseek.browser.v1.BrowserEngine.OpenUrl:input_type -> deepseek.browser.v1.OpenUrlRequest
	4,  // 23: deepseek.browser.v1.BrowserEngine.ReadPage:input_type -> deepseek.browser.v1.ReadPageRequest
	5,  // 24: deepseek.browser.v1.BrowserEngine.ExtractLinks:input_type -> deepseek.browser.v1.SessionRequest
	10, // 25: deepseek.browser.v1.BrowserEngine.Screenshot:input_type -> deepseek.browser.v1.ScreenshotRequest
	6,  // 26: deepseek.browser.v1.BrowserEngine.Click:input_type -> deepseek.browser.v1.SelectorRequest
	7,  // 27: deepseek.browser.v1.BrowserEngine.TypeText:input_type -> deepseek.browser.v1.TypeTextRequest
	8,  // 28: deepseek.browser.v1.BrowserEngine.Select:input_type -> deepseek.browser.v1.SelectRequest
	9,  // 29: deepseek.browser.v1.BrowserEngine.Scroll:input_type -> deepseek.browser.v1.ScrollRequest
	11, // 30: deepseek.browser.v1.BrowserEngine.Download:input_type -> deepseek.browser.v1.DownloadRequest
	19, // 31: deepseek.browser.v1.BrowserEngine.CloseSession:input_type -> deepseek.browser.v1.CloseSessionRequest
	1,  // 32: deepseek.browser.v1.BrowserEngine.Status:output_type -> deepseek.browser.v1.StatusResponse
	13, // 33: deepseek.browser.v1.BrowserEngine.OpenUrl:output_type -> deepseek.browser.v1.PageResponse
	13, // 34: deepseek.browser.v1.BrowserEngine.ReadPage:output_type -> deepseek.browser.v1.PageResponse
	14, // 35: deepseek.browser.v1.BrowserEngine.ExtractLinks:output_type -> deepseek.browser.v1.LinksResponse
	15, // 36: deepseek.browser.v1.BrowserEngine.Screenshot:output_type -> deepseek.browser.v1.ScreenshotResponse
	18, // 37: deepseek.browser.v1.BrowserEngine.Click:output_type -> deepseek.browser.v1.ActionResponse
	18, // 38: deepseek.browser.v1.BrowserEngine.TypeText:output_type -> deepseek.browser.v1.ActionResponse
	16, // 39: deepseek.browser.v1.BrowserEngine.Select:output_type -> deepseek.browser.v1.SelectResponse
	18, // 40: deepseek.browser.v1.BrowserEngine.Scroll:output_type -> deepseek.browser.v1.ActionResponse
	17, // 41: deepseek.browser.v1.BrowserEngine.Download:output_type -> deepseek.browser.v1.DownloadResponse
	20, // 42: deepseek.browser.v1.BrowserEngine.CloseSession:output_type -> deepseek.browser.v1.CloseSessionResponse
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_browser_v1_browser_proto_init() }
func file_browser_v1_browser_proto_init() {
	if File_browser_v1_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browser_v1_browser_proto_rawDesc), len(file_browser_v1_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_browser_v1_browser_proto_goTypes,
		DependencyIndexes: file_browser_v1_browser_proto_depIdxs,
		MessageInfos:      file_browser_v1_browser_proto_msgTypes,
	}.Build()
	File_browser_v1_browser_proto = out.File
	file_browser_v1_browser_proto_goTypes = nil
	file_browser_v1_browser_proto_depIdxs = nil
}
