// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: browser/v1/browser.proto

package browserv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrowserEngine_Status_FullMethodName       = "/deepseek.browser.v1.BrowserEngine/Status"
	BrowserEngine_OpenUrl_FullMethodName      = "/deepseek.browser.v1.BrowserEngine/OpenUrl"
	BrowserEngine_ReadPage_FullMethodName     = "/deepseek.browser.v1.BrowserEngine/ReadPage"
	BrowserEngine_ExtractLinks_FullMethodName = "/deepseek.browser.v1.BrowserEngine/ExtractLinks"
	BrowserEngine_Screenshot_FullMethodName   = "/deepseek.browser.v1.BrowserEngine/Screenshot"
	BrowserEngine_Click_FullMethodName        = "/deepseek.browser.v1.BrowserEngine/Click"
	BrowserEngine_TypeText_FullMethodName     = "/deepseek.browser.v1.BrowserEngine/TypeText"
	BrowserEngine_Select_FullMethodName       = "/deepseek.browser.v1.BrowserEngine/Select"
	BrowserEngine_Scroll_FullMethodName       = "/deepseek.browser.v1.BrowserEngine/Scroll"
	BrowserEngine_Download_FullMethodName     = "/deepseek.browser.v1.BrowserEngine/Download"
	BrowserEngine_CloseSession_FullMethodName = "/deepseek.browser.v1.BrowserEngine/CloseSession"
)

// BrowserEngineClient is the client API for BrowserEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The browser engine boundary (ADR-0050). A separate process owns the browser and
// answers these calls; the gateway keeps `execute_browser_action` and the safety gate
// where they are and only the controller moves behind this boundary.
//
// Call timeouts are the client's business and mirror the oracle's: `OpenUrl` 30 s
// (`domcontentloaded`), `ReadPage` 2 s, `Click`/`TypeText`/`Select` 5 s, `Download`
// 15 s. A call that exceeds them is a client deadline, not a distinct error code.
//
// Every request binds an `ActionFence` (`actionId + executionEpoch`), as ADR-0049
// requires of every native boundary; the engine treats it as the call's ordering id.
//
// Nothing here writes durable state. `Download` and `Screenshot` return bytes; media
// and RAG ownership stay where they are.
type BrowserEngineClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	OpenUrl(ctx context.Context, in *OpenUrlRequest, opts ...grpc.CallOption) (*PageResponse, error)
	ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*PageResponse, error)
	ExtractLinks(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*LinksResponse, error)
	Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
	Click(ctx context.Context, in *SelectorRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
	Scroll(ctx context.Context, in *ScrollRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	// CloseSession tears down the browser context the session id names and removes its
	// profile and staged downloads. It is `CloseSession` rather than a `Status` call
	// because closing is a real effect: without it a session the gateway has closed
	// would leave a Chromium and a profile directory behind for the engine's lifetime.
	//
	// Idempotent, and it answers `closed: false` for a session this process never had:
	// the gateway's own registry is the authority on whether the session existed, and
	// an engine that refused an unknown id would make a double close an error.
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
}

type browserEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserEngineClient(cc grpc.ClientConnInterface) BrowserEngineClient {
	return &browserEngineClient{cc}
}

func (c *browserEngineClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) OpenUrl(ctx context.Context, in *OpenUrlRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_OpenUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_ReadPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) ExtractLinks(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*LinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinksResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_ExtractLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_Screenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) Click(ctx context.Context, in *SelectorRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_Click_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_TypeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_Select_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) Scroll(ctx context.Context, in *ScrollRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_Scroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_Download_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserEngineClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, BrowserEngine_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserEngineServer is the server API for BrowserEngine service.
// All implementations must embed UnimplementedBrowserEngineServer
// for forward compatibility.
//
// The browser engine boundary (ADR-0050). A separate process owns the browser and
// answers these calls; the gateway keeps `execute_browser_action` and the safety gate
// where they are and only the controller moves behind this boundary.
//
// Call timeouts are the client's business and mirror the oracle's: `OpenUrl` 30 s
// (`domcontentloaded`), `ReadPage` 2 s, `Click`/`TypeText`/`Select` 5 s, `Download`
// 15 s. A call that exceeds them is a client deadline, not a distinct error code.
//
// Every request binds an `ActionFence` (`actionId + executionEpoch`), as ADR-0049
// requires of every native boundary; the engine treats it as the call's ordering id.
//
// Nothing here writes durable state. `Download` and `Screenshot` return bytes; media
// and RAG ownership stay where they are.
type BrowserEngineServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	OpenUrl(context.Context, *OpenUrlRequest) (*PageResponse, error)
	ReadPage(context.Context, *ReadPageRequest) (*PageResponse, error)
	ExtractLinks(context.Context, *SessionRequest) (*LinksResponse, error)
	Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	Click(context.Context, *SelectorRequest) (*ActionResponse, error)
	TypeText(context.Context, *TypeTextRequest) (*ActionResponse, error)
	Select(context.Context, *SelectRequest) (*SelectResponse, error)
	Scroll(context.Context, *ScrollRequest) (*ActionResponse, error)
	Download(context.Context, *DownloadRequest) (*DownloadResponse, error)
	// CloseSession tears down the browser context the session id names and removes its
	// profile and staged downloads. It is `CloseSession` rather than a `Status` call
	// because closing is a real effect: without it a session the gateway has closed
	// would leave a Chromium and a profile directory behind for the engine's lifetime.
	//
	// Idempotent, and it answers `closed: false` for a session this process never had:
	// the gateway's own registry is the authority on whether the session existed, and
	// an engine that refused an unknown id would make a double close an error.
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	mustEmbedUnimplementedBrowserEngineServer()
}

// UnimplementedBrowserEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserEngineServer struct{}

func (UnimplementedBrowserEngineServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedBrowserEngineServer) OpenUrl(context.Context, *OpenUrlRequest) (*PageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenUrl not implemented")
}
func (UnimplementedBrowserEngineServer) ReadPage(context.Context, *ReadPageRequest) (*PageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPage not implemented")
}
func (UnimplementedBrowserEngineServer) ExtractLinks(context.Context, *SessionRequest) (*LinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractLinks not implemented")
}
func (UnimplementedBrowserEngineServer) Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screenshot not implemented")
}
func (UnimplementedBrowserEngineServer) Click(context.Context, *SelectorRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Click not implemented")
}
func (UnimplementedBrowserEngineServer) TypeText(context.Context, *TypeTextRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TypeText not implemented")
}
func (UnimplementedBrowserEngineServer) Select(context.Context, *SelectRequest) (*SelectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Select not implemented")
}
func (UnimplementedBrowserEngineServer) Scroll(context.Context, *ScrollRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scroll not implemented")
}
func (UnimplementedBrowserEngineServer) Download(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedBrowserEngineServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedBrowserEngineServer) mustEmbedUnimplementedBrowserEngineServer() {}
func (UnimplementedBrowserEngineServer) testEmbeddedByValue()                       {}

// UnsafeBrowserEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserEngineServer will
// result in compilation errors.
type UnsafeBrowserEngineServer interface {
	mustEmbedUnimplementedBrowserEngineServer()
}

func RegisterBrowserEngineServer(s grpc.ServiceRegistrar, srv BrowserEngineServer) {
	// If the following call panics, it indicates UnimplementedBrowserEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowserEngine_ServiceDesc, srv)
}

func _BrowserEngine_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_OpenUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).OpenUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_OpenUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).OpenUrl(ctx, req.(*OpenUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_ReadPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).ReadPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_ReadPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).ReadPage(ctx, req.(*ReadPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_ExtractLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).ExtractLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_ExtractLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).ExtractLinks(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_Screenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).Screenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_Screenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).Screenshot(ctx, req.(*ScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_Click_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).Click(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_Click_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).Click(ctx, req.(*SelectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_TypeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).TypeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_TypeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).TypeText(ctx, req.(*TypeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_Select_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_Scroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).Scroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_Scroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).Scroll(ctx, req.(*ScrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).Download(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserEngine_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserEngineServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserEngine_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserEngineServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrowserEngine_ServiceDesc is the grpc.ServiceDesc for BrowserEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowserEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepseek.browser.v1.BrowserEngine",
	HandlerType: (*BrowserEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _BrowserEngine_Status_Handler,
		},
		{
			MethodName: "OpenUrl",
			Handler:    _BrowserEngine_OpenUrl_Handler,
		},
		{
			MethodName: "ReadPage",
			Handler:    _BrowserEngine_ReadPage_Handler,
		},
		{
			MethodName: "ExtractLinks",
			Handler:    _BrowserEngine_ExtractLinks_Handler,
		},
		{
			MethodName: "Screenshot",
			Handler:    _BrowserEngine_Screenshot_Handler,
		},
		{
			MethodName: "Click",
			Handler:    _BrowserEngine_Click_Handler,
		},
		{
			MethodName: "TypeText",
			Handler:    _BrowserEngine_TypeText_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _BrowserEngine_Select_Handler,
		},
		{
			MethodName: "Scroll",
			Handler:    _BrowserEngine_Scroll_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _BrowserEngine_Download_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _BrowserEngine_CloseSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "browser/v1/browser.proto",
}
