"""Shared metadata for release evidence generated by executable checks."""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from deepseek_infra.core.config import APP_VERSION


def git_commit(root: Path) -> str:
    completed = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )
    value = completed.stdout.strip()
    return value if completed.returncode == 0 and value else "unknown"


def stamp_release_report(report: dict[str, Any], *, root: Path) -> dict[str, Any]:
    stamped = dict(report)
    stamped.update(
        version=APP_VERSION,
        commit=git_commit(root),
        status="PASS" if report.get("ok") is True else "FAIL",
        generatedAt=datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
    )
    return stamped
