//! Lifecycle helpers for downloadable files generated by tools.
//!
//! Mirrors `infra/tool_runtime/generated_files.py`. `create_pptx` /
//! `create_document` / `create_mindmap` render into `<root>/.generated/{id}.{ext}`
//! and hand back a `downloadUrl`. This module owns the format-agnostic plumbing:
//! persist under a random id, resolve a download id without path traversal,
//! clean up expired files.
//!
//! Generated files are unique-id creates with a 6-hour TTL, not a durable store
//! with read-modify-write. Two runtimes writing the same directory do not share
//! a row; cleanup only unlinks expired names. That is why this is not a declared
//! ownership domain the way `memory_store` / `reminders_store` are.

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use regex::Regex;
use serde_json::{Value, json};

use crate::app_error::{AppError, codes};
use crate::entropy::Entropy;

/// `GENERATED_FILE_MAX_AGE_SECONDS`.
pub const GENERATED_FILE_MAX_AGE_SECONDS: u64 = 6 * 3600;

/// `GENERATED_MEDIA_TYPES` keys, in the oracle's registration order.
pub const GENERATED_EXTENSIONS: [&str; 5] = ["pptx", "docx", "pdf", "md", "svg"];

/// `<root>/.generated`.
pub fn generated_dir(root: &Path) -> PathBuf {
    root.join(".generated")
}

/// Mirrors `_safe_filename`.
pub fn safe_filename(title: &str) -> String {
    let stripped = unsafe_chars()
        .replace_all(title, "")
        .trim()
        .chars()
        .take(60)
        .collect::<String>();
    if stripped.is_empty() {
        "document".to_string()
    } else {
        stripped
    }
}

fn unsafe_chars() -> &'static Regex {
    static PATTERN: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    PATTERN.get_or_init(|| Regex::new(r"[^\w\u{4e00}-\u{9fff} -]").expect("static regex"))
}

fn id_re() -> &'static Regex {
    static PATTERN: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    PATTERN.get_or_init(|| Regex::new(r"^[0-9a-f]{32}$").expect("static regex"))
}

/// Mirrors `download_url`.
pub fn download_url(file_id: &str) -> String {
    format!("/api/download?id={file_id}")
}

/// Mirrors `cleanup_generated_files`. IO errors are swallowed.
pub fn cleanup_generated_files(root: &Path, now_epoch: f64) {
    let directory = generated_dir(root);
    if !directory.exists() {
        return;
    }
    let Ok(entries) = std::fs::read_dir(&directory) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        let Some(ext) = path.extension().and_then(|ext| ext.to_str()) else {
            continue;
        };
        if !GENERATED_EXTENSIONS
            .iter()
            .any(|allowed| allowed.eq_ignore_ascii_case(ext))
        {
            continue;
        }
        let Ok(metadata) = path.metadata() else {
            continue;
        };
        let Ok(modified) = metadata.modified() else {
            continue;
        };
        let mtime = modified
            .duration_since(UNIX_EPOCH)
            .map(|elapsed| elapsed.as_secs_f64())
            .unwrap_or(0.0);
        if now_epoch - mtime > GENERATED_FILE_MAX_AGE_SECONDS as f64 {
            let _ = std::fs::remove_file(&path);
        }
    }
}

/// Mirrors `store_generated_file`.
pub fn store_generated_file(
    title: &str,
    ext: &str,
    root: &Path,
    entropy: &dyn Entropy,
    now_epoch: f64,
    writer: impl FnOnce(&Path) -> std::io::Result<()>,
) -> Result<Value, AppError> {
    let normalized_ext = ext.trim().trim_start_matches('.').to_ascii_lowercase();
    if !GENERATED_EXTENSIONS
        .iter()
        .any(|allowed| *allowed == normalized_ext)
    {
        return Err(AppError {
            message: format!("不支持的生成文件类型：{ext}"),
            code: codes::INVALID_PAYLOAD,
            status: 400,
        });
    }
    let directory = generated_dir(root);
    std::fs::create_dir_all(&directory).map_err(|error| AppError {
        message: format!("cannot create generated dir: {error}"),
        code: codes::INTERNAL,
        status: 500,
    })?;
    cleanup_generated_files(root, now_epoch);
    let file_id = entropy.new_file_id()?;
    let path = directory.join(format!("{file_id}.{normalized_ext}"));
    writer(&path).map_err(|error| AppError {
        message: format!("cannot write generated file: {error}"),
        code: codes::INTERNAL,
        status: 500,
    })?;
    Ok(json!({
        "fileId": file_id,
        "filename": format!("{}.{normalized_ext}", safe_filename(title)),
        "downloadUrl": download_url(&file_id),
    }))
}

/// Mirrors `resolve_generated_file`.
pub fn resolve_generated_file(root: &Path, file_id: &str) -> Option<PathBuf> {
    if !id_re().is_match(file_id) {
        return None;
    }
    for ext in GENERATED_EXTENSIONS {
        let path = generated_dir(root).join(format!("{file_id}.{ext}"));
        if path.is_file() {
            return Some(path);
        }
    }
    None
}

/// The `(media type, attachment name)` pair `download_descriptor` returns.
///
/// The name is generic per type (`presentation.pptx`, `mindmap.svg`, `notes.md`,
/// `document.{ext}`) rather than the title the file was generated with: the download
/// id carries no title, and the oracle does not store one beside the file.
pub fn download_descriptor(path: &Path) -> (String, String) {
    let ext = path
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or_default()
        .to_ascii_lowercase();
    let media_type = match ext.as_str() {
        "pptx" => "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "pdf" => "application/pdf",
        "md" => "text/markdown; charset=utf-8",
        "svg" => "image/svg+xml",
        _ => "application/octet-stream",
    };
    let base = match ext.as_str() {
        "pptx" => "presentation",
        "svg" => "mindmap",
        "md" => "notes",
        _ => "document",
    };
    (media_type.to_string(), format!("{base}.{ext}"))
}

fn crc32(data: &[u8]) -> u32 {
    let mut crc = 0xFFFF_FFFFu32;
    for &byte in data {
        crc ^= u32::from(byte);
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                (crc >> 1) ^ 0xEDB8_8320
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

/// Uncompressed ZIP (STORE). Used by the docx/pptx writers so we do not take a
/// compression crate for unique-id generated files.
pub(crate) fn zip_store(files: &[(&str, Vec<u8>)]) -> Vec<u8> {
    let mut local = Vec::new();
    let mut central = Vec::new();
    for (name, data) in files {
        let name_bytes = name.as_bytes();
        let crc = crc32(data);
        let offset = local.len() as u32;
        local.extend_from_slice(&0x0403_4b50u32.to_le_bytes());
        local.extend_from_slice(&20u16.to_le_bytes());
        local.extend_from_slice(&0u16.to_le_bytes());
        local.extend_from_slice(&0u16.to_le_bytes());
        local.extend_from_slice(&0u16.to_le_bytes());
        local.extend_from_slice(&0u16.to_le_bytes());
        local.extend_from_slice(&crc.to_le_bytes());
        local.extend_from_slice(&(data.len() as u32).to_le_bytes());
        local.extend_from_slice(&(data.len() as u32).to_le_bytes());
        local.extend_from_slice(&(name_bytes.len() as u16).to_le_bytes());
        local.extend_from_slice(&0u16.to_le_bytes());
        local.extend_from_slice(name_bytes);
        local.extend_from_slice(data);
        central.extend_from_slice(&0x0201_4b50u32.to_le_bytes());
        central.extend_from_slice(&20u16.to_le_bytes());
        central.extend_from_slice(&20u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&crc.to_le_bytes());
        central.extend_from_slice(&(data.len() as u32).to_le_bytes());
        central.extend_from_slice(&(data.len() as u32).to_le_bytes());
        central.extend_from_slice(&(name_bytes.len() as u16).to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u32.to_le_bytes());
        central.extend_from_slice(&offset.to_le_bytes());
        central.extend_from_slice(name_bytes);
    }
    let central_offset = local.len() as u32;
    let central_size = central.len() as u32;
    let mut out = local;
    out.extend_from_slice(&central);
    out.extend_from_slice(&0x0605_4b50u32.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    out.extend_from_slice(&(files.len() as u16).to_le_bytes());
    out.extend_from_slice(&(files.len() as u16).to_le_bytes());
    out.extend_from_slice(&central_size.to_le_bytes());
    out.extend_from_slice(&central_offset.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    out
}

/// Wall clock as `time.time()`.
pub fn system_now() -> f64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|elapsed| elapsed.as_secs_f64())
        .unwrap_or(0.0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entropy::SystemEntropy;

    #[test]
    fn safe_filename_strips_punctuation_and_falls_back() {
        assert_eq!(safe_filename("Growth plan!"), "Growth plan");
        assert_eq!(safe_filename("???"), "document");
        assert_eq!(safe_filename("中文标题"), "中文标题");
    }

    #[test]
    fn the_download_descriptor_is_the_oracles_per_type_pair() {
        let cases = [
            (
                "a.pptx",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "presentation.pptx",
            ),
            (
                "a.docx",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "document.docx",
            ),
            ("a.pdf", "application/pdf", "document.pdf"),
            ("a.md", "text/markdown; charset=utf-8", "notes.md"),
            ("a.svg", "image/svg+xml", "mindmap.svg"),
            ("a.bin", "application/octet-stream", "document.bin"),
        ];
        for (name, media_type, download_name) in cases {
            let (actual_media, actual_name) = download_descriptor(Path::new(name));
            assert_eq!(actual_media, media_type, "{name}");
            assert_eq!(actual_name, download_name, "{name}");
        }
        // The extension is lower-cased, so an upper-case suffix still resolves.
        assert_eq!(
            download_descriptor(Path::new("a.PPTX")).1,
            "presentation.pptx"
        );
    }

    #[test]
    fn store_and_resolve_round_trip() {
        let root = std::env::temp_dir().join(format!("generated-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let stored = store_generated_file(
            "Growth plan",
            "svg",
            &root,
            &SystemEntropy,
            system_now(),
            |path| std::fs::write(path, "<svg></svg>"),
        )
        .unwrap();
        let file_id = stored["fileId"].as_str().unwrap();
        assert_eq!(file_id.len(), 32);
        assert_eq!(stored["filename"], "Growth plan.svg");
        assert_eq!(stored["downloadUrl"], format!("/api/download?id={file_id}"));
        let path = resolve_generated_file(&root, file_id).unwrap();
        assert_eq!(path.extension().unwrap(), "svg");
        assert_eq!(std::fs::read_to_string(path).unwrap(), "<svg></svg>");
        assert!(resolve_generated_file(&root, "../secret").is_none());
        let _ = std::fs::remove_dir_all(&root);
    }
}
